### ISSUE TITLE
MNT CI error: SciKeras requires Tensorflow > 2.7.0

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1009]
We came across an error in the "Tests - other ML packages" in the adversarial debiasing PR (#973), because SciKeras requires a newer version of Tensorflow (>2.7.0) than the one that is currently in our requirements (>2.4.0). Some options:
* Upgrade the Tensorflow requirement.
* Remove the SciKeras dependency. It seems like SciKeras is actually not used at all apart from the tests. It might be a relic from old documentation - I seem to recall we once had a notebook with a neural network example?

@fairlearn/fairlearn-maintainers 

Full traceback:

```
Starting: Run tests for TensorFlow
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.195.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash /home/vsts/work/_temp/249d110a-3cbc-4014-a467-b94e2d7ae69a.sh
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/vsts/work/1/s, configfile: pyproject.toml
collected 0 items / 1 error

==================================== ERRORS ====================================
___________ ERROR collecting test_othermlpackages/test_tensorflow.py ___________
ImportError while importing test module '/home/vsts/work/1/s/test_othermlpackages/test_tensorflow.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/share/miniconda/envs/test-conda-env/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_othermlpackages/test_tensorflow.py:13: in <module>
    from scikeras.wrappers import KerasClassifier # noqa
/usr/share/miniconda/envs/test-conda-env/lib/python3.8/site-packages/scikeras/__init__.py:25: in <module>
    raise ImportError(TF_VERSION_ERR)
E   ImportError: SciKeras requires TensorFlow >= 2.7.0.
------------ generated xml file: /home/vsts/work/1/s/TEST-TEST.xml -------------
=========================== short test summary info ============================
ERROR test_othermlpackages/test_tensorflow.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 2.87s ===============================
##[error]Bash exited with code '2'.
Finishing: Run tests for TensorFlow
```

**Comment by riedgar-ms** [comment]
I don't have any objection to bumping the TF requirement @hildeweerts . Those tests are only there to show that we can work with other packages, and are not meant to be comprehensive. Is TensorFlow a package which people expect to upgrade regularly, or does it have a long term support structure?

**Comment by hildeweerts** [comment]
>  Is TensorFlow a package which people expect to upgrade regularly, or does it have a long term support structure?

I am not a TensorFlow user myself, but I've asked around and it seems to be pretty standard for Tensorflow to have strong backward compatibility.

I do recall that @adrinjalali mentioned at some point that if we are going to add some deep learning examples etc., he'd prefer to go for PyTorch instead, so that's maybe something to consider as well.

**Comment by romanlutz** [comment]
I agree with @riedgar-ms and suspect the former is much easier.

I'm a little confused as to why this broke in the first place. What changed?

**Comment by hildeweerts** [comment]
> I'm a little confused as to why this broke in the first place. What changed?

I *think* the problem is that we didn't specify a version for scikeras: https://github.com/fairlearn/fairlearn/blob/94229647dda802a59bcbfe7f6d64295d64e96efa/test_othermlpackages/conda-tensorflow.yaml

**Comment by hildeweerts** [comment]
> TF is always a pain for people who test against it. It's really much better to avoid it. Also, TF is a would where it kinda makes people stay there. They have their own modules for fairness related stuff as well. It would make a lot of sense for us not to test against it, and whenever people ask, forward them to scikeras. If that doesn't work, then it's most probably a scikeras issue rather than a fairlearn one.

I think we will need to make some decisions related to this related for the adversarial debasing PR #973, in particular regarding the use of tensorflow/pytorch/scikeras examples in the documentation.

Tagging @SeanMcCarren

**Comment by romanlutz** [comment]
- using TF or PyTorch in tests is a MUCH easier task than in the docs because we'd have to include these packages in the dev requirements to make them available for the doc build. You'll find that's currently not the case. Eventually we may need to find a solution to this problem by splitting our doc build into separate pieces (maybe?) but that's certainly a major issue of its own and out of scope for this one.
- I don't have much of an opinion on the TF ecosystem, but it's quite evident to me that there are plenty of users. Having a set of tests was always a pre-step to including a short sample in the docs (for TF and many other packages). I still think that's a good idea. Just because someone is using TF doesn't mean they don't want to use Fairlearn. The choice of modeling tool is often beyond the control of the end user.

**Comment by SeanMcCarren** [comment]
> * using TF or PyTorch in tests is a MUCH easier task than in the docs because we'd have to include these packages in the dev requirements to make them available for the doc build. You'll find that's currently not the case. Eventually we may need to find a solution to this problem by splitting our doc build into separate pieces (maybe?) but that's certainly a major issue of its own and out of scope for this one.

That makes sense! Shall I make the examples in PR #973 just non-functional code then?

**Comment by adrinjalali** [comment]
> That makes sense! Shall I make the examples in PR #973 just non-functional code then (in an rst file)?

yes, but the issue there is that since it's not compiled code and the API changes quite frequently, it either becomes dead code or needs to be maintained, and since changes in TF are not gonna break our CI in that example, it's hard to keep it in mind. We could have the example also as a test and whenever the tests fail, also update the example.

**Comment by SeanMcCarren** [comment]
> yes, but the issue there is that since it's not compiled code and the API changes quite frequently, it either becomes dead code or needs to be maintained, and since changes in TF are not gonna break our CI in that example, it's hard to keep it in mind. We could have the example also as a test and whenever the tests fail, also update the example.

Oh I did not think of this problem, but this seems like a great solution! I'll be sure to cross-reference the example code and test code then as well.

**Comment by adrinjalali** [comment]
Yes. A test which basically runs the same code as the one used in the docs, to make sure it doesn't go out of date, and only run in that TF or pytorch CI.

**Comment by AIBlackBelt** [comment]
I'm still having the same issue as the author in a kaggle notebook 

`!pip3 install --upgrade tensorflow #you can skip this step if you already have an upgraded tensorflow
!pip3 install scikeras[tensorflow]`

**Comment by hildeweerts** [comment]
Hi, @AIBlackBelt. This seems to be more of an issue with tensorflow / scikeras than Fairlearn. I would recommend you to open an issue on those repositories!

**Comment by TamaraAtanasoska** [comment]
> Yes. A test which basically runs the same code as the one used in the docs, to make sure it doesn't go out of date, and only run in that TF or pytorch CI.

Since the testing method mentioned by @adrinjalali above seems to have been implemented, is there anything more that can be done about it @hildeweerts, or it can be closed?

**Comment by hildeweerts** [comment]
Agreed @TamaraAtanasoska, i'm closing the issue!
