### ISSUE TITLE
xgboost and latest pandas

### ISSUE THREAD

**Issue by riedgar-ms** [fairlearn/fairlearn#1015]
#### Describe the bug

This is more a reminder to remove a workaround. In the `othermlpackages` tests, `xgboost` was not interacting well with the latest `pandas`. It appears that the former is using a feature which the latter considers to be deprecated. PR #1014 puts a cap on the version of `pandas` as a workaround, but once `xgboost` updates, we should remove this.

**Comment by riedgar-ms** [comment]
Now that I look at it, this issue might block #981

**Comment by romanlutz** [comment]
Let me see whether I understand this right: xgboost is not working with latest pandas, so you propose waiting for xgboost to fix itself. To me this seems backwards as we can't wait for every ML package to finally work as expected. After all, we don't depend on xgboost in any way. We have some tests that could be temporarily disabled until they fix xgboost, of course.

That said, I don't know if there's a particular hurry to move forward with the version. I'm just trying to question the reasoning behind it in case we do end up feeling more strongly about bumping the pandas version at some point.
