### ISSUE TITLE
Add Discord icon to the top of the website

### ISSUE THREAD

**Issue by alliesaizan** [fairlearn/fairlearn#1037]
Right now, the menu on the top of the website only includes a link to the fairlearn GitHub repo. 
![image](https://user-images.githubusercontent.com/15962391/156587818-96f357a1-9125-481a-b207-8a801098bb5d.png)

Discord is where the fairlearn community mostly communicates, so we should add the [Discord icon](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.svgrepo.com%2Fsvg%2F353655%2Fdiscord-icon&psig=AOvVaw1i86aATKswyKDovRBr90pM&ust=1646405362654000&source=images&cd=vfe&ved=2ahUKEwj99dKHmKr2AhVoGVkFHVSUBnQQr4kDegUIARDdAQ) to the top of the page so new contributors can quickly get linked up with the rest of the team! This issue addresses a comment raised by @romanlutz  in PR #1036.

**Comment by iofall** [comment]
I can help.

Would something like this work?
![image](https://user-images.githubusercontent.com/50991099/156625850-aada4d69-3a05-4170-a290-f55b1a517a36.png)

**Comment by alliesaizan** [comment]
> I can help.
> 
> Would something like this work? ![image](https://user-images.githubusercontent.com/50991099/156625850-aada4d69-3a05-4170-a290-f55b1a517a36.png)

@romanlutz, thoughts? I think this is fine

**Comment by romanlutz** [comment]
Would be nice if it was similar in style to the GitHub button next to it. You can probably borrow the code from that(?)

I also see that we have the button already in our generated pages. It's only the landing page that's missing it.

**Comment by iofall** [comment]
> Would be nice if it was similar in style to the GitHub button next to it. You can probably borrow the code from that(?)

I added it. However, I had to decrease the nav-item font-size to make it look properly spaced.
![image](https://user-images.githubusercontent.com/50991099/156828530-3ca024b0-3fd0-48dc-9ae7-39c531d3143d.png)

**Comment by romanlutz** [comment]
Do you have a PR for this @iofall ? I don't quite know which font size you're referring to. We may not want to change the font sizes of other items, but if it's just that particular one it's perhaps fine (?).
