### ISSUE TITLE
MNT Add a pull request template

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#1050]
This is pretty simple to do, e.g., [this one in another repo](https://github.com/microsoft/responsible-ai-toolbox/blob/main/.github/PULL_REQUEST_TEMPLATE.md). That said, the experience we've had with the template there were that it's way too complicated, too much work, and should just be a lot simpler. Things I'd like to include:

```
<!--- Make sure to add a description of your changes in docs/user_guide/installation_and_version_guide/v<major>.<minor>.<patch>.rst -->
<!--- If this is your first contribution feel free to add your name to AUTHORS.md. -->

## Description
<!--- Provide a general summary of your changes. -->
<!--- Mention related issues with #<issue ID>. -->
<!--- Tag people for whom this PR may be of interest using @<username>. -->

## Tests
<!--- Select all that apply by putting an x between the brackets: [x] -->
- [ ] no new tests required
- [ ] new tests added
- [ ] existing tests adjusted

## Documentation
<!--- Select all that apply. -->
- [ ] no documentation changes needed
- [ ] user guide added or updated
- [ ] API docs added or updated
- [ ] example notebook added or updated

## Screenshots
<!--- If your PR makes changes to visualizations (e.g., matplotlib code) or the website, please include a screenshot of the result. -->

```

This list may not be comprehensive (or even too detailed!) so please comment with your own perspective. Once people like it we can mark it as "help wanted" or directly open a PR.

@fairlearn/fairlearn-maintainers

**Comment by hildeweerts** [comment]
What is the purpose of the checkboxes under "Tests" and "Documentation"? Aren't those obvious from the PR itself? Or is this more as a tool to remind prospective contributors that tests and documentation are important?

I'm definitely in favor of adding "description" and "screenshots" to the template! 
Nitpick: maybe add PRs to possible references under description (in addition to issues)?

**Comment by adrinjalali** [comment]
I find PR templates to be great for first time contributors. And others can simply ignore it. I'd be in favor of having something there.

**Comment by romanlutz** [comment]
@hildeweerts it's the same reason checklists make sense anywhere else 🙂 If you check our PRs we're discussing all of these with every contributor (can you add a user guide? Can you update the example? Etc) whereas this prompts people to think about it themselves before anyone even has to write anything.

FWIW I use these for myself, too! No better way to check yourself than by holding yourself to the same standards that apply to everyone. 😎 Besides, putting a couple of Xs in checkboxes takes 10 seconds max. If someone deletes it from the description I wouldn't necessarily mind, but I don't quite see why given the extremely low effort required. It's definitely true that the main benefit is for newer contributors. This is something they definitely see unlike the contributor guide which they aren't guaranteed to come across.

Your point about PRs makes sense, of course, @hildeweerts. Same for discussions now that I think about it.

**Comment by hildeweerts** [comment]
Makes sense, @romanlutz! Let's go for it :)
