### ISSUE TITLE
CI test_othermlpackages not triggered

### ISSUE THREAD

**Issue by SeanMcCarren** [fairlearn/fairlearn#1053]
In [this CI run](https://github.com/fairlearn/fairlearn/runs/5658032662) the test_othermlpackages should have been triggered (I think) because that commit changed something in `fairlearn\test_othermlpackages\adversarial_fairness.py`. Any ideas why it did not trigger? Perhaps because I pushed other commits shortly after?

**Comment by SeanMcCarren** [comment]
Ohhh. It is in [this PR](https://github.com/fairlearn/fairlearn/pull/973), and [this comment](https://github.com/fairlearn/fairlearn/pull/973/commits/374000348c8a44214421be3c1bdb063d5ac0e05c) should have triggered that CI (I think!)

**Comment by romanlutz** [comment]
Right now it looks like you have conflicts with `main` so it can't trigger the pipelines. If you resolve those first it should trigger it. Happy to look into it if it doesn't do that.
