### ISSUE TITLE
ENH Add SciPy tutorial dataset to fairlearn.datasets

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1066]
Once we have added the Scipy tutorial dataset to OpenML (#1064) we should add fetch functionality to Fairlearn.

Completing this item requires:
- [x] implement a function `fairlearn.datasets.fetch_...` (we need to come up with a name)
- [x] adjust relevant unit tests in `test.unit.datasets`
- [x] descriptive API reference (directly in the docstring)
- [x] a user guide in `docs.user_guide.datasets` [~~possibly in a separate PR~~]

**Comment by romanlutz** [comment]
I would argue it's a good idea to keep the user guide in the same PR. These tasks have a tendency to not get done if they don't happen in one PR 🙂

**Comment by hildeweerts** [comment]
> I would argue it's a good idea to keep the user guide in the same PR. These tasks have a tendency to not get done if they don't happen in one PR 🙂

Fair enough! I was mostly thinking of prospective contributors who would like to contribute to the user guide section but are less comfortable with the code part (which is arguably very minimal, but can still be intimidating for first-time contributors).

**Comment by rensoostenbach** [comment]
I will start on this issue either this week or next week! #1064 is closed, so we're not blocked anymore there.

**Comment by hildeweerts** [comment]
Awesome! I've assigned the issue to you @rensoostenbach

**Comment by romanlutz** [comment]
@hildeweerts this looks like it's ready to close (?)

**Comment by hildeweerts** [comment]
good catch @romanlutz
