### ISSUE TITLE
fairlearn.org is down

### ISSUE THREAD

**Issue by omri374** [fairlearn/fairlearn#1074]
#### Describe the bug
https://fairlearn.org website is down

#### Steps/Code to Reproduce

Go to https://fairlean.org, the GH page is not showing:
![image](https://user-images.githubusercontent.com/3776619/165458445-bfd07569-7a4b-4e4f-b871-af9f0d55b48a.png)

**Comment by romanlutz** [comment]
Thanks for reporting!
#1073 fixed this and #1076 is fixing the styling.
