### ISSUE TITLE
Release pipeline broken

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#1078]
Since our Azure DevOps tenant is orphaned and we can't seem to get it back we have to consider migrating to another tenant or completely off of ADO towards GitHub Actions. I feel like that's a good thing regardless since everything will be in the same place (GitHub). @adrinjalali is considering taking care of this migration.

Relatedly, the release definition is also on Azure DevOps. Since we originally had the release definition in a Microsoft-owned tenant, I had moved it to the current orphaned independent tenant several months ago. I never actually got it to work, though, so we may have to rewrite the release logic into a GitHub Action. I am somewhat confident that we can borrow from other repos for this, though, since we're not the only ones releasing to PyPI.

Apologies for the disruption all of this causes. I deserve a good chunk of the blame for orphaning the tenant 🙁

**Comment by riedgar-ms** [comment]
Latest release done with GitHub workflows.
