### ISSUE TITLE
Bring Fairness to ML.Net

### ISSUE THREAD

**Issue by LittleLittleCloud** [fairlearn/fairlearn#1091]
Hi fairlearn team, greeting from [ML.Net](https://github.com/dotnet/machinelearning), which is an open-source machine learning library under Dotnet foundation.  

We are reaching out to see if it's possible for us to leverage fairlearn into ml.net so that we can bring ways to evaluate or mitigate unfairness when training a ml.net model. 

And also, many thanks to @romanlutz and @riedgar-ms for their eagerness and willingness to guide us on this new topic.

**Comment by MiroDudik** [comment]
Thanks for reaching out. Let us know how you'd envision collaborating. I think that beginning with some form of informal collaboration might be best. And if there's interest for something more formal, we could discuss that. You can get a sense of mission/direction of Fairlearn here: https://fairlearn.org/main/about/index.html

(And follow the links to our governance, the use of the Fairlearn trademark etc.)

@fairlearn/fairlearn-maintainers

**Comment by LittleLittleCloud** [comment]
Thanks @MiroDudik, based on our last discussion, `MetricFrame` and its group metric can be a good place to start, then we can start adding constraints and reducing methods.

So maybe

- MetricFrame
  - Binary/Regression
- Constraints
  - Demographic Parity
  - Equalized odds
  - Bounded group loss
- Reduction
  - Grid search

would be good to consider leveraging into ML.Net for fairness training at the beginning?

Also, as @romanlutz and @riedgar-ms mentioned, it's crucial to provide proper guidance like education material to the audience as fairness is more than a problem that can be solved by code only. So there'll be more work to do other than just implementing fairness algorithms in csharp/ML.Net.

I also create a code example on what could fairlearn api in ml.net looks like. There might be a bit different from what it is in python because of the language differences. You can also leave comments under this [pr](https://github.com/LittleLittleCloud/Microsoft.ML.FairLearn/pull/3/files)

```csharp
IDataView testData = null;
var context = new MLContext();

// train a model using fair learn
// create a fairlearn experiment using AutoML
var experiment = context.Auto().CreateExperiment();

// reducing demographic parity using "Zone" as sensitive feature.
var constraint = new DemographicParity(bound: 0.9);
experiment.SetSensitiveFeature("Zone");
experiment.SetConstraint(constraint, weight: 0.5);
experiment.ReducingConstraintUseGridSearch(gridLimit: 10, gridSize: 100);

var result = await experiment.Run();
var bestModel = result.Model;

// assess a model using group metric
var evaluateData = bestModel.Transform(testData);
var groupMetric = context.FairLearn().Metric.BinaryClassificationMetrics(evaluateData, "Label", "Predicted", "Zone");

// output
// | Accuracy | AOC | .. 
// | 0.33     | 0.4 |
// equal to call context.Binary.Evaluate(evaluateData, "Label");
groupMetric.OverAll();

// output 
// | Zone  | Accuracy   | AUC | ...
// | 98101 | 0.2        | 0.3 |
// | 98004 | 0.5        | 0.9 |
// | 98010 | 0.1        | 0.7 |
groupMetric.ByGroup();

// output 
// | Accuracy   | AUC | ...
// | 0.4        | 0.6 |
groupMetric.DifferenceBetweenGroups();
```

**Comment by LittleLittleCloud** [comment]
@adrinjalali



`Fairlearn` in ML.Net will have its own implementation and we will have @jordi1215 help us with that. Since we are leveraging the existing algorithm and API from fairlearn, we want to make sure that the fairlearn community is involved and okay with it before moving forward.



@romanlutz thanks for your assistance as well as the rest of the fairlearn members. We'll reach out as questions come up and we have a prototype. If you want you can close this issue and we'll track this work in the ML.NET repo.

**Comment by luisquintanilla** [comment]
Thanks @adrinjalali @romanlutz @MiroDudik for your input. We're excited to provide .NET developers with guidance and tools to help them in their model building process. 

One question I had though. As @LittleLittleCloud mentioned we'll be leveraging the existing docs, algorithm, and API from fairlearn, is it okay for us to use the fairlearn name in the .NET implementation?

**Comment by adrinjalali** [comment]
That's a very good question. You could call it maybe fairlearn.net, but I think that might result in confusion for users and they might expect certain compatibilities between the APIs or what's included in the two projects.

I personally have no idea of you using the term (others might have a different opinion), but I'm not sure if it's the best thing to do in terms of confusing/not confusing the users.

**Comment by luisquintanilla** [comment]
>...that might result in confusion for users and they might expect certain compatibilities between the APIs or what's included in the two projects.

I suspect that may be the case as well.

**Comment by adrinjalali** [comment]
Closing since there seems to be no required action ATM from our side.

I'd like to thank you @LittleLittleCloud and @luisquintanilla for the heads up ❤️ 

I wish you luck in the implementations, and happy to have you open more issues on specific challenges on this repo as you encounter them 😃

**Comment by MiroDudik** [comment]
[pinging @LittleLittleCloud and @luisquintanilla to confirm]

**Comment by luisquintanilla** [comment]
@MiroDudik apologies for the delayed response. Thanks for providing the trademark policy which provides clearer guidance and also aligns with the point made by @adrinjalali re: users thinking we're distributing the fairlearn package in .NET. 

The following clause basically excludes us from using the name `fairlearn.net`:

> You may not use or register, in whole or in part, the Marks as part of your own trademark, service mark, domain name, company name, trade name, product name or service name.

With that in mind, we'll consult with the community on what they'd like for it to be named (other than fairlearn.net). Thanks again for all your help 🙂
