### ISSUE TITLE
RFC remove test_othermlpackages

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#1101]
We have a folder called `test_othermlpackages` which does some very minimal tests against other frameworks.

The tests don't necessarily seem very meaningful, and it has added quite a bit of overhead to the CI process (nightly runs which we don't necessarily check and their own conda environments which we haven't updated in a while).

I don't recall any issues triggered by failures of these tests. Can we remove them?

cc @fairlearn/fairlearn-maintainers

**Comment by SeanMcCarren** [comment]
Parts of adversarial fairness are hard to test without PyTorch or TensorFlow loaded, so the important test cases for adversarial fairness are in test_othermlpackages.

**Comment by adrinjalali** [comment]
In that case, it seems they shouldn't be a cron job, rather run for all PRs?

**Comment by adrinjalali** [comment]
cron jobs are jobs which are run on a pre-defined period rather than on a trigger (like committing to a PR).

So It seems we need them, I'll re-work our CI, probably remove xgboost and lightgbm (not sure if they're adding much), and see where I can get.

**Comment by romanlutz** [comment]
Hmm, I have actually seen these tests catch a few issues that we could avoid since they were triggered on PRs.

I'm not a huge fan of cronjobs for such things. As you may know some of our nightly tests are broken. #1055

**Comment by romanlutz** [comment]
How about using the `paths` filter in the trigger instead? That could be limited to directories that rely on it.

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-affects-specific-files

**Comment by romanlutz** [comment]
Just wanted to update this based on where we are today. @adrinjalali did lots of work rewriting the CI which runs these on GitHub Actions now. They all just take a few seconds, so I'm tempted to keep them. Is there anything else you want to get out of this issue @adrinjalali ?

**Comment by adrinjalali** [comment]
I guess we can keep them then :)
