### ISSUE TITLE
Format of the notebook in PR #1008

### ISSUE THREAD

**Issue by MiroDudik** [fairlearn/fairlearn#1108]
PR #1008 is a major update of the credit loan notebook linked from the Fairlearn landing page, but the updated notebook is in .ipynb format. While we would like to move all of the old notebooks into .py format, after conversation with @LeJit, I don't think that he will be able to do that for the Credit Card Loans notebook (otherwise the PR is almost finished). How do we proceed?

@adrinjalali suggested:
> I'd like to remove the old one in this PR and add a new `.py` file instead.

I think that @adrinjalali's suggestion is sensible, but it would stall the PR, so I am not too crazy about it.

My suggestion is to accept the current PR, and create an issue to convert .ipynb into .py. That will mean that the current PR can be completed, and it will lead to an immediate improvement of our webpage. I don't think that we should allow this more generally though... the only reason why I'm willing to split the work like this here is because we're linking to this notebook from the landing page.

**Comment by romanlutz** [comment]
The conversion to `.py` is a matter of 5-10 minutes, isn't it? Why don't we get the `.ipynb` file in shape so that we're happy to merge it (content-wise) and then convert it?

If people aren't sure how to do the conversion I'm happy to take care of that... I guess at that point it can be a separate PR 😆

**Comment by MiroDudik** [comment]
I think that @LeJit was looking into the conversion into `.py` and it was more annoying than you make it sound.

@LeJit -- do you want to take up @romanlutz on the offer to move your notebook into `.ipynb`?

@adrinjalali -- would you be okay splitting this up into two PRs?

**Comment by romanlutz** [comment]
Hmm, the PR does include the `.py` file under `examples` now. I chatted with @LeJit about this a few days ago. Seems like he was able to do it all by himself (yeay!) 🙂

**Comment by MiroDudik** [comment]
I guess that works too... :-)

@LeJit : you okay seeing this PR through, including having this notebook in `.py` format?

**Comment by LeJit** [comment]
Yes. I should be able to finish the conversion to `.py` format.

I also think it may be worth keeping the `.ipynb` notebook somewhere if we want to make a second tutorial/workshop presentation out of it.

**Comment by romanlutz** [comment]
You can download the `.ipynb` from the sphinx-gallery generated page 🙂

**Comment by adrinjalali** [comment]
I guess we can close this one now then :)
