### ISSUE TITLE
[Doc Bug] Bad link from Fairlearn logo

### ISSUE THREAD

**Issue by riedgar-ms** [fairlearn/fairlearn#1134]
#### Describe the bug

Going to the 'main' branch of the documentation, the Fairlearn logo has a bad link

#### Steps/Code to Reproduce

![image](https://user-images.githubusercontent.com/28632930/195636473-39005a77-a097-4e49-804a-78fa9af81ed6.png)

This image has a link target of:

https://fairlearn.org/main/https%3A//fairlearn.org.html

**Comment by riedgar-ms** [comment]
I suspect that this is related to the logo link in `html_theme_options` in `conf.py` but I'm not sure _exactly_ what is happening.

**Comment by iofall** [comment]
I can help.

If you look at the code for [`navbar-logo.html` ](https://github.com/pydata/pydata-sphinx-theme/blob/v0.9.0/src/pydata_sphinx_theme/theme/pydata_sphinx_theme/components/navbar-logo.html) **v0.9.0**

```jinja
{% if not theme_logo.get("link") %}
  {% set href = pathto(root_doc) %}
{% elif theme_logo.get("link").startswith("http") %}
  {# Logo link is to external URL}
  {% set href = theme_logo.get("link") %}
{% else %}
  {# Logo link is to internal page #}
  {% set href = pathto(theme_logo.get("link")) %}
{% endif %}
```
The line `{# Logo link is to external URL}` is missing the ending `#` thus making it an invalid comment and we directly jump into the last case, which gives us the wrong URL.

They have fixed it in the latest version - https://github.com/pydata/pydata-sphinx-theme/pull/921

We can thus either **upgrade** to the latest version or just **override** the template with required fix.

**Comment by riedgar-ms** [comment]
I wouldn't object to updating to the latest version of the theme. @adrinjalali  do you have any concerns, since you were the last person tangling with the doc build?

**Comment by riedgar-ms** [comment]
Thanks for the detective work @iofall !

**Comment by adrinjalali** [comment]
It's complicated, we have been doing a branch per release. We can have a PR to that branch for the fix, but hopefully with the coming release it wouldn't be as urgent.

I don't mind having it fixed on that branch though. I just didn't want to push to all those branches.

**Comment by iofall** [comment]
Now that the release is done, we can fix this by:
1. Fixing it on main
2. And just updating the link manually on the docs repo for v8.0

What do you think?

**Comment by riedgar-ms** [comment]
I'd be happy to see this fixed on main. We could even cherry pick to the release branch

**Comment by iofall** [comment]
Ok great, working on it. 

But I don't think we need it on the release branch, right? 

The docs will now remain the same for v8.0, so I was thinking of making a one-off commit to just manually change the link there. Because even if we change it on the release branch, we will still have to manually trigger the doc build for v8.0 (as far as I know).

**Comment by adrinjalali** [comment]
Any commits to the release branch should automatically trigger a doc build and push.
