### ISSUE TITLE
[DOC] Bad 'source' links v0.8.0

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1150]
#### Describe the issue linked to the documentation

The "source" links in the API reference point to 404 because the `v` before the version is missing. E.g.,:

https://github.com/fairlearn/fairlearn/blob/0.8.0/fairlearn/datasets/_fetch_acs_income.py#L13-L211

instead of

https://github.com/fairlearn/fairlearn/blob/v0.8.0/fairlearn/datasets/_fetch_acs_income.py#L13-L211

I think this happens because we [used to get the `tag_or_branch` from sphinx multi version](https://github.com/fairlearn/fairlearn/blob/release/v0.7.0/docs/conf.py#L226) but in the current release `tag_or_branch ` is derived [from the fairlearn package version](https://github.com/fairlearn/fairlearn/blob/37e55bd9cdef858e4b62c379638c718b1e8c9b2b/docs/conf.py#L46).

#### Suggest a potential alternative/fix
It seems an easy fix would be to change [this line](https://github.com/fairlearn/fairlearn/blob/main/docs/conf.py#L231) in conf.py to include `v` before `{tag_or_branch}` in main and v0.8.0 - but I'm not sure if I understand our current sphinx setup well enough to understand if that would break other things in our doc build :D

**Comment by adrinjalali** [comment]
oh yeah, that's certainly the right direction.
