### ISSUE TITLE
Wording of Equal Opportunity

### ISSUE THREAD

**Issue by socallaghan** [fairlearn/fairlearn#1154]
Line 300 of the [Common Fairness Metrics](https://github.com/fairlearn/fairlearn/blame/main/docs/user_guide/assessment/common_fairness_metrics.rst
) text describes Equal Opportunity as: 
> For example, in the hiring example, equal opportunity requires that the individuals who are actually hired have an equal opportunity 
of being hired in the first place. 

The statement is a bit unclear. It relies on the term "equal opportunity" to explain what equal opportunity is. It also drops the concepts of groups, which the previous section on Equalised Odds was using throughout.

Maybe something like the following is clearer:
> In the hiring example, equal opportunity requires that the individuals in *group A* who are qualified to be hired are just as likely to be chosen as individuals in *group B* who are qualified to be hired.

**Comment by hildeweerts** [comment]
Many thanks for pointing this out @socallaghan and for suggesting an improvement! Would you like to create a PR to add your suggestion to the user guide?

**Comment by socallaghan** [comment]
Sure. I can give it a go.

**Comment by romanlutz** [comment]
@socallaghan let us know if anything is unclear. The website infrastructure has a bit of a steep learning curve if you're not used to sphinx/ReST, but we're always happy to help point you in the right direction.

**Comment by socallaghan** [comment]
Sorry for the long delay on this. It slipped through the cracks. But I've submitted a PR now.

**Comment by hildeweerts** [comment]
Fixed by #1195
