### ISSUE TITLE
[CI] TclError

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1156]
In #1152, windows build 3.9 [failed](https://github.com/fairlearn/fairlearn/actions/runs/3525473951/jobs/5927445026) on a `TclError`  in `test_plot_equalized_odds_ex3` saying "This probably means that Tcl wasn't installed properly.". 

It doesn't look like it should be related to that PR so I did some digging. It seems to be a more common problem and [this issue](https://github.com/microsoft/azure-pipelines-tasks/issues/16426) provides some pointers to fix it, including "setting the `matplotlib` backend prior" and "selecting a non-interactive backend".

Tagging @adrinjalali @riedgar-ms

**Comment by adrinjalali** [comment]
Yep, I think using `agg` backend should fix it.
