### ISSUE TITLE
[CI] Codecov upload failures

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1161]
We sometimes get codecov upload failures that forces us to rerun the CI.

There are a few suggestions in [this issue](https://github.com/codecov/codecov-action/issues/598) we can explore.

**Comment by adrinjalali** [comment]
I've seen this for a while, and the only solution I've had has been "rerun the workflow" 😁

**Comment by romanlutz** [comment]
The main takeaway I see from the issue you linked @hildeweerts was that it might help to add the token, but the [official docs](https://github.com/codecov/codecov-action#usage) say it's not needed for public repos.

There are GitHub Actions that do retry-on-fail, but you can only wrap a command that way, not another action. At least that's how I understand it.

**Comment by hildeweerts** [comment]
Hmm... seems then there's no other option than just rerunning the workflow manually. I'll close this issue then.
