### ISSUE TITLE
[CI] PyTorch error

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1162]
In [this run](https://github.com/fairlearn/fairlearn/actions/runs/3573431020/jobs/6007487149) the PyTorch tests fail due to a `RuntimeError`.

```
>       return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
E       RuntimeError: all elements of input should be between 0 and 1
```

**Comment by riedgar-ms** [comment]
@SeanMcCarren this is happening in your Adversarial test.... any idea what's going on?
