### ISSUE TITLE
DOC Postprocessing API docs styling + content improvements

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#1164]
#### Describe the issue linked to the documentation

https://fairlearn.org/main/api_reference/fairlearn.postprocessing.html

This is what it looks like right now:
![image](https://user-images.githubusercontent.com/10245648/210035716-e1b9f44c-efc6-4b45-951e-2c49e540950a.png)

#### Suggest a potential alternative/fix

In the `predict_proba` bullet point the `predict_proba` written in italics should actually be in a `:code:` block instead. Same for `decision_function` in italics in the next bullet, as well as `predict` in the last one.

Also, the "new in version 0.7" box could be improved to say what the new behavior is. I think adding a sentence at the end saying "Now you can specify which method to use as documented above." might make sense.

**Comment by Nobody4591** [comment]
Hi, Can i start working on this?

**Comment by romanlutz** [comment]
Absolutely! Please don't hesitate to reach out if you have questions or don't know where to start.

**Comment by Nobody4591** [comment]
Thank you. I'll ping you for sure if there's anything

**Comment by Nobody4591** [comment]
Hi @romanlutz. I have made some progress regrading this issue which I wanna share with you.

Following your suggestion "In the predict_proba bullet point the predict_proba written in italics should actually be in a :code: block instead". I try to implement this but it show some weird results. 

![Annotation 2023-01-12 103048](https://user-images.githubusercontent.com/69182153/211985269-ce0e1cea-f28d-4ff4-b85f-ea7c8ec8bd45.png)
I don't know either it's my incompetency as I'm noob or something else. But it show some discontinuity. Than I came up with another idea.

![Annotation 2023-01-12 103301](https://user-images.githubusercontent.com/69182153/211985498-604c8d5b-a178-4374-817d-cd4bf7e13efd.png)

I think, it preserves same structure like Objective and constraints but you know well. I just wanna know your thoughts or suggestions on this. 
Thanks!

**Comment by romanlutz** [comment]
@Nobody4591 very interesting! First of all, please know that ReST can be quite finicky and it takes practically everyone several attempts to get some of these things right. I see what you mean by discontinuity. Do you mind posting the change you made to render this result? You can post it as a (draft) PR if you like, or if it's just a few lines you can post it here, too.

**Comment by Nobody4591** [comment]
Sure. Just give me couple of minutes. BTW, thanks for so quick response :)

**Comment by romanlutz** [comment]
Thanks @Nobody4591 for fixing this! The page is live at https://fairlearn.org/main/api_reference/fairlearn.postprocessing.html
