### ISSUE TITLE
BUG OpenML version of adult does not work with pandas parser

### ISSUE THREAD

**Issue by MiroDudik** [fairlearn/fairlearn#1168]
#### Describe the bug
Scikit-learn 1.2 introduced a faster parser for OpenML files, but that parser leads to an incorrectly parsed adult dataset, so we need to continue using the slow parser. (See #1166.)

#### Steps/Code to Reproduce
```pycon
>>> import sklearn.datasets as skd
>>> d = skd.fetch_openml(data_id=1590, as_frame=True, parser='pandas')
>>> d.target
0         <=50K
1         <=50K
2          >50K
3          >50K
4         <=50K
          ...  
48837     <=50K
48838      >50K
48839     <=50K
48840     <=50K
48841      >50K
Name: class, Length: 48842, dtype: category
Categories (2, object): [' <=50K', ' >50K']
```
In the last line you see that there's an extra space in how the categorical variables are parsed. This is because the source CSV file has spaces after commas.

The proposed fix is to upload the version of adult without those spaces, and then we can replace the slow parser with the faster 'pandas' parser.

**Comment by glemaitre** [comment]
Note that we should fix the issue here: https://github.com/scikit-learn/scikit-learn/pull/25312
It should be released in 1.2.1 in the upcoming weeks.

I still foresee an inconsistency between the metadata of the ARFF file and the data read with the ARFF parser or pandas parser. It might not be an issue if you don't care about the raw data.

**Comment by MiroDudik** [comment]
Fantastic. Thanks!

**Comment by hildeweerts** [comment]
@MiroDudik did you verify whether this is still an issue with the new release of scikit-learn?

**Comment by hildeweerts** [comment]
@MiroDudik any update on this?

**Comment by hildeweerts** [comment]
see above @MiroDudik :D

**Comment by MiroDudik** [comment]
We need to bump our requirement to `sklearn >= 1.2.1`, see #1287 (which re-introduces this bug).
