### ISSUE TITLE
DOC remove the last .ipynb notebook

### ISSUE THREAD

**Issue by MiroDudik** [fairlearn/fairlearn#1175]
Is it time to remove the very last .ipynb notebook from our repository?
https://github.com/fairlearn/fairlearn/blob/main/notebooks/Grid%20Search%20for%20Binary%20Classification.ipynb

Or do we believe it serves some educational value that would be lost?

**Comment by MiroDudik** [comment]
@romanlutz @riedgar-ms @hildeweerts

**Comment by hildeweerts** [comment]
Sounds good!

**Comment by romanlutz** [comment]
@riedgar-ms authored it and should definitely add his thoughts. I'm certainly not attached to it 😄

**Comment by riedgar-ms** [comment]
I'm not attached to it.

**Comment by MiroDudik** [comment]
Ok! It shall live forever in our history (and our hearts).
