### ISSUE TITLE
DOC Replace adult/census dataset in "Get Started"

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#1182]
#### Describe the issue linked to the documentation

We're currently using the adult/census dataset in "Get Started" on the website. As we have agreed on many occasions it's not a particularly good example of a useful application context. This should be replaced with a different dataset.

#### Suggest a potential alternative/fix

Some alternatives that @MiroDudik proposed recently (on the community call and #1177 ):
- the diabetes dataset from https://github.com/fairlearn/talks/tree/main/2021_scipy_tutorial (I think it's now part of fairlearn.datasets, but for the tutorial they added something synthetic) - it needs a lot of context to be explained which makes it less suitable for a quickstart where we can't spend much time (I think the page says 10 minutes), BUT we could just point to the tutorial for a holistic view.
- generate something entirely synthetic with a fairly obvious context. @MiroDudik's idea was this: rolling out a new version of a website happens slowly to avoid having everyone experience downtime if something goes wrong. So a model can select who sees the new version (1) or the old version (0) and we have some characteristics like perhaps location (country?) or browser or such and want to achieve equal risk distribution across groups (risk of having a bad QoS). Thinking about this a bit more, I'm wondering what features the original model without mitigation would use to make its prediction.

**Comment by MiroDudik** [comment]
Some clarifications re scipy tutorial dataset:
* We didn't need to add anything synthetic
* I also don't think that the context would take too long to explain--I think that we could describe things in a paragraph--building on what's already in [scipy tutorial](https://github.com/fairlearn/talks/blob/main/2021_scipy_tutorial/fairness-in-AI-systems-instructors.ipynb), specifically sections: **Dataset and task** and **Measuring fairness-related harms** (just the sentences related to health care scenario).
* As Roman says, we would point to the tutorial for more context / definitions
* One downside with this dataset is that the disparity is between the race group labeled *Unknown* and the other groups; this is a statistically significant disparity, but not something that is brought up in the literature

All of that said, I would be in favor of using that dataset over what we have right now. (Synthetic datasets are a can of worms that would just block this issue...).

**Comment by shimst3r** [comment]
I wouldn’t mind taking care of either. 🤓

**Comment by romanlutz** [comment]
@shimst3r it looks like #1185 is sort of a prerequisite for #1182 and would have to be done first.

Thanks @MiroDudik for the clarifications 🙂

**Comment by shimst3r** [comment]
@romanlutz ah, yes. Then I'll start with #1185 👍

**Comment by alliesaizan** [comment]
Hi there, I am looking through the open documentation issues and it looks like since #1185 has been closed work can start on this one if it hasn't already, but please correct me if I am missing something! @shimst3r would you be interested in picking this back up?

**Comment by shimst3r** [comment]
Thanks for asking @alliesaizan. I'm a bit out of the loop at the moment, so I wouldn't mind if someone else picks this up. :relieved:

**Comment by alliesaizan** [comment]
> Thanks for asking @alliesaizan. I'm a bit out of the loop at the moment, so I wouldn't mind if someone else picks this up. 😌

No problem! I will let this sit for a bit in case others from the community want to give it a shot, and if there are no takers I will open up a PR to address this :)

**Comment by alliesaizan** [comment]
Hi all, it's been a few weeks so I will work on this one this week and will plan to get a PR submitted by the weekend.

**Comment by alliesaizan** [comment]
Hi @romanlutz and @MiroDudik, I am working on this and it appears that the variable used in the tutorial, "<30 days readmit", suffers from a label imbalance problem. In the scipy tutorial, the authors resample the data; I am guessing we do not want to do this for Getting Started, but as I am seeing odd results that I think are related to the label imbalance (perfect accuracy on a basic decision tree classifier), I am wondering if you have any advice.

**Comment by romanlutz** [comment]
I had the same issue in my post processing docs PR! You can take a look... essentially, I'm removing the 3 rows that are not from male/female because it's too small of a group to be representative. Not great but we can point that out as something that needs to be addressed!

Also, I used balanced accuracy score. Wdyt?

**Comment by alliesaizan** [comment]
Yeah, balanced accuracy score is also what the tutorial used, so I agree we should proceed with that! Thanks, I will take a look at the PR.

**Comment by alliesaizan** [comment]
Closing as PR #1310 addresses this.
