### ISSUE TITLE
MNT remove customplots extra

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#1186]
We have an extra called "customplots" that installs `matplotlib`. The idea behind it was to not force people to install `matplotlib` if they don't want to. For example, if you're running Fairlearn in the cloud as part of a remote job you may not need to render any plots. Additionally, `matplotlib` is occasionally difficult to install which we've sometimes observed on MacOS.

In the meantime, other packages have the same optional relationship with Fairlearn, e.g., pytorch, which is needed for some mitigation technique(s) but not generally required to run Fairlearn. We don't have extras for pytorch, though.

I raised the idea of potentially removing the "customplots" extra in a recent (unrelated) PR, but wanted to set this up as a separate task. The alternative would be to have more extras for things like pytorch, of course. That seems like a tricky undertaking, though, and would increase our test matrix considerably.

1st note: We have a build/test pipeline for `minimal-deps` that tests Fairlearn without extras. ~~Do we still need it if we remove all extras?~~ [Update: yes we do need the minimal deps pipeline, see discussion below.]
2nd note: Should we update documentation to mention that matplotlib needs to be installed for some functionality? @shimst3r ran into this recently in the "Get started" page.

FYI @fairlearn/fairlearn-maintainers

**Comment by MiroDudik** [comment]
i think we should keep minimal-deps or something like that to test our warning paths, e.g., when matlab is not installed? or there might be some other way how to use pytest to test these paths?

**Comment by romanlutz** [comment]
Yeah you're right, we still have those cases where matplotlib (not matlab 🤣 ) isn't installed (or pytorch or whatever else we might have as optional dependencies in the future), so the minimal version tests should remain.

**Comment by adrinjalali** [comment]
I don't mind removing the `customplots` extra, but we need to improve our installation page, and be clear about what functionality requires what dependency, and have something which people can copy/paste to install all dependencies.

**Comment by romanlutz** [comment]
Our "get started" page does a decent job with 
```
pip install fairlearn matplotlib
```
and the code tells you if you don't have matplotlib installed for something that needs it so I guess I'm not super worried? If you'd like to open an issue to improve the docs on this please go ahead. It's related but not exactly this issue (which has been addressed) so I'm closing this one. I'm just not entirely sure how you want it represented in our docs so the new issue should capture that (if indeed you feel like it needs clarification).
