### ISSUE TITLE
MNT remove _group_metric_set and affiliate baggage

### ISSUE THREAD

**Issue by MiroDudik** [fairlearn/fairlearn#1187]
This is a ghost of the versions past:
https://github.com/fairlearn/fairlearn/blob/main/fairlearn/metrics/_group_metric_set.py
(and it has some ghostly baggage scattered around our repo).

We kept it as a courtesy when we split off the dashboard to [responsible AI toolbox](https://github.com/microsoft/responsible-ai-toolbox), but that's been more than two years ago and we're still maintaining it; it would be nice to stop at some point.

@romanlutz ?

**Comment by romanlutz** [comment]
@riedgar-ms created this and at some point considered removing it. Was there anything holding you back?

**Comment by riedgar-ms** [comment]
My only concern would be if it needs to be moved to AzureML. Of course, removing it here might help that process along....

**Comment by MiroDudik** [comment]
the two of you are the main ones that would know if there's an existing outside dependency on this. so if you are okay, then i say let's remove it...
