### ISSUE TITLE
DOC Fix doc build of plot_quickstart.py so filename.png is not saved

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1192]
#### Describe the issue linked to the documentation
`filename.png` gets generated every time we run `plot_quickstart.py`. On the last line we save a figure which leads to the file being saved in the `examples` directory. In #1179 this was fixed by adding `filename.png` to .gitignore. As suggested by @adrinjalali a nicer fix would have been to ensure the file is not saved in the first place.

#### Suggest a potential alternative/fix

- Make sure `filename.png`  is not saved in the `examples` directory after running `plot_quickstart.py`
- Remove `filename.png` from gitignore.

**Comment by iofall** [comment]
https://github.com/fairlearn/fairlearn/blob/659ee3ae7d8c02df6f22f7f9990b80bd651c6c4c/examples/plot_quickstart.py#L94

The easiest fix we can do is to just comment out the part where the figure is being saved. That way readers can still see how to save a figure without the line getting executed.

**Comment by adrinjalali** [comment]
We can also do a `if "__file__" in locals():` check, and I think when sphinx runs the script that condition is not true. Example: https://skops.readthedocs.io/en/stable/auto_examples/plot_hf_hub.html#sphx-glr-auto-examples-plot-hf-hub-py

**Comment by iofall** [comment]
> We can also do a `if "__file__" in locals():` check, and I think when sphinx runs the script that condition is not true. Example: https://skops.readthedocs.io/en/stable/auto_examples/plot_hf_hub.html#sphx-glr-auto-examples-plot-hf-hub-py

So we could do something like this, right? -
```python
# don't save file during doc build
if "__file__" in locals():
    fig[0][0].figure.savefig("filename.png")
```
