### ISSUE TITLE
DOC Fix links in Further Resources (Papers) of User Guide

### ISSUE THREAD

**Issue by AndresAlgaba** [fairlearn/fairlearn#1197]
#### Describe the issue linked to the documentation
I was browsing through the Further Resources section in the User Guide and found that the links to:

- [Algorithmic Fairness from a Non-ideal Perspective](http://zacklipton.com/media/papers/fairness-non-ideal-fazelpour-lipton-2020.pdf) (Fazelpour & Lipton, 2020) is broken,

- [Measures and Mismeasures of Fairness](https://5harad.com/papers/fair-ml.pdf) (Corbett-Davies & Goel, 2018) refers to a newer version of this paper with additional authors.

#### Suggest a potential alternative/fix

- Replace the link with the arXiv version: https://arxiv.org/abs/2001.09773, or the open-access published version: https://dl.acm.org/doi/10.1145/3375627.3375828.

- Update the authors (add: Nilforoshan and Shroff) and year (2018 -> 2022) or refer to the old version on arXiv: https://arxiv.org/abs/1808.00023.

**Comment by romanlutz** [comment]
Excellent points! Perhaps we should make a general pass over all references and ensure they link to websites that don't suddenly change links or the contents. 

I don't think it matters which version we link to, other than that the authors should match the version that we're linking to (as you wrote).

@AndresAlgaba , you don't want to make those changes yourself by any chance? No pressure, just wondering. Thanks for finding and reporting the problem!

**Comment by AndresAlgaba** [comment]
Sure! I would love to contribute and open a PR :). Do you mean a manual pass over all references or have some automated testing at regular intervals?

**Comment by romanlutz** [comment]
Oh I just meant for fixing this particular one. If you want to make a pass over all of them it's probably best to convert them as described in #1069, but even just the single fix is great.

**Comment by romanlutz** [comment]
Having a full list with author names etc is not a bad idea. We have that in many pages,e.g., at the the bottom of https://fairlearn.org/v0.8/user_guide/fairness_in_machine_learning.html#footcite-umojanoble2018algorithmsoppression

So I'm all for it.

**Comment by AndresAlgaba** [comment]
Cool! I'll open a PR :)
