### ISSUE TITLE
How to use fairlearn directly for mitigating bias in multiclass classification problems?

### ISSUE THREAD

**Issue by pradeepdev-1995** [fairlearn/fairlearn#1201]
How to use fairlearn directly for mitigating bias in multiclass classification problems?

**Comment by pradeepdev-1995** [comment]
@romanlutz any updates on this?

**Comment by romanlutz** [comment]
@pradeepdev-1995 This is answered on our [FAQ page](https://fairlearn.org/main/faq.html) under "Does Fairlearn support multiclass classification?"

**Comment by pradeepdev-1995** [comment]
@romanlutz 
In this section - https://fairlearn.org/main/user_guide/mitigation/reductions.html#fairness-constraints-for-multiclass-classification
I could see that 
```Fairness constraints for multiclass classification
Reductions approaches do not support multiclass classification yet at this point. If this is an important scenario for you please let us know!```
Which means the fairlearn doesnt support multiclass classification fairness mitigation now?

and in the FAQ, it state like this

```On the mitigation side, our algorithms [reductions.ExponentiatedGradient](https://fairlearn.org/main/api_reference/generated/fairlearn.reductions.ExponentiatedGradient.html#fairlearn.reductions.ExponentiatedGradient) and [reductions.GridSearch](https://fairlearn.org/main/api_reference/generated/fairlearn.reductions.GridSearch.html#fairlearn.reductions.GridSearch) support [bounded group loss](https://fairlearn.org/main/user_guide/mitigation/reductions.html#bounded-group-loss) constraints, which are applicable to any supervised learning setting, including multiclass classification.```

It seems contradictory to me.

So does fairlearn can able to  mitigate bias in multiclass classification problems?

**Comment by hildeweerts** [comment]
Hi, @pradeepdev-1995. Many thanks for pointing out the inconsistency! Bounded group loss is primarily designed for the regression scenario (see [this paper](https://proceedings.mlr.press/v97/agarwal19d.html) for more information). Do note this corresponds to a very specific notion of fairness (it constraints the worst-case loss across groups) which may not be applicable to your use case.

@MiroDudik could you confirm whether/how bounded group loss can be used in the multiclass classification scenario? If so, we should add an example to our user guide.

**Comment by pradeepdev-1995** [comment]
@hildeweerts Thanks for the response. I am looking  for an update on this from @MiroDudik

**Comment by pradeepdev-1995** [comment]
Also tried multiclassification fairness use cases with ```ThresholdOptimizer```.  Called the ```fit``` function by
```threshold_optimizer.fit(X_train, y_train, sensitive_features=A_train)```
where ```y_train``` is the multiclass label - [0,1,2,3] . 

But it shows the error
```ValueError: Supplied y labels are not 0 or 1```

**Comment by hildeweerts** [comment]
Hi, @pradeepdev-1995. 
* `ThresholdOptimizer` is for sure only implemented for the binary classification scenario. 
* `CorrelationRemover` is a pre-processing algorithm that only considers input features, so it can also be applied in the multiclass scenario.
* I believe `AdversarialFairnessClassifier` does support multiclass classification, let me know if this works.

**Comment by pradeepdev-1995** [comment]
@hildeweerts 
checked with ```AdversarialFairnessClassifier``` as in sklearn model case

```
pipeline = Pipeline(
        [
            ("preprocessor", ct),
            (
                "classifier",
                AdversarialFairnessClassifier(
                    backend="torch",
                    predictor_model=[50, "leaky_relu"],
                    adversary_model=[3, "leaky_relu"],
                    batch_size=2 ** 8,
                    random_state=123,
                ),
            ),
        ]
    )
pipeline.fit(X_train, Y_train, classifier__sensitive_features=Z_train)
```
where y_train is the multiclass label - [0,1,2,3] .

But both shows the error
```RuntimeError: 0D or 1D target tensor expected, multi-target not supported```

**Comment by hildeweerts** [comment]
This error leads me to believe you might be asking for multioutput rather than multiclass classification? Could you show me what your Y_train looks like exactly? Is it a single array (e.g. [1, 2, 0, 3, ..., 2]) or a multidimensional array?

**Comment by pradeepdev-1995** [comment]
@hildeweerts 
I am calling fit function in this way
```pipeline.fit(X_train, y_train.values, classifier__sensitive_features=A_train)```
where ```y_train.values``` shows such as ```array([2, 0, 0, ..., 2, 0, 3], dtype=int8)```  and it shows error ```RuntimeError: 0D or 1D target tensor expected, multi-target not supported```

**Comment by hildeweerts** [comment]
Could you please provide a minimal example that I can use to reproduce your error? @pradeepdev-1995

**Comment by pradeepdev-1995** [comment]
@hildeweerts 
Here is the code throws the error ```RuntimeError: 0D or 1D target tensor expected, multi-target not supported```

```
import pandas as pd
from sklearn.model_selection import train_test_split
from fairlearn.adversarial import AdversarialFairnessClassifier
d = {
     'col1': [1,2,3,4,5,6,7,8],
     'sex': [1,1,0,0,1,0,1,1],
     'col2': [11, 12,13,14,11, 12,13,14],
     'Target':[0,1,2,3,2,1,3,0]
     }
df = pd.DataFrame(data=d)

X = df[['col1','sex','col2']]
y = df[['Target']]
z = df["sex"] # In this example, we consider 'sex' the sensitive feature.

X_train, X_test, Y_train, Y_test, Z_train, Z_test = train_test_split(
    X, y, z, test_size=0.1
)

mitigator = AdversarialFairnessClassifier(
    backend="torch",
    predictor_model=[50, "leaky_relu"],
    adversary_model=[3, "leaky_relu"],
    batch_size=2 ** 8,
    progress_updates=0.5,
    random_state=123,
)
mitigator.fit(X_train, Y_train, sensitive_features=Z_train)
```
The same code works fine if I changed the Target column to binary values ``` 'Target':[0,1,1,0,0,1,2,0]```

**Comment by pradeepdev-1995** [comment]
@hildeweerts  @MiroDudik  Any updates on this?

**Comment by romanlutz** [comment]
@pradeepdev-1995 Please rest assured that we read all the messages here. There are no response time SLAs since this is an open source project to which we all volunteer our time. Sometimes it takes a few days to find the time to respond. If you don't hear back within 7 days you can always feel free to respond on the issue. For more of a real-time-style chat I suggest you join our Discord and start a thread there (although that doesn't necessarily guarantee faster responses either, it's just a different format).

**Comment by SeanMcCarren** [comment]
@pradeepdev-1995 AdversarialFairness is definitely applicable, but in this case it doesn't work because of an error in our code. Nice catch! It turns out `torch.nn.NLLLoss` expects single-column categorical, but we preprocess `y` to a one-hot-encoding. I will work on fixing this.

For now, if you just want to play with AdversarialFairness I suggest two options: just to switch the backend to tensorflow, it works there. So pass `backend="tensorflow"`. 

Alternatively, but I don't really recommend it, you could take a look at our internal base class (hidden in the public API) `_AdversarialFairness` at `fairlearn.adversarial._adversarial_mitigation`, which allows you to pass your own loss function. I think something like this should work:
```
from fairlearn.adversarial._adversarial_mitigation import _AdversarialFairness
import torch

mitigator = _AdversarialFairness(
   predictor_model = # I think you need to make your own model now
   predictor_loss = torch.nn.CrossEntropyLoss
)
```

**Comment by pradeepdev-1995** [comment]
@SeanMcCarren Thanks for the clarification.  ```backend="tensorflow"``` worked for me. But I confused if I put  backend as TensorFlow then how can I fine-tune the model? The below code is present in the fine-tuning section of ```https://fairlearn.org/main/user_guide/mitigation/adversarial.html```  , seems ```torch``` based. 

```
import torch

class PredictorModel(torch.nn.Module):
    def __init__(self):
        super(PredictorModel, self).__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(X_prep_train.shape[1], 200),
            torch.nn.LeakyReLU(),
            torch.nn.Linear(200, 1),
            torch.nn.Sigmoid(),
        )

    def forward(self, x):
        return self.layers(x)


predictor_model = PredictorModel()
```
So what is the corresponding Tensorflow based code?

**Comment by pradeepdev-1995** [comment]
Also If I have two positive labels(since it is multi classification) how can I pass those in ```pos_label```. In documentation it seems that pos_label is a scalar value.

**Comment by SeanMcCarren** [comment]
> Shall use the same code for tensorflow backend also? else what is the corresponding Tensorflow based code?

Indeed you now need a tf model. I won't spoil the fun for you of exploring it yourself.



> Also If I have two positive labels(since it is multi classification) how can I pass those in `pos_label`. In documentation it seems that pos_label is a scalar value.

Positive label only makes sense in binary classification. What do your target features mean here?

**Comment by pradeepdev-1995** [comment]
@SeanMcCarren  Okay so let me run it without passing the ```pos_label``` argument.

**Comment by pradeepdev-1995** [comment]
@SeanMcCarren  facing two issues

1 - What is  ```selection_rate==0``` means, the model is fair enough?
2 - Without AdversarialFairnessClassifier , using a simple SVM classifier I got ```selection_rate==0```. But after AdversarialFairnessClassifier mitigation, the ```selection_rate``` value increased.  What does this mean?

**Comment by hildeweerts** [comment]
Hi, @pradeepdev-1995. It is a bit unclear what `selection_rate` you're referring to. The selection rate usually refers to the proportion of positive predictions. When you consider `fairlearn.metrics.selection_rate(y_true,y_pred,*,pos-label=1)`, you calculate the fraction of predicted labels that match `pos_label`. In the user guide for adversarial mitigation, there is one example where `selection_rate` is computed as the average prediction. This makes sense in the context of binary classification where `pos_label=1`, as in that case the average prediction is equivalent to the proportion of positives. In the multiclass classification scenario, `selection_rate` is less sensible. In particular, computing the average predicted value usually does not really mean anything.

**Comment by pradeepdev-1995** [comment]
@MiroDudik 
CorrelationRemover worked for me.
But ```ExponentiatedGradient``` as I already mentioned above in this thread, shows error - ```ValueError: Supplied y labels are not 0 or 1```.
Code tried
```
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from fairlearn.reductions import ExponentiatedGradient, DemographicParity
data = {
     'col1': [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18],
     'sex': [0,0,1,0,0,1,1,1,1,1,0,1,0,1,1,0,1,1],
     'col2': [19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36],
     'y_true':[0, 1, 2, 3, 1, 2, 1, 3, 2, 0, 0, 3, 1, 0, 2, 3, 1, 2]
     }
df = pd.DataFrame(data=data)

X = df[['col1','sex','col2']]
y_true = df[['y_true']]

sf_data = df["sex"]

np.random.seed(0)

classifier = GradientBoostingClassifier()
constraint = DemographicParity()
mitigator = ExponentiatedGradient(classifier, constraint)
mitigator.fit(X, y_true, sensitive_features=sf_data)
y_pred_mitigated = mitigator.predict(X)  
```

**Comment by pradeepdev-1995** [comment]
EDIT:
I changed DemographicParity with ``` BoundedGroupLoss``` and ```ZeroOneLoss``` like below
```
from fairlearn.reductions import ExponentiatedGradient,GridSearch, BoundedGroupLoss,ZeroOneLoss
from sklearn.metrics import accuracy_score,precision_score,recall_score
constraint = BoundedGroupLoss(ZeroOneLoss(), upper_bound=0.6)
classifier = GradientBoostingClassifier()
mitigator = ExponentiatedGradient(classifier, constraint)
mitigator.fit(X, y_true, sensitive_features=sf_data)
y_pred_mitigated = mitigator.predict(X)

sr_mitigated = MetricFrame(metrics={"conf_mat": conf_mat, "recall": recall},
                           y_true=y_true,
                           y_pred=y_pred_mitigated, 
                           sensitive_features=sf_data)
print(sr_mitigated.by_group)
```

But I observe that the recall scores of each sensitive variable is not changing towards closely. 
Before mitigation it was  
```
sex: 0 = recall: 0.712 
sex: 1 = reacall: 0.589
```
After mitigation it is  
```
sex: 0 = recall: 0.234
sex: 1 = reacall: 0.889
```

why it is more deviating after mitigation?
