### ISSUE TITLE
DOC dataset fetch_* function return types unclear

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#1205]
#### Describe the issue linked to the documentation

Example:
![image](https://user-images.githubusercontent.com/10245648/217054435-04516c2d-0ba9-4e53-a71b-c6092ba2534b.png)

I'm confused. What happens if `return_X_y=False`? It's not mentioned. I happen to know the implementation, but other readers may not, so this needs clarifying.

This applies to basically every function in the `fairlearn.datasets` module AFAIK.

#### Suggest a potential alternative/fix

After reading this I'm thinking there are a few cases:
- `return_X_y=True` and `as_frame=False` gets me `(data, target)` with ndarrays
- `return_X_y=True` and `as_frame=True` gets me `(data, target)` with pandas.DataFrame and Series
- `return_X_y=False` is not mentioned. Should it be mentioned in the first case (`dataset`)?

nit: I would also like there to be a colon instead of full stop in the first line after "attributes."

**Comment by MiroDudik** [comment]
I think that much of it originates with https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_openml.html

I think that it is confusing to have three cases. The two `return_X_y=True` cases should be merged and the logic of the return types just described (the same as we do with `data` and `target` fields under the `Bunch`).

Also, I think that we don't need to mention `return_X_y=False` under the `Bunch`--this is the default behavior.

**Comment by hildeweerts** [comment]
Closed by #1216
