### ISSUE TITLE
ValueError: If pos_label is not specified, values must be from {0, 1} or {-1, 1}

### ISSUE THREAD

**Issue by pradeepdev-1995** [fairlearn/fairlearn#1212]
Tried the below code for finding the **equalized_odds_difference** in a multiclass scenario. 

```
y_true = [0, 1, 2, 3, 1, 2, 1, 3, 2, 0, 0, 3, 1, 1, 2, 3, 1, 2]
y_pred = [1, 3, 1, 3, 2, 2, 3, 0, 0, 2, 1, 1, 2, 0, 3, 1, 2, 2]
sf_data = ['b', 'b', 'a', 'b', 'b', 'a', 'a', 'a', 'a','a', 'b', 'a', 'b', 'b', 'a', 'b', 'a', 'a']
from fairlearn.metrics import equalized_odds_difference
equalized_odd_dif = equalized_odds_difference(y_true,y_pred,sensitive_features=sf_data)
print("\nEqualized odds difference = ", equalized_odd_dif)
```
But it shows the error like this
```ValueError: If pos_label is not specified, values must be from {0, 1} or {-1, 1}```

**Comment by hildeweerts** [comment]
Hi, @pradeepdev-1995. Please note that equalized odds requires false positive rates and false negative rates to be equal across groups. As FPR and FNR are only defined in the binary classification scenario, this error is to be expected in the multiclass scenario. I would recommend checking out [`make_derived_metric`](https://fairlearn.org/v0.8/api_reference/fairlearn.metrics.html#fairlearn.metrics.make_derived_metric) to create a fairness metric tailored for your use case.

**Comment by pradeepdev-1995** [comment]
@hildeweerts Thanks for the reply. Is there any example of creating equalized_odds_difference metric using  **make_derived_metric** for multiclass classification? Please provide the code snippet.

**Comment by pradeepdev-1995** [comment]
@hildeweerts 
But in this (https://fairlearn.org/main/user_guide/mitigation/reductions.html#fairness-constraints-for-multiclass-classification)  documentation I can see that
```
Reductions approaches do not support multiclass classification yet at this point. If this is an important scenario for you please let us know!
```
So still how  a derived our own metric will help here?
Or
Please share the challenge you are facing while developing/enhancing fairlearn to  a multiclass classificaiton fairness support?
All the fairness tools i could see around web only support binary classification or regression. What are the reasons behind this?

**Comment by hildeweerts** [comment]
The derived metric can be used for measurement, not mitigation.

So far we have not seen a great demand for multiclass classification. We might consider adding functionality to support this in the future, but as with most OS projects, we only have limited capacity and this is currently not part of our roadmap. I expect most libraries do not support the multiclass scenario because the research literature has focused primarily on the binary classification scenario.
