### ISSUE TITLE
ValueError: Supplied y labels are not 0 or 1

### ISSUE THREAD

**Issue by pradeepdev-1995** [fairlearn/fairlearn#1213]
Tried the following code for demographic parity reduction in multiclass classification
```
data = {
     'col1': [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18],
     'sex': [0,0,1,0,0,1,1,1,1,1,0,1,0,1,1,0,1,1],
     'col2': [19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36],
     'y_true':[0, 1, 2, 3, 1, 2, 1, 3, 2, 0, 0, 3, 1, 0, 2, 3, 1, 2]
     }
df = pd.DataFrame(data=data)
X = df[['col1','sex','col2']]
y_true = df[['y_true']]
sf_data = df["sex"]
from fairlearn.reductions import DemographicParity
dp = DemographicParity(difference_bound=0.01)
dp.load_data(X, y_true, sensitive_features=sf_data)
print(dp.gamma(lambda X: y_pred))
```
But it shows error such as ```ValueError: Supplied y labels are not 0 or 1```
So how to apply demographic parity reduction in multiclass classification?

**Comment by hildeweerts** [comment]
Hi, @pradeepdev-1995. Similar to #1212, demographic parity is not defined for the multiclass classification scenario. As per my comment in #1212 I would highly recommend you to check out our user guide on performing fairness assessments.
