### ISSUE TITLE
Link Broken 

### ISSUE THREAD

**Issue by eskayML** [fairlearn/fairlearn#1224]
Algorithms link broken under **Fairlearn algorithms** in main readME 

https://fairlearn.org/main/user_guide/mitigation.html

**Comment by romanlutz** [comment]
I think it should point to https://fairlearn.org/main/user_guide/mitigation/index.html

Feel free to submit a PR @eskayML 🙂  Thank you!

**Comment by hildeweerts** [comment]
Closed by #1225
