### ISSUE TITLE
DOC: Fairness metric documentations (typo)

### ISSUE THREAD

**Issue by Tizpaz** [fairlearn/fairlearn#1230]
#### Describe the issue linked to the documentation
In the documentation for the fairness metric API (https://fairlearn.org/v0.4.6/api_reference/fairlearn.metrics.html), there is a typo in the group_max_from_summary: the description should be :"Retrieve the maximum group-level metric value from group summary" rather than minimum.  

#### Suggest a potential alternative/fix
The fix is very simple: just replace the minimum with maximum.

**Comment by adrinjalali** [comment]
Thanks for the report. But that's a very old release and not supported anymore.
