### ISSUE TITLE
DOC Improve metrics documentation

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1231]
#### Describe the issue linked to the documentation

Our documentation currently does not clearly indicate the two main types of fairness assessments in Fairlearn (i.e. `MetricFrame` versus fairness metrics such as `equalized_odds_difference`), which can lead to confusion (see e.g., #1222).

#### Suggest a potential alternative/fix

Some places where we could possibly mention this more explicitly:
* https://fairlearn.org/main/api_reference/index.html#module-fairlearn.metrics
* https://fairlearn.org/main/user_guide/assessment/index.html
* https://fairlearn.org/main/user_guide/assessment/perform_fairness_assessment.html

**Comment by hildeweerts** [comment]
Also related to #1095

**Comment by alliesaizan** [comment]
Assigning myself to this one - I think it makes most sense to either add this information to _Assessment_ or _Performing a Fairness Assessment_. If someone from the community wants to help out, I will offer assistance :). If no one picks it up in a reasonable amount of time, I will propose a path forward and implement it myself.

**Comment by romanlutz** [comment]
It may not be mutually exclusive... clearly, this is a point that confuses people so mentioning it multiple times may be a good thing.

**Comment by alliesaizan** [comment]
> It may not be mutually exclusive... clearly, this is a point that confuses people so mentioning it multiple times may be a good thing.

Agreed, I will mock up a version where this is mentioned in both sections.

**Comment by alliesaizan** [comment]
Resolved by #1284.
