### ISSUE TITLE
DOC update copyright year static landing page 

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1232]
#### Describe the issue linked to the documentation

The copyright of the landing page currently says 2021.

#### Suggest a potential alternative/fix

Update to 2023 on [this line]

**Comment by Daniel-olaO** [comment]
Hi, I want to resolve the issue

**Comment by Daniel-olaO** [comment]
Okay thanks @hildeweerts

**Comment by Daniel-olaO** [comment]
done

**Comment by hildeweerts** [comment]
Fixed by #1233
