### ISSUE TITLE
DOC Add section to contributor guide "contributing code" on new features

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1236]
#### Describe the issue linked to the documentation

We currently do not explain in the contributor guide how we evaluate which features (metrics, algorithms, etc.) will be included in Fairlearn. 

#### Suggest a potential alternative/fix

To avoid disappointment from prospective contributors, we should be much clearer about what we do (not) want to include.

**Comment by alliesaizan** [comment]
Hi there! I can add a section to the "Contributing code" page about what we do/do not accept. If you could provide some bullets with the main points, I can formalize that into guidelines. Also, if there are particular relevant issues (open or closed) that come to mind, that would also be helpful. Please let me know!

**Comment by hildeweerts** [comment]
Generally, I think we should be clear that we are quite picky for various reasons (the field is still developing, we would like to emphasize sociotechnical context, etc.)

For algorithms, the main requirement is that it is described in a peer-reviewed paper (to avoid having to essentially replicate the peer-reviewing process ourselves). I personally also would prefer algorithms that are intuitively easy to grasp and make explicit the underlying empirical and normative assumptions (e.g., designed to tackle a specific type of measurement bias), but others might feel differently.

For metrics, we currently only support disaggregated metrics, so anything that does not fall into the group fairness metric paradigm would first need to be discussed thoroughly.

@MiroDudik probably has opinions as well.

**Comment by alliesaizan** [comment]
Gotcha! About to open up a PR with a paragraph that describes this reasoning and I will tag you both as reviewers.

**Comment by hildeweerts** [comment]
Closed by #1290
