### ISSUE TITLE
DOC make PR for #1233 in the fairlearn website repository

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1238]
As the static landing page currently does not get pushed to the website repository when a PR gets merged, we need to manually include the changes in #1233 in the [website repo](https://github.com/fairlearn/fairlearn.github.io).

**Comment by romanlutz** [comment]
Voila: https://github.com/fairlearn/fairlearn.github.io/pull/11

**Comment by romanlutz** [comment]
Merged.
