### ISSUE TITLE
DOC write script such that the static landing page is pushed to the website repository

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1239]
Currently, only changes to the documentation of the current Fairlearn version are pushed to fairlearn.github.io. Changes to the static landing page need to be added manually to the website repo (see #1233 and #1238). 

It would be great if we could add a script that makes sure any changes made to the static landing page in the fairlearn repository are automatically pushed to the website repository.

**Comment by romanlutz** [comment]
#1316 by @riedgar-ms should finally have addressed this.
