### ISSUE TITLE
Wrong Code in the documentation

### ISSUE THREAD

**Issue by eskayML** [fairlearn/fairlearn#1240]
#### Describe the issue linked to the documentation
Hello, so the very first piece of code in the [QuickStart Page]( https://fairlearn.org/main/quickstart.html) seem to contain quite a few problems
```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from fairlearn.datasets import fetch_adult
data = fetch_adult()
X = pd.get_dummies(data.data)
y_true = (data.target == '>50K') * 1
sex = data.data['sex']
sex.value_counts()
```
first of all, on line 6, the pd.get_dummies returns an error, owing to the fact that the data.data object is actually a numpy array without columns names , also the same issue occurs on line 8 where we tried to reference the `sex` column which  also  returns an error, I think a quick fix to the entire code would be the following:

## solution
```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from fairlearn.datasets import fetch_adult
data = fetch_adult()
df = pd.DataFrame(data.data, columns = data.feature_names)
X = pd.get_dummies(df)
y_true = (data.target == '>50K') * 1
sex = df['sex']
sex.value_counts()
```

**Comment by eskayML** [comment]
PS: I just realized that adding the `as_frame = True` actually fixes the entire error in the first code😅

**Comment by adrinjalali** [comment]
@eskayML thanks for reporting this. would you like to open a PR with the fix?

**Comment by eskayML** [comment]
@adrinjalali done ✅
