### ISSUE TITLE
DOC documentation for methods are not fully rendered

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1243]
#### Describe the issue linked to the documentation

The new documentation structure implemented in #1184 does not fully render the documentation of methods of classes.

Example for MetricFrame: 
Before (v0.8.0): https://fairlearn.org/v0.8/api_reference/fairlearn.metrics.html#fairlearn.metrics.MetricFrame
Current (v0.9.0): https://fairlearn.org/main/api_reference/generated/fairlearn.metrics.MetricFrame.html

#### Suggest a potential alternative/fix

I'd expect this to be a simple change in settings of autosummary but I haven't had a chance to look into it more deeply. 

Tagging @alliesaizan

**Comment by alliesaizan** [comment]
Hi there, I agree that it would probably be an autosummary fix within the index.rst file unders docs/api_reference. I will look into this issue this week and let you know if the fix is less straightforward than it appears.

**Comment by hildeweerts** [comment]
@alliesaizan that would be great, thanks!!

**Comment by alliesaizan** [comment]
> @alliesaizan that would be great, thanks!!

@hildeweerts I think I figured out the issue. The sphinx autogallery [documentation ](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html) states that the extension provides several templates, which we reference in "docs/api_reference/index.rst":

![image](https://github.com/fairlearn/fairlearn/assets/15962391/39fc6f23-97b6-40b4-915b-4ba7c100bd2d)

However, I cannot find these templates in the sphinx site-package, which suggests that these templates [are not](https://stackoverflow.com/questions/60005605/where-are-sphinx-autosummary-templates-for-functions) [provided](https://stackoverflow.com/questions/2701998/automatically-document-all-modules-recursively-with-sphinx-autodoc/62613202#62613202) [by the library](https://github.com/sphinx-doc/sphinx/tree/master/sphinx/ext/autosummary). My suggested solution is to add a "_templates" directory under docs. In this new directory, I added a new template file and replaced the former "class.rst" template references in the "api_reference/index.rst" file. This change appears to link to the methods/attributes within a class:
![image](https://github.com/fairlearn/fairlearn/assets/15962391/114536cd-1dd8-40f0-9808-ae0b6c736e86)

Please let me know your thoughts and if this looks on the right track, I will open up a PR for further review. I did a relatively shallow scan of the sphinx documentation to troubleshoot this issue, so I welcome any sphinx insight from the maintainers that I have missed. Thank you!

**Comment by romanlutz** [comment]
By all means, please try to see if that works. What I don't fully understand is what cased this to change (version upgrade?). If so, perhaps other projects have had to deal with the same problem. Just saying in case we're looking for validation for the idea :-)

**Comment by romanlutz** [comment]
This was addressed in #1244
