### ISSUE TITLE
DOC Add intersectionality notebook to Fairlearn

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1245]
Yifan has processed all comments on the notebook on intersectional fairness assessment:
https://colab.research.google.com/drive/1T0WyRVBu1JHw7hc2aI1C1dB3wBHkwzjZ

The next steps:
* convert the colab to a .py file 
* add the .py file to the [examples](https://github.com/fairlearn/fairlearn/tree/main/examples) folder

@LeJit do you have any recommendations on the best way to convert a colab to a .py file?

**Comment by romanlutz** [comment]
Colab should be exportable to ipynb which can be converted with nbconvert I think. The trickier part IMO is getting the py file into the right format for the website. The examples directory has good examples for what this should look like but I'm happy to help if needed. I know how much work goes into making such an extensive notebook so this isn't where it should get stuck 🙂

**Comment by LeJit** [comment]
After downloading the Colab notebook, I would recommend using `jupytext` to export to [percent format](https://github.com/mwouts/jupytext/blob/main/docs/formats.md) to get a .py file that mostly matches the format we need. If I recall correctly, the big things that need to be changed are headers and external links after using the conversion tool.

**Comment by romanlutz** [comment]
Correct! 

Basically markdown to Restructured text. That's the part I can help with if needed.
