### ISSUE TITLE
MNT tests are failing

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1254]
Two of our tests are failing (see e.g.,  #1244):
___
In `all-deps` we get the warning: `FAILED test/unit/test_show_versions.py::test_smoke - DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives`.

According to [this comment](https://github.com/pandas-dev/pandas/issues/44980#issuecomment-1001237377) we should be able to "fix" this by simply swapping `pip` and `setuptools` [here](https://github.com/fairlearn/fairlearn/blob/8282ce3c1d32aa8c0b7f17f1f35e20380d93fc89/fairlearn/show_versions.py#L39).
___
In `other-ml` we get the following error: `ERROR test_othermlpackages/test_tensorflow.py - AttributeError: module 'numpy' has no attribute 'typeDict'` related to `tf = pytest.importorskip("tensorflow")` resulting in issues once `h5py` is used.  I think we probably need to upgrade `pytest` to a newer/the newest version.

**Comment by romanlutz** [comment]
Running this locally I get yet another one 
```
test\unit\postprocessing\test_plots.py:4: in <module>
    import pkg_resources
C:\ProgramData\Anaconda3\envs\fairlearn\lib\site-packages\pkg_resources\__init__.py:121: in <module>
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
E   DeprecationWarning: pkg_resources is deprecated as an API
```

**Comment by romanlutz** [comment]
I believe this is fully addressed. @hildeweerts feel free to reopen otherwise.
