### ISSUE TITLE
How do we calculate Demographic parity difference, DPR, etc. object detection scenario?

### ISSUE THREAD

**Issue by pearlmary** [fairlearn/fairlearn#1285]
How do we calculate Demographic Parity difference/ratio and Equalized odds difference/ratio in object detection. In object detection our y_true and y_pred are bboxes instead of singular values, so how do we do it?

**Comment by hildeweerts** [comment]
Hi, @pearlmary! demographic parity and equalized odds are specifically designed for (binary) classification tasks.

Fairlearn does not include metrics for object detection out of the box. It depends on your application context which metric would make sense to compare across groups. 

For example, if you're concerned about disparities in predictive performance across groups, you could compare your favorite predictive performance metric for object detection (e.g., mAP) across groups using `MetricFrame`. As long as your metric behaves as a scikit-learn metric, with `y_true` and `y_pred` as input and a singular value as output, `MetricFrame` does not really care whether `y_true` is a list of singular values or a list of an bbox objects.

You can also define your own fairness metric using `make_derived_metric` that computes e.g., the maximum difference in predictive performance between groups, see [API docs](https://fairlearn.org/v0.9/api_reference/generated/fairlearn.metrics.make_derived_metric.html#fairlearn.metrics.make_derived_metric) and [this user guide](https://fairlearn.org/v0.9/user_guide/assessment/custom_fairness_metrics.html).

I hope this helps!

**Comment by pearlmary** [comment]
Thanks a lot for the quick reply.
