### ISSUE TITLE
DOC add link to raise issue

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#1301]
#### Describe the issue linked to the documentation

In today's community call, the idea was brought up (by @MiroDudik  or @hildeweerts , I forget...) to add a link on example notebooks to raise an issue. This should make it easy for readers to raise issues without having to navigate to our repo first and then copy-paste links to the correct notebook etc.

#### Suggest a potential alternative/fix

There's no feature in sphinx-gallery that does that automatically BUT I found this is the pytorch docs:

raw.githubusercontent.com/pytorch/tutorials/3e9e8f68cc904f9eb37c862348cc2216611faadd/intermediate_source/ddp_tutorial.rst

```
.. note::
   |edit| View and edit this tutorial in `github <https://github.com/pytorch/tutorials/blob/main/intermediate_source/ddp_tutorial.rst>`__.
```

So this would just be a highlighted box with a link and we'd have to make sure the link is correct. The file names rarely change so it wouldn't be hard to maintain over time, though.

![image](https://github.com/fairlearn/fairlearn/assets/10245648/56fd3d48-407d-492c-bf19-4e86f4dd515c)

Thoughts @fairlearn/fairlearn-maintainers ?

**Comment by hildeweerts** [comment]
Sounds like a fine and not too overengineered solution to me! :)

**Comment by Hrittik20** [comment]
Hello @romanlutz! Just to confirm, do I need to add this to only "Example Notebooks" page?

**Comment by romanlutz** [comment]
It needs to be added to every single notebook I would imagine.

**Comment by Hrittik20** [comment]
@romanlutz So I need to put the links to the appropriate notebooks, right? For example, for contributing example notebook, I need to use this link "https://github.com/fairlearn/fairlearn/blob/main/docs/contributor_guide/contributing_example_notebooks.rst"

**Comment by romanlutz** [comment]
I was thinking more along the lines of linking to the code file in the repo. Once you are there you can hit edit and create a branch with your changes. 

But what you're saying has merit, too. For most people it's probably advisable to first file an issue and ask if the changes are meant to happen instead of doing all the work for a PR.

We could do both...

**Comment by hildeweerts** [comment]
Perhaps we can add two links, 'view source' to the code file and 'open issue' (with a link like https://github.com/fairlearn/fairlearn/issues/new?title=DOC%20Issue%20blabla&body=blabla.)

**Comment by TamaraAtanasoska** [comment]
@romanlutz I am not sure if I follow. Is the goal to raise an issue about the example being broken? Is the end goal to improve reporting for not working examples?

**Comment by TamaraAtanasoska** [comment]
> The button would help people report problems in an example. All they'd have to do is click the button and it would open the GH page, perhaps with the example link prefilled. To what extent that is possible is unclear to me since I'm lacking the context in Sphinx.

ok got it, it is about issues in the concrete example. I might look into this as I am dealing with some spinx stuff this week.

**Comment by romanlutz** [comment]
Jupyter book has this as I discovered today. In plain Sphinx it may be harder to do

**Comment by TamaraAtanasoska** [comment]
> Jupyter book has this as I discovered today. In plain Sphinx it may be harder to do

It seems the Pydata Sphinx theme offers some options, I hope to make it both looks nice and functional in the PR (still WIP).
