### ISSUE TITLE
Possible typo in documentation for Equalized odds

### ISSUE THREAD

**Issue by fountaindive** [fairlearn/fairlearn#1314]
#### Describe the issue linked to the documentation

I think there is a small typo in the documentation for Equalized odds.

Quoting the last paragraph in the docs for [equalized-odds](https://fairlearn.org/main/user_guide/assessment/common_fairness_metrics.html#equalized-odds)

>However, since equalized odds is based on both the true positive and false positive rates, there is an extra step in order to return a single scalar result. For [equalized_odds_difference()](https://fairlearn.org/main/api_reference/generated/fairlearn.metrics.equalized_odds_difference.html#fairlearn.metrics.equalized_odds_difference), we first calculate the true positive rate difference and the true negative rate difference separately. We then return the larger of these two differences.

I believe the mention of "true negative rate" is incorrect.

The documentation for [equalized_odds_difference](https://fairlearn.org/main/api_reference/generated/fairlearn.metrics.equalized_odds_difference.html#fairlearn.metrics.equalized_odds_difference) seems to be correct though as it only mentions true positive and false positive rates.

#### Suggest a potential alternative/fix

I think the correct wording should be:

current

"we first calculate the true positive rate difference and the true negative rate difference separately"

new

"we first calculate the true positive rate difference and the false positive rate difference separately"

**Comment by romanlutz** [comment]
Maybe I'm not thinking about this enough, but TNR = 1-FPR, so the TNR difference is the same as the FPR difference since the 1 cancels out in a subtraction. Does that make sense?

**Comment by hildeweerts** [comment]
@romanlutz is correct that computing the absolute difference in TNR and FPR is equivalent. However, what we actually [do](   https://github.com/fairlearn/fairlearn/blob/142c5580ead67b4f0b4b9f87a9a131af4656c380/fairlearn/metrics/_fairness_metrics.py#L189) is compute the TPR and FPR differences, so @fountaindive's suggested change would be more consistent with the code base.

**Comment by fountaindive** [comment]
Ah yes good point! I was about to say that would change the sign of the difference but you compute the absolute difference.

**Comment by hildeweerts** [comment]
Would you like to open a PR to address your suggested change yourself, @fountaindive?

**Comment by fountaindive** [comment]
Here ya go! https://github.com/fountaindive/fairlearn/pull/1

**Comment by fountaindive** [comment]
Here we go: https://github.com/fairlearn/fairlearn/pull/1315
