### ISSUE TITLE
Equal opportunity metric implementation

### ISSUE THREAD

**Issue by faildeny** [fairlearn/fairlearn#1322]
#### Is your feature request related to a problem? Please describe.
 
The documentation [page](https://fairlearn.org/v0.9/user_guide/assessment/common_fairness_metrics.html) describes the following fairness metrics along with some code snippets:
- Demographic parity
- Equalized odds
- Equal opportunity

However, there is no implementation of Equal Opportunity metric in the library, which is quite confusing.

#### Describe the solution you'd like

Ability to calculate e.g. `equal_opportunity_difference` in the same way as other fairness metrics e.g. `demographic_parity_difference` or `equalized_odds_difference`. 

#### Describe alternatives you've considered, if relevant

The metric can be calculated not-directly with already existing functionality (`MetricFrame` and `true_positive_rate`), however it seems to be more intuitive and consistent to have it directly available like e.g. `demographic_parity_difference` implemented in [`fairlearn/metrics/_fairness_metrics.py`](https://github.com/fairlearn/fairlearn/blob/main/fairlearn/metrics/_fairness_metrics.py).

#### Additional context

If agreed, I can submit an implementation that will allow the direct calculation in the same way as the other fairness metrics.

**Comment by romanlutz** [comment]
Sounds like you're describing `true_positive_rate_difference`. One option might be to have an alias that is identical? I do think TPR difference is a much preferable name which is why we have it this way. However, the docs should mention that we call it TPR difference if we don't have EOpp as a metric name.

@fairlearn/fairlearn-maintainers thoughts?

**Comment by hildeweerts** [comment]
I would be happy either way. The advantage of having an alias called equal opportunity is that those specifically looking for the metric would be able to find it. I also agree we should adjust the docs in any case. This is also related to the discussion in https://github.com/fairlearn/fairlearn/issues/1313#issuecomment-1822821569

**Comment by faildeny** [comment]
I agree that it's mostly a naming convention. In my case I was looking for equal opportunity metric and _fairlearn_ docs are the first result among other fairness libraries. 

As said before, there is no code that supports the naming convention in the documentation article I linked above. For less experienced users it may not be that straightforward to go for `true_positive_rate` instead. Let me know if you would prefer to just mention it in the docs or add the code implementation.

**Comment by romanlutz** [comment]
I agree that we could do both the doc update and the alias (code change).

@faildeny do you want to try making (one of) the change(s)?

**Comment by faildeny** [comment]
@romanlutz ok, I will prepare the changes

**Comment by romanlutz** [comment]
@faildeny amazing! Reach out if anything is unclear or you run into problems.

**Comment by faildeny** [comment]
PR with first proposal added #1325

**Comment by hildeweerts** [comment]
Fixed by #1325!
