### ISSUE TITLE
Adversarial Mitigation Error

### ISSUE THREAD

**Issue by joelthe1** [fairlearn/fairlearn#1332]
#### Describe the bug
Unable to run Adversarial Mitigation with a sensitive features vector.

#### Steps/Code to Reproduce
See GitHub Gist: https://gist.github.com/joelthe1/df8b948465741f0cc03f15617f91a609

#### Expected Results
Expected to successfully run training and show predictions.

#### Actual Results
```RuntimeError: The size of tensor a (8) must match the size of tensor b (3) at non-singleton dimension 1```

#### Versions
- Firefox
- Python version: 3.11.3]
- Fairlearn version: 0.9.0

**Comment by SeanMcCarren** [comment]
@joelthe1 Thanks a bunch for this elaborately typed-out issue, and the accompanied gh gist. Please review [this fix](https://github.com/fairlearn/fairlearn/pull/1333) for this issue.

**Comment by joelthe1** [comment]
This looks okay to me. Will raise separate issue if I encounter anything later.

**Comment by TamaraAtanasoska** [comment]
@adrinjalali this issue can be closed.
