### ISSUE TITLE
MNT Replace flake8 with ruff for linting

### ISSUE THREAD

**Issue by TamaraAtanasoska** [fairlearn/fairlearn#1364]
Both for speed and convenience, a proposal to replace `flake8` with `ruff`, to run alongside `black` for linting.

For testing and exploration, I've created a [branch](https://github.com/TamaraAtanasoska/fairlearn/tree/linting-updates) that replaces `flake8` with `ruff`, updates the documentation and fixes all new raised errors for a clean slate.

@adrinjalali

**Comment by adrinjalali** [comment]
That sounds good to me. We should also make sure they're applied to all existing files.

**Comment by TamaraAtanasoska** [comment]
> That sounds good to me. We should also make sure they're applied to all existing files.

Awesome! There is a commit resolving all errors, there were just a few and very unproblematic edits. I will make a PR then and link the issue.

**Comment by adrinjalali** [comment]
Cool. Once that is merged, we should merge a PR ignoring that commit in git-ignore-revisions

**Comment by TamaraAtanasoska** [comment]
With the switch from `flake8` to `ruff` happening in #1365 and the `.git-blame-ignore-revs` update in #1371, this issue can be closed.
