### ISSUE TITLE
BUG Initialising a parameter with an empty default mutable type in estimator

### ISSUE THREAD

**Issue by TamaraAtanasoska** [fairlearn/fairlearn#1368]
The `_AdversarialFairnes` estimator has a parameter `predictor_model` parameter which is initialised with an empty list. This causes the `check_parameters_default_constructible` scikit-learn check estimator check to fail. 

The bug can be fixed with initialising the parameter with `None`, and then change to empty list in the fit ([example here](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/linear_model/_ransac.py#L374)).

Happy to take this on next, or since it needs to be added to the changelog at a convenient time.

@adrinjalali

**Comment by adrinjalali** [comment]
Yes, that sounds right. thanks @TamaraAtanasoska
