### ISSUE TITLE
Incorporating Sensitive Features with Sampling Methods

### ISSUE THREAD

**Issue by haytham918** [fairlearn/fairlearn#1377]
I am currently trying to incorporate `imblearn`'s sampling methods such as `SMOTE()` and `NearMiss()` with `ThresholdOptimizer` and `AdversarialFairnessClassifier`. When I try to put all of them to run in `imblearn.pipeline`(sampling then classifier), the sampling step fails, which I guess it does not know what to do with the sensitive features we passed as metadata. Right now, I am twisting the work-flow to work this around, but I would like to know if there is a configuration or a feature that can easily solve this.

**Comment by adrinjalali** [comment]
You should report this on the imbalanced learn side. (cc @glemaitre)

**Comment by haytham918** [comment]
Will do so
