### ISSUE TITLE
The User Guide description of the ACSIncome dataset does not include the ST feature.

### ISSUE THREAD

**Issue by excepto64** [fairlearn/fairlearn#1390]
The User Guide description https://fairlearn.org/v0.10/user_guide/datasets/acs_income.html#dataset-description of the ACSIncome dataset does not include the ST (state) feature. 
The description is here (taken from https://www2.census.gov/programs-surveys/acs/tech_docs/pums/data_dict/PUMS_Data_Dictionary_2018.pdf): 
ST Character 2
State Code based on 2010 Census definitions
01 .Alabama/AL
02 .Alaska/AK
04 .Arizona/AZ
05 .Arkansas/AR
06 .California/CA
08 .Colorado/CO
09 .Connecticut/CT
10 .Delaware/DE
11 .District of Columbia/DC
12 .Florida/FL
13 .Georgia/GA
15 .Hawaii/HI
16 .Idaho/ID
17 .Illinois/IL
18 .Indiana/IN
19 .Iowa/IA
20 .Kansas/KS
21 .Kentucky/KY
22 .Louisiana/LA
23 .Maine/ME
24 .Maryland/MD
25 .Massachusetts/MA
26 .Michigan/MI
27 .Minnesota/MN
28 .Mississippi/MS
29 .Missouri/MO
30 .Montana/MT
31 .Nebraska/NE
32 .Nevada/NV
33 .New Hampshire/NH
34 .New Jersey/NJ
35 .New Mexico/NM
36 .New York/NY
37 .North Carolina/NC
38 .North Dakota/ND
39 .Ohio/OH
40 .Oklahoma/OK
41 .Oregon/OR
42 .Pennsylvania/PA
44 .Rhode Island/RI
45 .South Carolina/SC
46 .South Dakota/SD
47 .Tennessee/TN
48 .Texas/TX
49 .Utah/UT
50 .Vermont/VT
51 .Virginia/VA
53 .Washington/WA
54 .West Virginia/WV
55 .Wisconsin/WI
56 .Wyoming/WY
72 .Puerto Rico/PR

**Comment by romanlutz** [comment]
Hi @excepto64 ! That's correct. We wrote the fetch function so that you can query by state

https://fairlearn.org/v0.10/api_reference/generated/fairlearn.datasets.fetch_acs_income.html#fairlearn.datasets.fetch_acs_income

Does that help?

**Comment by excepto64** [comment]
Okay, I guess in that case, what I was trying to report is that the usage guide does not show how to use this dataset. The most obvious way for me to access the dataset was using the OpenML [https://www.openml.org/d/43141](link) to download the data rather than using the fetch function. The OpenML data contains ST as a separate column and hence my confusion when I ended up with 11 columns instead of 10.
I guess my suggestion would be to add a 1 sentence long subheading on usage of the dataset to the user guide, to make it more informative and consistent with the Diabetes dataset.

**Comment by adrinjalali** [comment]
Feel free to open a PR with your suggestion @excepto64
