### ISSUE TITLE
Version 0.11 release

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#1391]
Should we do a new release? We've fixed quite a few pandas and numpy issues and I think it'd be nice to release those fixes.

WDYT @fairlearn/fairlearn-maintainers

**Comment by riedgar-ms** [comment]
Fine by me

**Comment by hildeweerts** [comment]
Sounds good!

**Comment by riedgar-ms** [comment]
Is this still active? I know that there were a couple of PRs about a release while I was on holiday.

**Comment by adrinjalali** [comment]
yeah I lost the momentum since it wasn't easy to get the reviews 😁 need to restart again

**Comment by riedgar-ms** [comment]
Would be good to get this moving... can you point me at the reviews you need doing please, @adrinjalali ?

**Comment by TamaraAtanasoska** [comment]
@riedgar-ms looking at the PRs I believe this one would be great to merge and nothing else looks urgent: https://github.com/fairlearn/fairlearn/pull/1380. Maybe @adrinjalali thinks otherwise?
