### ISSUE TITLE
Always returning a numpy array in FloatTransformer.inverse_transform

### ISSUE THREAD

**Issue by TamaraAtanasoska** [fairlearn/fairlearn#1395]
The new scikit-learn estimator checks, specifically [check_classifiers_train](https://github.com/scikit-learn/scikit-learn/blob/df25e3747b36bf11d328fe2cc39561a7f933aefd/sklearn/utils/estimator_checks.py#L2416) expect that `Y_pred` always is always a `numpy array` and not `list`. However, `FloatTransformer.inverse_transform` is implemented in a way that allows the input type to be preserved, in the case of `list`, `Dataframe` and `Series` ([here](https://github.com/TamaraAtanasoska/fairlearn/blob/main/fairlearn/adversarial/_preprocessor.py#L189)). Using `FloatTransformer.inverse_transform` [here](https://github.com/TamaraAtanasoska/fairlearn/blob/main/fairlearn/adversarial/_adversarial_mitigation.py#L608) triggers the error. 

Is this behaviour still desired to be kept as it is, in which case we can keep the test under the xfail flag, or I could look into changing this behaviour to always return a `numpy array`?

**Comment by adrinjalali** [comment]
I think the output should really be an array.

**Comment by adrinjalali** [comment]
Unless @SeanMcCarren remembers a reason not to.

**Comment by TamaraAtanasoska** [comment]
this one has been merged and can be closed @adrinjalali
