### ISSUE TITLE
Fairlearn.Reduction.ExponentiatedGradient has been receiving the sample weights, but it is giving the inner models without applying the weight.  With weight and without weight, appears the same outcome.

### ISSUE THREAD

**Issue by sln2737** [fairlearn/fairlearn#1400]
#### Steps/Code to Reproduce

```
Sample code to reproduce the problem
```

**Comment by adrinjalali** [comment]
If the underlying estimator with the given sample weight and data doesn't return a different, model, then the end results would be the same.

Closing as this needs a good reproducer to investigate further.
