### ISSUE TITLE
README in portuguese

### ISSUE THREAD

**Issue by GabrielLeite2004** [fairlearn/fairlearn#1409]
i was opened to solution this

**Comment by adrinjalali** [comment]
We've had discussions in the ecosystem about this.The hard part of having translations is how to keep them in sync when we don't have people who can validate translation into other languages.

**Comment by TamaraAtanasoska** [comment]
Thanks @GabrielLeite2004 for your suggestion! Since we won't be moving in this direction, could this issue be closed @adrinjalali?
