### ISSUE TITLE
MetricFrame bootstrapping breaks if not all the sensitive feature's values are sampled

### ISSUE THREAD

**Issue by taharallouche** [fairlearn/fairlearn#1441]
#### Describe the bug
When the data fed to a `MetricFrame` (with `n_boot` and `ci_quantiles` not set to `None`) is sampled for bootstraping, there's no guarantee that all the values the sensitive features takes will be represented in the sampled data.

If it happens that in some samples, some values are left out, the `MetricFrame` object instantiation breaks.

The probability of this occurring would depend on the distribution of the sensitive features in the data, and it would be more likely to happen if some "minority" classes are present in the data.

#### Steps/Code to Reproduce
Example:
```python
y_true = [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0]
y_pred = [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0]
sensitive_features = ["a", "b", "c", "a", "b", "c", "a", "b", "c", "a", "b"]

random_state = np.random.RandomState(1234)


mf = MetricFrame(
    metrics={"selection_rate": selection_rate},
    y_true=y_true,
    y_pred=y_pred,
    sensitive_features=sensitive_features,
    ci_quantiles=[0.1, 0.5, 0.9],
    n_boot=3,
    random_state=random_state,
)
```

#### Expected Results
The MetricFrame object is created.

#### Actual Results
Here's the error stack:
```
Traceback (most recent call last):
  File "/home/allouche/repos/fairlearn/fairlearn/metrics/experimental_bootstrap.py", line 21, in <module>
    mf = MetricFrame(
         ^^^^^^^^^^^^
  File "/home/allouche/repos/fairlearn/fairlearn/metrics/_metric_frame.py", line 309, in __init__
    self._populate_results_ci(_bootstrap_samples, ci_quantiles)
  File "/home/allouche/repos/fairlearn/fairlearn/metrics/_metric_frame.py", line 406, in _populate_results_ci
    result_group = calculate_pandas_quantiles(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/allouche/repos/fairlearn/fairlearn/metrics/_bootstrap.py", line 137, in calculate_pandas_quantiles
    result = _calc_dataframe_quantiles(quantiles=quantiles, samples=bootstrap_samples)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/allouche/repos/fairlearn/fairlearn/metrics/_bootstrap.py", line 112, in _calc_dataframe_quantiles
    assert all(s.index == samples[0].index), "Sanity check shape of bootstrap sample"
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/allouche/repos/fairlearn/.venv/lib/python3.12/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/allouche/repos/fairlearn/.venv/lib/python3.12/site-packages/pandas/core/arraylike.py", line 40, in __eq__
    return self._cmp_method(other, operator.eq)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/allouche/repos/fairlearn/.venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 7185, in _cmp_method
    raise ValueError("Lengths must match to compare")
ValueError: Lengths must match to compare
```

Tracing back the cause of the error, I see that one of the samples doesn't include any row with a "b" sensitive feature:
```
    y_true  y_pred sensitive_feature_0
0        1       1                   a
1        1       1                   c
2        0       0                   a
3        1       1                   a
4        0       0                   a
5        1       1                   c
6        0       0                   a
7        1       1                   c
8        1       1                   c
9        1       1                   c
10       1       1                   c
```

#### Fix Suggestion
I would suggest that instead of bootstrapping the whole dataset, we bootstrap each group within the sensitive feature alone, and we concatenate the results. So basically, doing "stratified sampling".

This fix would break reproducibility though (with the same data and random seed, a `fairlearn` user that has an older version would get different results).

#### Versions
- OS: Ubuntu 24.04.1 LTS
- Python version: 3.12.3
- Fairlearn version: https://github.com/fairlearn/fairlearn/commit/8ce6e35b822929c30d4a1ab732f3c0fc3a0b384b

**Comment by glemaitre** [comment]
> I'm not sure if a stratified sampling is the right choice here, since it probably breaks some statistical properties.

I think that I agree here. It looks like a bias will be introduced. It might be better to let the user defined what he would do in such case.

**Comment by hildeweerts** [comment]
Tagging @Harsha-Nori who might have thoughts on this too

**Comment by MiroDudik** [comment]
I think there are two reasonable approaches:
1. When the bootstrap replicate does not contain any elements from a given group, it should return `np.nan`, and we should use `np.nanquantile` to get the values of various `*_ci` quantities. This will yield valid quantiles (under the same assumptions as the standard bootstrap). I don't think that we should allow substituting some other default value (like 0 or 1) in this case, because that is likely to lead to wrong quantiles. This approach would be also backward compatible re. random seeds. One possible downside is that `*_ci` might sometimes still include `np.nan`.
2. We could possibly also allow the user to use stratified bootstrap, which would mean stratifying the boostrapping procedure by the joint value of the **sensitive features and control features**. This would yield valid confidence intervals for the individual slices, but it would typically underestimate variance of various global (and possibly some cross-group) quantities.
    * As an extreme example, imagine that your dataset consists of 100 data points, each belonging to a different sensitive group. Then all the stratified bootstrap replicates would be identical, so we wouldn't get sensible overall quantiles. On the other hand, standard bootstrap would give reasonable overall quantiles. (Of course, neither of these techniques would give sensible group-level confidence intervals in this extreme case... this is just to illustrate the point about underestimating overall variance.)

So--I'm definitely in favor of using the approach (1) above--that is, impute `np.nan` when the group is empty and use `np.nanquantile` to get the quantiles.

**Comment by taharallouche** [comment]
I'll go ahead and implement @MiroDudik 's suggestion if no one has any objection

**Comment by hildeweerts** [comment]
Yes, please go ahead, @taharallouche!!
