### ISSUE TITLE
DOC Fix the copy output of the first link in the "Contributing Documentation" section

### ISSUE THREAD

**Issue by TamaraAtanasoska** [fairlearn/fairlearn#1456]
In the[ "Contributing Documentation" section](https://fairlearn.org/v0.11/contributor_guide/contributing_documentation.html), clicking on the copy button of the first link copies additional `.css` code that shouldn't be there.

```
span.prompt1:before {
  content: "$ ";
}
python scripts/install_requirements.py --pinned False
```

The fix would include going over the contents of that `.rst` document, checking if there is anything that could cause this, and fixing it. Ideally, the person working on this issue would check if this problem is present elsewhere in the generated documentation as well.

The copy button is part of the `sphinx_copybutton` extension.

Thank you @audreyfeldroy for finding this issue during the PyLadiesCon sprint!

**Comment by TamaraAtanasoska** [comment]
Hi @anhpnv, no problem, thanks for taking a look! Feel free to make a PR and tag me (and the issue) :) I will take review it and comment on the PR.

**Comment by anhpnv** [comment]
Hi @TamaraAtanasoska, I'm already create a Pull Request, could you please review it for me 😄

**Comment by TamaraAtanasoska** [comment]
@anhpnv thanks for your patience, I was sick last week. Merged! This issue can be closed now 🥳
