### ISSUE TITLE
Release Pipeline Improvements

### ISSUE THREAD

**Issue by riedgar-ms** [fairlearn/fairlearn#200]
In addition to the `pip freeze` proposal, the 0.4.0 release has highlighted a weakness in our release automation. This is around the
- Required updates to `ReadMe.md` (not helped by GitHub and PyPI having difference concepts of markdown syntax)
- Branching and tagging of the release

We need to get all these automated so they are done and done consistently.

**Comment by adrinjalali** [comment]
you could alternatively use `.rst`, which is the same across platforms AFAIK.

**Comment by riedgar-ms** [comment]
Have done this for the current `ReadMe.md` file.
