### ISSUE TITLE
try to pass sklearn's check_estimator

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#222]
[This page](https://scikit-learn.org/dev/developers/develop.html#rolling-your-own-estimator) explains how you can write a test to pass tests included in `check_estimator`. We can see which ones fail and see if we can fix them.

**Comment by TamaraAtanasoska** [comment]
Does this one still need to be open? We have recently used the new way to test estimators to test `AdversarialFairnessClassifier`, `AdversarialFairnessRegressor` and `_AdversarialFairness` (example in #1384). Failing tests have either been resolved or moved under the `xfail` flags to be resolved soon.

**Comment by hildeweerts** [comment]
I agree I think this can be closed. @adrinjalali are you happy with the changes?
