### ISSUE TITLE
Add Error bars

### ISSUE THREAD

**Issue by rihorn2** [fairlearn/fairlearn#235]
Show error bars in reports when available

**Comment by michaelamoako** [comment]
There are a few potential implementations of Error bars/ Confidence bounds. My question is, how do we present them in a way that is clear and actionable. An example of one potential implementation (using the MetricFrame, though you could imagine this being woven into the plots as well) is below. 


**Wilson bounds** 
(@LeJit and Duncan)

```
def wilson(p, n, z = z_score):
    denominator = 1 + z**2/n
    centre_adjusted_probability = p + z*z / (2*n)
    adjusted_standard_deviation = np.sqrt((p*(1 - p) + z*z / (4*n)))/np.sqrt(n)
    lower_bound = (centre_adjusted_probability - z*adjusted_standard_deviation) / denominator
    upper_bound = (centre_adjusted_probability + z*adjusted_standard_deviation) / denominator
    return (lower_bound, upper_bound)
```
   
Using the above, you could then define functions for each bound, for a specific metric, and pass that into the metric frame. Below is an example of recall (which is a proportion, so n is calculated using the confusion matrix): 
```
def recall_bound_lower(y_t, y_p):
    assert len(y_t)==len(y_p)
    tp, tn, fp, fn = confusion_matrix(y_t, y_p).ravel()
    bounds = wilson(tp/(tp+fp), tp + fp, z_score)
    return bounds[0]

def recall_bound_upper(y_t, y_p):
    assert len(y_t)==len(y_p)
    tp, tn, fp, fn = confusion_matrix(y_t, y_p).ravel()
    bounds = wilson(tp/(tp+fp), tp + fp, z_score)
    return bounds[1]
```

Adding the above to the metric frame:

``` 
by_race_gender= MetricFrame({'Recall': true_positive_rate, 'Recall lower bound': recall_bound_lower, 'Recall upper bound': recall_bound_upper, 'Count':count}, 
                  pdf["golden_label"], 
                  ms_pred, 
                  sensitive_features = sensitive_cols)
```
The output of the Metric Frame using mock data with race and gender as sensitive features: 

![Confidence Bounds Metric Frame](https://user-images.githubusercontent.com/69976597/117990965-a047bc00-b30b-11eb-8fe6-0d402c357c0d.PNG)

**Comment by riedgar-ms** [comment]
Thank you for reanimating this discussion @michaelamoako !

As I said in the community call, I think that the statistical issues are too fraught for us to try offering error bounds intrinsically within `MetricFrame`. However, we absolutely should have examples for users to follow, similar to the one you give above. And as @MiroDudik mentioned on the call, we can adjust the `MetricFrame` so that when there are non-comparable columns (such as the confidence bounds, or a confusion matrix), a  `NaN` is returned, rather than throwing an exception.

**Comment by riedgar-ms** [comment]
Talking to @alexquach about working on this.

**Comment by riedgar-ms** [comment]
It would be good if three different formats for the errors:
 
- +/- number
- + number, - number
- lower bound, upper bound (as @michaelamoako has above)

**Comment by alexquach** [comment]
I'm working on this.

**Comment by TamaraAtanasoska** [comment]
Does the work done until now complete this issue @riedgar-ms, including the last work done in [37d20a8](https://github.com/fairlearn/fairlearn/commit/37d20a8bbf01f52f7bdb51196e40600de51e4273)? Or there is still more to be done?

**Comment by riedgar-ms** [comment]
I'm not sure this is relevant any more.

**Comment by hildeweerts** [comment]
Agreed @TamaraAtanasoska @riedgar-ms - I'm closing the issue!
