### ISSUE TITLE
Allow grouping by multiple sensitive features

### ISSUE THREAD

**Issue by rihorn2** [fairlearn/fairlearn#237]
Multiple sensitive features are a common scenario. The only other way to capture intersectionality is by creating a 1-dimensional grouping vector manually and providing that to Fairlearn. We want to make this easier and allow users to provide an m-dimensional matrix. This needs to be enabled on three levels:

- [x] mitigation techniques
- [x] metrics
- [ ] dashboard

The current implementation for mitigation techniques simply considers all combinations from the `sensitive_features` matrix, e.g. if column A has 4 distinct values and column B has 3 distinct values and all combinations occur we have 4*3=12 groups.

It is possible that users want more fine-grained control, but we'll wait for that feedback. This could mean specifying multiple constraints (demographic parity w.r.t. column A and demographic parity w.r.t. column B, but not intersections of A and B, for example).

**Comment by Dref360** [comment]
Hello,
I'm interested in this feature for Metrics.

If we take `group_summary` for example,

would the change be as simple as calling `np.unique(s_f, axis=0)` instead of `np.unique(s_f)`?
https://github.com/fairlearn/fairlearn/blob/master/fairlearn/metrics/_metrics_engine.py#L66

**Comment by romanlutz** [comment]
Sorry for missing your message, @Dref360 ! As you probably observed this went along with a complete redesign of the metrics API.

I'm closing this issue now since the remaining portion (dashboard integration) will not happen in this repo, but in the `raiwidgets` package's repo which will be released at the end of November.
