### ISSUE TITLE
Enable switching between metrics within a report

### ISSUE THREAD

**Issue by rihorn2** [fairlearn/fairlearn#238]
Allow user to select multiple metrics of interest and switch between them inside of the report view.

**Comment by kevinrobinson** [comment]
hello @rihorn2!  Is the idea here that this is design work to make a new variant of `<WizardReport />` that would show multiple disparity metrics at once, to better support directly comparing subgroup performance across multiple metrics?  I'm imagining something like this, using a binary classifier as an example:

![image](https://user-images.githubusercontent.com/1056957/74679343-99bfa880-518b-11ea-9cae-80b6c55ed10b.png)

Or is the idea more that a single visualization would allow comparing model performance for sensitive attributes across multiple measures of performance (eg, accuracy, precision, recall)?  Thanks! 👍

**Comment by rihorn2** [comment]
Hi Kevin, thank you for contributing to the repo! The idea with this item is to enable switching the metric here without going to the  'edit config' button and walking through the wizard again, just presenting the option in the metrics page of the wizard in a convenient dropdown. I believe Chinmay is including this in a PR he is working on.
Thanks,
Brandon

**Comment by kevinrobinson** [comment]
@rihorn2 Ah thanks!  👍 I guess I missed this notification and also didn't notice https://github.com/fairlearn/fairlearn/pull/283 earlier.  Yeah, I see the kind of UX you are describing there:

<img width="1029" alt="Screen Shot 2020-02-24 at 11 08 19 AM" src="https://user-images.githubusercontent.com/1056957/75169301-48b53480-56f6-11ea-89b3-a189619ace87.png">

<img width="1022" alt="Screen Shot 2020-02-24 at 11 08 39 AM" src="https://user-images.githubusercontent.com/1056957/75169252-363afb00-56f6-11ea-823a-2a399852a4f1.png">

I'm mostly just being curious here, but am interested in learning more about the user need here if you or @chisingh could share more.  In other words, why are folks doing that kind of navigation?  I was assuming it was sort of building up context on multiple different perspectives on fairness, and so this question seemed super interesting for thinking about different ways to support that need directly.  But I am mostly just making guesses and so curious about what's actually come up for folks using fairlearn :)

**Comment by romanlutz** [comment]
This won't get addressed in this repo. Stay tuned for the `raiwidgets` release at the end of November!
