### ISSUE TITLE
Test dependencies

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#245]
`conftest.py` under `test/perf` checks for `azureml`, but would also give the same error if the user doesn't have `tempeh` installed.

I encountered this error since I avoid installing everything which is in `requirements.txt` not to bloat my env unnecessarily.

Also, we could have the performance tests optional and skip them if the user doesn't have required dependencies. They're not an integral part of the functionality test anyway, are they?

**Comment by romanlutz** [comment]
Correct, they're not. We do that explicitly in the pipelines that run PR checks. Is there a better way of skipping them without having to write
```
python -m pytest --ignore=test/perf
```
?

**Comment by adrinjalali** [comment]
That makes sense, but I think that exception is still giving an incorrect message.

**Comment by romanlutz** [comment]
Which exception? I definitely want to fix bad messages :-)

**Comment by adrinjalali** [comment]
The one which says: `fairlearn performance tests require azureml-sdk to be installed.`

**Comment by romanlutz** [comment]
That is the truth AFAIK

**Comment by adrinjalali** [comment]
The issue is I saw the message, installed `azureml-sdk`, re-ran the tests, and got the same message. The issue was that I didn't have `tempeh` installed.

**Comment by romanlutz** [comment]
That's part of requirements.txt, though. Wouldn't it be expected to not be able to run things if you don't install the requirements?

The way the perf tests are set up right now is that you wouldn't run them locally anyway since that will take ages. So you really need some sort of cluster that takes care of it. We've chosen AzureML since it's the easiest option for us, but in theory you could plug in whatever you like. `tempeh` supports `azureml-sdk` right now, but you can feel free to add whatever other platforms you prefer. I am pretty much the only person behind `tempeh` right now, so anything useful you want to add is more than welcome. It's quite a bit hacky compared to `fairlearn`, though, because it's not the main priority.

**Comment by adrinjalali** [comment]
It'd be nice to have a little section for each part, saying what's needed for them, instead of referring people to the requirements.txt. As I mentioned, I ended up running all the tests with only a few of those packages listed in requirements.txt

For instance, you could say, 

```
Tests have extra dependencies, you can install them via:

    pip install tempeh etc etc
```

**Comment by romanlutz** [comment]
By section you mean in the CONTRIBUTING guide, README, or in the test directory in a separate README? I think this is a great suggestion!

**Comment by adrinjalali** [comment]
I mean probably contributing.md, since people who are going to contribute are the people who are going to test the library.

**Comment by romanlutz** [comment]
I guess we could rename this now since the perf test dependencies aren't the issue anymore, but rather test & notebook dependencies in general. The biggest factors IMO are tempeh which pulls in a bunch of things, and packages we use for smoke testing the compatibility light lightgbm.

**Comment by romanlutz** [comment]
I keep coming back to this without a good resolution :-(

If I add instructions into the contributor guide about specific dependencies then I bet they'll be outdated pretty quickly.

`requirements.txt` at least specifies what the dependencies are for, so a selective install is possible.

I'm hoping to get rid of `tempeh` and `shap` as dependencies in there as soon as the datasets module exists and I can add a few datasets there.

**Comment by adrinjalali** [comment]
You may wanna look at this one: https://github.com/scikit-learn/scikit-learn/pull/17573

It's probably an overkill here though :D

**Comment by romanlutz** [comment]
I think it's a good suggestion. It is quite a bit of engineering for this, but perhaps somebody wants to pick it up one day. 🙂

**Comment by romanlutz** [comment]
Closing this since #645 includes this work.
