### ISSUE TITLE
python tests instead of notebooks

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#248]
Would it be okay to replace the notebooks tests with `.py` tests? It'd be much easier to work with, and it'll also remove a bunch of test dependencies we have right now.

**Comment by adrinjalali** [comment]
I see there are also tests there, why are the notebooks there then?

**Comment by romanlutz** [comment]
The notebooks are there to actually show functionality to users, for example when you demo fairlearn.

**Comment by riedgar-ms** [comment]
And we have tests which run the notebooks as unit tests via papermill too.

**Comment by adrinjalali** [comment]
Alternatively you could have scripts from which notebooks are generated in the documentation platform.

There are different ways of doing it, in sklearn we use sphinx and sphinx-gallery to do that, and we provide `.py`, the notebook, and a link to binder for each user manual/example, here's an [example](https://scikit-learn.org/stable/auto_examples/release_highlights/plot_release_highlights_0_22_0.html#sphx-glr-auto-examples-release-highlights-plot-release-highlights-0-22-0-py)

Numpy is taking a different approach AFAIK, but usually we try to avoid having notebooks in the repo, since they're also hard to manage with version control systems (getting a meaning full `git diff` and `git blame` on them is pretty hard.)

**Comment by riedgar-ms** [comment]
We should look in to that. We had noticed that Notebooks don't play particularly nicely with git ;-)
