### ISSUE TITLE
Postprocessing - Separate plotting

### ISSUE THREAD

**Issue by riedgar-ms** [fairlearn/fairlearn#252]
Having the decision on plotting done in the constructor of the `ThresholdOptimizer` object is rather odd. The plotting should be moved to a separate routine

**Comment by adrinjalali** [comment]
We had very long discussions regarding the plotting API, and this is what we came up with, and will expand on: https://scikit-learn.org/stable/auto_examples/plot_roc_curve_visualization_api.html

**Comment by romanlutz** [comment]
Thanks @adrinjalali ! Ours would be based on the mitigation method and the data it trained on, so we wouldn't actually pass X, y. My PR hopefully makes it clear how to use it. Any comments/feedback appreciated!

**Comment by romanlutz** [comment]
This was obviously completed a long time ago. Closing the issue.
