### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by riedgar-ms** [fairlearn/fairlearn#256]
We should review our property naming conventions. For example, `sklearn` puts trailing underscores on attributes which have been calculated by operation of the class. See e.g.:
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

**Comment by MiroDudik** [comment]
I think we should aim to follow the conventions in
https://scikit-learn.org/stable/developers/develop.html

**Comment by adrinjalali** [comment]
in summary:

- `attr` is a public attribute, and is set via the `__init__` and `set_props`
- `_attr` is private, and is used internally by methods of the object, and are set usually in `fit`
- `attr_` is public, and is set in `fit`, and not in `__init__`

**Comment by romanlutz** [comment]
#381 is fixing this for postprocessing, after which we should be conforming. Issue #222 will then track the remaining pieces required to get check_estimator to pass.
