### ISSUE TITLE
Support for Equality of Opportunity constraint

### ISSUE THREAD

**Issue by harvineet** [fairlearn/fairlearn#264]
Is there a way to use Equality of Opportunity or True Positive Rate equality constraint?
Any quick change to [ConditionalSelectionRate](https://github.com/fairlearn/fairlearn/blob/master/fairlearn/reductions/_moments/conditional_selection_rate.py#L12) implementation?

**Comment by MiroDudik** [comment]
Yes! The tweak tweak should work:
* `load_data` (line 36) should be receiving the `event` argument similar to the one created in `EqualizedOdds`
* however, after line 42 (that is after the data gets loaded into `self.X` and `self.tags`), you should remove (from both `X` and `tags`) all the rows with Y=0, but do not reindex `X` and `tags`; also store somewhere the indices of the removed rows
* now the `signed_weights` method is only returning the weights over examples with Y=1, but we need to generated signed weights for all the original examples (the examples with Y=0 should receive the signed weights of zero); so after line 113, you need to reinsert zero weights corresponding to the removed examples

**Comment by harvineet** [comment]
Thanks! Will try this and share results.

**Comment by romanlutz** [comment]
#362 addressed this
