### ISSUE TITLE
Performance tests fail in image build stage

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#266]
https://ml.azure.com/experiments/id/737565a7-514b-4dde-9e69-6b2644929eb1/runs/perftest_1579846054_95b06609?wsid=/subscriptions/cecafb73-04ae-4432-9f96-d96925d28058/resourcegroups/fairlearn-automation/workspaces/fairlearnperf&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#logs

**Comment by romanlutz** [comment]
https://github.com/Azure/MachineLearningNotebooks/issues/746 this fix seems to be the way to go...

**Comment by romanlutz** [comment]
Closing this since it was caused by a pip upgrade. If we ever encounter such issues again we can simply pin pip.

**Comment by adrinjalali** [comment]
More like fixing the issue with the upgraded pip rather than pinning pip? pinning pip sounds like a very drastic measure to me :P

**Comment by romanlutz** [comment]
Kind of depends on whether pip breaks something intentionally (as in "this is the way we do things now") or unintentionally (as in "oops, broke this, but version n+1 will fix it again"). In this case we assumed it's the latter, although I don't recall whether we ever figured out if that's true.
