### ISSUE TITLE
Widget needs minimum padding for over-/underprediction charts

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#273]
If the overprediction bars are very large compared to the underprediction bars the label of the underprediction bars (e.g. 0.1%) may be cut off.

![image](https://user-images.githubusercontent.com/10245648/73215241-a2d7cf80-4121-11ea-9ed3-3d62a3e4039b.png)

**Comment by yuanshi4** [comment]
when I was trying to access the dashboard, the user interactive dashboard did not show up, I only see [out]:<fairlearn.widget._fairlearn_dashboard.FairlearnDashboard at 0x7f0206c42cc0>

**Comment by romanlutz** [comment]
@yuanshi4 you opened #484 for that purpose, right? Can we keep the discussion there and follow the steps we outlined? Thanks!

**Comment by romanlutz** [comment]
closing this since the dashboard is moving out of Fairlearn.
