### ISSUE TITLE
Automatic reviewer addition to PRs

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#285]
I've seen this in other repositories, e.g. https://github.com/pytorch/pytorch/blob/master/CODEOWNERS

and we've previously set up the CODEOWNERS file, so this should be possible.

@adrinjalali if you've seen a different way of handling this lmk!

**Comment by adrinjalali** [comment]
yeah that's one approach which some projects take, and it works, especially when the project is kinda massive and it's hard for people to follow all conversations. For the time being, I'm not sure if it changes much in this repo though. That said, I don't see that as a bad process anyway.
