### ISSUE TITLE
SECURITY.md file

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#290]
It seems the `SECURITY.md` file is from the time where `fairlearn` was under the _microsoft_ org. Now that it's not, does it need to be there?

**Comment by romanlutz** [comment]
Great question! We raised this a while back and never really got a good answer. Judging from other projects like https://github.com/dotnet/orleans which are not necessarily in the *microsoft* org, but started off at Microsoft, we don't need it since they don't have it.

@riedgar-ms @vingu @slbird @mesameki any idea?

**Comment by riedgar-ms** [comment]
Might not be necessary, but having a separate channel for security bugs (not that I see how we'd have any) could be wise. One would want controlled disclosure on those.

**Comment by adrinjalali** [comment]
we could have a private mailing list for instance, for those cases.

**Comment by adrinjalali** [comment]
But looking at the other projects in the ecosystem, I'm not sure if you really have to have that.

**Comment by adrinjalali** [comment]
Probably related, the license says:

```
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
```

**Comment by vingu** [comment]
I'm still working with the relevant parties in Microsoft to update it. For now, I hope it doesn't block people from contributing to the repo.

**Comment by vingu** [comment]
After consulting with the OSS advisers in Microsoft, we will keep the current security policy for now. As the fairlearn community continues to develop, we will evaluate the policy again.

**Comment by adrinjalali** [comment]
Thanks for following up on this. Could you please maybe expand on why this is needed, for the rest of us who are not at Microsoft to understand the background?

**Comment by vingu** [comment]
The main feedback is that fairlearn hasn't established as an independent foundation, so we don't have another entity owning it specifically besides Microsoft.
