### ISSUE TITLE
Title copy in WizardReport should vary depending on the disparity metric

### ISSUE THREAD

**Issue by kevinrobinson** [fairlearn/fairlearn#300]
hello!  I think this is a UX bug, but perhaps I'm misunderstanding.  I'll walk through what I see to try to understand if this is an issue or I'm misunderstanding.

### 1. Pick "precision" for a disparity metric
Let's say I want to look at my binary classifier and see how precision changes for sensitive attributes.  I think the root UX issue might be that the title copy is asking how I want to measure "accuracy" which is an overloaded term on this screen where it has a precise technical meaning:
<img width="945" alt="Screen Shot 2020-02-17 at 1 53 59 PM" src="https://user-images.githubusercontent.com/1056957/74681384-43556880-5191-11ea-9f25-5630f859ab04.png">

### 2. Look at model comparisons
This matches what I expect; I see the disparity in precision, which is what I chose.
<img width="959" alt="Screen Shot 2020-02-17 at 1 53 42 PM" src="https://user-images.githubusercontent.com/1056957/74681492-8a435e00-5191-11ea-9231-468afe529e5a.png">

### 3. Look at precision by sensitive attribute
On this screen, the header copy says "Disparity in accuracy," which isn't what I expect.  I care about precision, and have been looking at precision, and looking closer, I realize that the chart is actually showing precision.
<img width="981" alt="Screen Shot 2020-02-17 at 1 53 34 PM" src="https://user-images.githubusercontent.com/1056957/74681527-9af3d400-5191-11ea-8f22-b765ea142454.png">

I think the root issue is using the term "accuracy" in a more informal way, but in this context it already has a precise technical meaning.  If I'm understanding this properly, then one approach could be to rename this "disparity metric" or "focus metric" or something like that.  Alternately, the initial prompt could be "How do you want to measure model performance?" or something that is more generic and doesn't have a specific technical meaning.

Let me know what y'all think! 👍

**Comment by MiroDudik** [comment]
Thanks for catching this--you are right that in those two instances we are using "accuracy" in a generic sense rather than the more specific "accuracy rate". We are currently revising the wizard, so there will be two steps after the selection of sensitive features:
* Accuracy metric (which we should perhaps rename to "Error metric"); in this step the user selects any standard metric of model's predictive performance
* Disparity metric (which we might also rename "Fairness metric", because we have a few that are not disparities); which would quantify the disparities
The single-model view (Step 3) will no longer have the heading that you currently see (so "Disparity in accuracy" will vanish there).

So--I think that we should just change the second step from "Accuracy metric" to "Error metric". Thoughts?

**Comment by romanlutz** [comment]
@mesameki @rihorn2

**Comment by kevinrobinson** [comment]
@MiroDudik Sure!  Yeah, this seems like a normal thing to crop up as products evolve over time :)  I think the revisions you discuss proposed here seem like a good steps to clarify, and if I read right https://github.com/fairlearn/fairlearn/pull/283 aims to address these kinds of revisions to the wizard. 👍

Given the scope of fairlearn is pretty broad, it does seem like the framing that it chooses to present to users about how to think through fairness questions is probably one of its core competencies, even beyond specific audits or visualizations.   So to broaden the discussion a bit, I opened up https://github.com/fairlearn/fairlearn/issues/307 separately, and asked some questions about how you're thinking about evolving fairlearn in relation to the various needs described in your awesome Holstein et al. (2019) paper.

**Comment by kevinrobinson** [comment]
I think https://github.com/fairlearn/fairlearn/pull/405 made the minimal copy change here?

**Comment by romanlutz** [comment]
That's correct! I think that addresses the issue, so I'll close it. Feel free to reopen if there's more.
