### ISSUE TITLE
Question: should we move to numpydoc format?

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#314]
Many libraries use the [`numpydoc`](https://numpydoc.readthedocs.io/en/latest/format.html) format, which is understood by many tools in the ecosystem as well.

Would there be any interest in moving to it instead of what we have?

**Comment by romanlutz** [comment]
We did quite a bit of work to make it somewhat consistent in the current format. @riedgar-ms spent many hours getting this right. When you say "understood" what do you actually mean? Do tools do further processing using docs?

**Comment by riedgar-ms** [comment]
I believe I did try the `numpydoc` format for the ReST strings for a while. It's basically a different set of markup tags to the existing ones we have.

Changing would be nontrivial (we have to edit all of our existing documentation to conform to the new ReST variant, and possibly persuade ReadTheDocs to process it). As @romanlutz asks, what are the specific benefits from this?

**Comment by adrinjalali** [comment]
It's just that the part of the ecosystem I know follows that format and we're all used to it, and people write tools to parse the format and extract information from it. We even have tests in our test suit which make sure all the parameters of a function or a method are documented in the docstring and we can check for the presence of the default values etc. I'm not sure how you could do that for the one we have here right now.

**Comment by riedgar-ms** [comment]
We'd have to investigate, but since this is just the default `autodoc` format (as I understand it), I'd guess that there are similar tools for it. Those are definitely significant benefits which you list, but I think we should make sure that we can't get them with the existing docstrings before we commit to rewriting all of them.

**Comment by riedgar-ms** [comment]
Bump.... this should be part of the wider discussion we're having about documentation. Tagging @MiroDudik and @mesameki for that reason.

**Comment by romanlutz** [comment]
In general, such changes are best addressed as soon as possible, since the amount of work for switching only increases over time. I don't know whether we see enough of a need to allocate time for this (unless there are volunteers, of course). @vingu  FYI

**Comment by adrinjalali** [comment]
I'm really not sure if `autodoc` gives you the options I mention, but for a better understanding of what I mean, you can check the [`sklearn/tests/test_docstring_parameters.py`](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/tests/test_docstring_parameters.py) file as an example.

**Comment by hildeweerts** [comment]
In addition to the previous points, in my opinion, numpy docstrings are also a much more human-readable format than the one that is currently used.

**Comment by MiroDudik** [comment]
I agree with the human-readability comment. As far as I can tell--there are quite a few benefits in switching to `numpydoc` (much of the sklearn ecosystem and beyond use it and it is human readable). The main downside is that our documentation follows a different format and so we'd need to port it. Are there other downsides?

**Comment by adrinjalali** [comment]
It can be a gradual process. We can say whenever a PR touches a docstring, it should port it to numpydoc with whatever standard we choose.

**Comment by riedgar-ms** [comment]
Sphinx doesn't require us to declare upfront which style docstring we're using?

**Comment by adrinjalali** [comment]
You can see how it's rendered already on the PR @riedgar-ms : https://250-133444044-gh.circle-artifacts.com/0/docs/_build/html/api_reference/fairlearn.datasets.html

**Comment by MiroDudik** [comment]
I love the idea of gradually porting the documentation. It seems that sphinx doesn't mind, so I think that we should just do it. @riedgar-ms ?

**Comment by riedgar-ms** [comment]
Being able to convert gradually was my main concern; the benefits @adrinjalali described were very real, but I wasn't enamoured of the prospect of having to convert everything at once.

**Comment by MiroDudik** [comment]
I take it as a yes. So let's do it--can somebody put out a PR to augment our contributor guide to describe our docstring standard and the interim solution?
