### ISSUE TITLE
Tease apart eps in ExponentiatedGradient

### ISSUE THREAD

**Issue by riedgar-ms** [fairlearn/fairlearn#317]
According to @MiroDudik , the `eps` parameter in `ExponentiatedGradient` is used for two slightly different purposes. It should be split into two independent parameters.

**Comment by MiroDudik** [comment]
To clarify: `eps` is used for:
1. defining the constraints, e.g., | E[h(x) | A=a] - E[h(x)] | <= `eps`
2. the extent to which they can be violated at convergence

See the current documentation:
> :param eps: Allowed fairness constraint violation; the solution best_classifier is
>        guaranteed to have the classification error within :code:`2*best_gap` of the best error
>        under constraint eps; the constraint violation is at most :code:`2*(eps+best_gap)`

This is sensible for demographic parity difference and equalized odds difference, but we should separate out this two uses for more generic constraint types.

**Comment by romanlutz** [comment]
#424 addressed the issue (and #443 is adding much needed documentation). Closing the issue accordingly!
