### ISSUE TITLE
Approaches to end-to-end product development

### ISSUE THREAD

**Issue by kevinrobinson** [fairlearn/fairlearn#322]
I'm curious how folks are doing end-to-end development!

I see the different sub-projects within the repo, including the JS test app and how it has a mix of static fixture data and randomly generated values.  This works great for some kinds of changes, but not super well for developing semantically meaningful changes.  Earlier I worked around this by writing a script to process a dataset and output more metrics into a static file in [visualization/test/__mock-data](https://github.com/fairlearn/fairlearn/tree/master/) and then updated [generateRandomMetrics](https://github.com/fairlearn/fairlearn/blob/master/visualization/test/test-page/App.jsx#L36) to read from those new fields.  But this was just hacked-together to understand how the pieces fit together :)

To improve on this, I first tried to see if there ways to develop UI elements within Jupyter.  That would enable using realistic data fed in from Python (as in the demo notebooks).  Installing a local fairlearn package worked on the Python side, but couldn't get this to load updated JS in the visualization folder.  So I looked into the build steps and started trying to see where the problem was.

I changed some localization text within [visualization/FairnessDashboard](https://github.com/fairlearn/fairlearn/tree/master/visualization/FairnessDashboard), ran `build_widget.py` and worked through differences on OSX.  But this didn't update the artifacts in the `static` folder that get bundled with the Python package, and it seems like this is because when it builds [fairlearn/widget/js](https://github.com/fairlearn/fairlearn/tree/master/fairlearn/widget/js) that project is pinned to a specific published version of the `fairlearn-dashboard` npm package.

So I backed up and tried to use `npm link` to build [fairlearn/widget/js](https://github.com/fairlearn/fairlearn/tree/master/fairlearn/widget/js) with the local modified copy of `fairlearn-dashboard`, but I can't get that working.  I can share more specific error messages (some around not being able to `npm install` because of plot.ly type defs, and others around that suggest I'm probably not doing `npm link` right since the build process can't resolve `fairlearn-dashboard`).  but I thought this might be a good point to instead ask how others folks are doing this :)

@chisingh it seems like you must have been  https://github.com/fairlearn/fairlearn/pull/283 so thought you in particular might have thoughts on this.  Thanks!

**Comment by MiroDudik** [comment]
Tagging @rihorn2. We should try to resolve this issue within `CONTRIBUTING.md`.

**Comment by rihorn2** [comment]
@kevinrobinson  Thank you for calling attention to this, I've been working on improving the end-to-end testing in our sibling project, interpretML. The blocking issue had been what you encountered, building the jupyter extension package from the typescript required publishing a version of the dashboard to npm (additionally, the dependence on jupyter extensions prevented pip install -e from working, and it was incompatible with databricks notebooks). The work in interpretML has been to move to a local Flask backend that serves the built static javascript files, which allows for locally testing changes in notebook using pip install local in interactive mode (-e). The plan is to move this architecture into fairlearn when all the issues are worked out (there is an issue with databricks that I'm working on currently). 

As for the mock-data, the idea is we can add new data to validate common use cases quickly without needing to set up the notebook and pip install. I'd love to have better test coverage than this, but in the meantime it provides some valuable validation that common scenarios work. Please feel free to add other scenarios, and we can improve the test-page to use precomputed metric values for a given dataset to replace the random numbers (this works well with the work done by @riedgar-ms for calculating metrics for upload).

**Comment by romanlutz** [comment]
As a small improvement to the current process the recent updates I made to `scripts/build_widget.py` automate most of the UX dev process away. https://github.com/fairlearn/fairlearn/commit/a404a058918d233f65e084252d5da2e07ff2dbd0

With this it's basically
1. make changes to UX code within `visualizations`
2. run `build_widget.py` with `--use-local-changes` option
3. `pip install .` 
4. validate that it works as intended

Clearly that's no substitute for tests and a simpler process

**Comment by kevinrobinson** [comment]
@romanlutz ah yeah, I'm aware of that script and the improvements to it, but I think we are talking about slightly different things :)  To try to clarify, let me break the issue into two components, and then connect this to why I brought this up back then, and why I don't think this is worth spending on time on right now.

### a. build_widget workflow
`build_widget` is a production step, it's not optimized for development experience.  On my laptop this takes ~90 seconds, which is slow enough that it impacts the local development workflow.

### b. test app workflow
 There's a `test` folder, which doesn't have tests but a separate JS app that can be used for local development.

Using that approach avoids any Python, but is still configured as a production build so takes almost a minute.  I'm using:
```
% time python scripts/build_widget.py --use-local-changes --yarn-path=/Users/krobinson/.yarn/bin/yarn
(25 seconds)
% cd /visualization/test/test-page
% time yarn add fairlearn-dashboard@"../../FairnessDashboard"
(15 seconds)
% yarn start
(9 seconds)
```

There's also some JS code that mocks the API to Python and provides a mix of static fixture data and randomly generated values.  These randomly generated values is what I'm really trying to get at, and why this is about *end-to-end product development*, and not just about "how do I run the build."

### why i brought this up
When I first started looking at this project, I pulled down the repo and started getting it running, and then was looking around the test app.  I was confused because the visualizations weren't semantically meaningful, and then I discovered that the metrics were being randomly generated.  I understand why this tradeoff makes sense, and how it's particularly helpful for iterating on the visual design elements in the UI.

But it also means you can't use the test app to evaluate UX changes, even for a local demo.  So I wrote a script to grab a dataset, compute the metrics and write them out to `__mock_data` and then updated `App.jsx` in the test app to read those.

As I was doing that, I realized that this was too involved for a prototype, and opened this issue :)

---

Anyway, I'm going to close this issue since it's no longer a priority for me, and from what @rihorn2 said above, it sounds like there might be other internal MS considerations like merging with interpretml and maybe other interop required on the Azure side.  It's hard to evaluate any of the engineering tradeoffs here without any context on the product roadmap, but maybe these notes are helpful for the future.  Thanks! 👍
