### ISSUE TITLE
Add a GitHub Action to test notebooks against the last released Fairlearn version

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#353]
Currently we can break notebooks for the last released version without noticing because we don't actually test against the last released version, but the current master version.

#351  addresses this gap and will tell us that it's failing, so that we can create a new release

**Comment by adrinjalali** [comment]
moving to sphinx generated notebooks and having sphinx run in the CI would fix this though.

**Comment by romanlutz** [comment]
I don't see how. We currently run tests against the master version of Fairlearn as opposed to the last release. How you get your notebook seems like an orthogonal question.

**Comment by riedgar-ms** [comment]
Also, as I mentioned in the PR, I'm not hugely keen on splitting builds between GitHub Actions and ADO. Using Actions to auto-add PR reviewers makes a lot of sense. Splitting our builds (and releases) feels like a headache generator. I'm not so fussed as to which we use, but I think we should use one.
