### ISSUE TITLE
Mismatched labels in Dashboard

### ISSUE THREAD

**Issue by riedgar-ms** [fairlearn/fairlearn#370]
Testing out the v0.4.5 dashboard, I noticed the following when on the model details tab:
![image](https://user-images.githubusercontent.com/28632930/78788983-86a2ab00-797a-11ea-8c0e-8137821f6de3.png)
The large title "Disparity in accuracy" doesn't match the smaller ones (I'd selected precision as the metric to plot).

Shouldn't the large title match the metric chosen for comparing models?

**Comment by kevinrobinson** [comment]
I believe this is a duplicate of https://github.com/fairlearn/fairlearn/issues/300.  https://github.com/fairlearn/fairlearn/pull/283 may be addressing this, I'm not sure.

**Comment by riedgar-ms** [comment]
Agree, this looks like a duplicate of #300 . Since that has prettier pictures, I'll close this

**Comment by kevinrobinson** [comment]
oops actually I think https://github.com/fairlearn/fairlearn/pull/405 did this.
