### ISSUE TITLE
Handle exceptions when relabeling results in single class

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#395]
#### Describe the bug
Our reductions methods relabel samples occasionally, so it's possible that a class (label) is entirely erased, resulting in a single class as opposed to two classes (for binary classification). Certain estimators are unable to handle this and throw and exception. Since this isn't unintended from a Fairlearn perspective we should catch this error and handle it appropriately.

#### Steps/Code to Reproduce
Example with `LogisticRegression` as a representative of classifiers that don't work with a single class.
```python
>>> from sklearn.linear_model import LogisticRegression
>>> LogisticRegression().fit([[1],[2],[3]], [0,0,0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1558, in fit
    " class: %r" % classes_[0])
ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 0
```

Another example with different error message
```python
>>> from sklearn.ensemble import GradientBoostingClassifier
>>> GradientBoostingClassifier().fit([[1],[2],[3]], [0,0,0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py", line 1455, in fit
    y = self._validate_y(y, sample_weight)
  File "~\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py", line 2097, in _validate_y
    % n_trim_classes)
ValueError: y contains 1 class after sample_weight trimmed classes with zero weights, while a minimum of 2 classes are required.
```

#### Expected vs. Actual Results
Fairlearn should just skip fitting in this case and use a classifier that always returns the one remaining class.
We received a `ValueError` in the case above. However, even within `sklearn` the returned error messaged isn't consistent as shown above. For that reason we can't assume that we'll be able to check for those error messages. `ValueError` is too generic to simply catch, either. It may be best to first check for the number of unique classes in `y` before calling `fit`.

#### Versions

System:
    python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
executable: ~\AppData\Local\Continuum\anaconda3\python.exe
   machine: Windows-10-10.0.18362-SP0

Python dependencies:
       pip: 19.2.3
setuptools: 41.4.0
   sklearn: 0.22.2.post1
     numpy: 1.18.1
     scipy: 1.4.1
    Cython: 0.29.13
    pandas: 0.25.1
matplotlib: 3.1.3
    tempeh: 0.1.12

**Comment by riedgar-ms** [comment]
I've noticed something similar in the metrics too - in those cases, `sklearn` writes a warning message, and returns zero.

Checking and substituting a trivial predictor seems reasonable. I think we shoulda lso report this inconsistency to `sklearn` because they might want to add a specific exception.
