### ISSUE TITLE
From scikit-lego to something fair ... and then we heard about this project.

### ISSUE THREAD

**Issue by koaning** [fairlearn/fairlearn#406]
Hi all, 

my name is Vincent Warmerdam and together with Matthijs Brouns (@MBrouns) we've started a project called [scikit-lego](https://scikit-lego.readthedocs.io/en/latest/) a while ago. It's a set of scikit-learn compatible tools that we wanted to open source. It's taken off, we hear it is in production, it has 2K downloads a month and we use sklearn's testing framework to keep all the parts compatible. 

Part of that library contained tools that might make models more fair and a while ago we decided it may be best to have these tools in a seperate package. We figured scikit-fairness might be a nice name. Potentially we could make it part of the official scikit-learn contrib landscape and that would perhaps help more folks consider more fair approaches. So we started working ... preview is [here](https://github.com/koaning/scikit-fairness).

On our side, it is our long term goal to make it as simple as possible for somebody new to scikit-learn to be able to pick up tools for fairness. The project will be heavily tutorial driven and there's been interest from DataKind UK to help create content. Odds are that we prefer simpler tooling that is easier to use over state of the art tooling that requires one to be knowledgeable in the field.

Then somebody on github made us aware of this project. We weren't aware of this effort and since there may be overlap in the goals we figured it'd be good to reach out. We were happy to see other efforts to make scikit-learn compatible tools for fairness but it made us wonder what to do with our own package. 

It might make sense to collaborate, then again it might make sense to have multiple packages for fairness but either way we figured it'd be good to check in. 

So out of wonder; 

1. Are you planning on making fairness-learn something that exists inside of scikit-learn-contrib? 
2. Would you argue that your effort is more industry focussed or academia focussed? 
3. What would you say is the long term goal of your package?

**Comment by riedgar-ms** [comment]
Thank you for reaching out. We are still in a fairly early stage of moving from being a research project to a more general tool, and we have not finalised how we want to fit into the larger ecosystem.

One big source of concern for us is how the issue of fairness is presented in our package (documentation and any other materials) - we do not want to enable so-called 'fairwashing' of ML algorithms.

**Comment by MiroDudik** [comment]
Thanks for getting in touch! Some of the questions about what we want to do with Fairlearn long-term were answered in #311.

Re. industry vs. academia, I'd say that we are looking to enable practitioners (in tech, but also other sectors) to effectively do fairness assessment and mitigation. The field of fair ML is dynamically evolving, so we expect to interact with academic research. Not just the academic research on new algorithms, but also academic research on how practitioners use these algorithms. Some of the people on the Fairlearn team have been involved in that style of research: [Improving Fairness in Machine Learning Systems: What Do Industry Practitioners Need?](https://arxiv.org/pdf/1812.05239.pdf), [Co-Designing Checklists to Understand Organizational
Challenges and Opportunities around Fairness in AI
](http://www.jennwv.com/papers/checklists.pdf). And see also: https://github.com/fairlearn/fairlearn-proposals/issues/2 .

Re. scikit-learn-contrib, we don't have an immediate plan, but it seems worth discussing!

**Comment by romanlutz** [comment]
+1 on previous responses.
@koaning if you're up for it we'd love to discuss this in this week's Fairlearn developer call. It's this Thursday at 8am PST / 11am ET / 3pm UTC / 5pm CEST. Please send me your email address(es) directly on Gitter (just pinged you) and I'll forward the invite.

+ @adrinjalali who may have thoughts on this as well

**Comment by adrinjalali** [comment]
I'd be delighted to see the two teams work together. From the users' perspective, I think it makes sense to have them together, and I believe fairlearn has enough focus on industry which would satisfy @koaning and @mbrouns concerns. I also think having more eyes and ideas on the same package would make it stronger and create a much nicer and more resilient codebase and workflow. It would also move fairlearn towards having a "developer community" which I think would be very beneficial and healthy for the project as well.

On the scikit-learn-contrib, I'd be more than happy to have at least one fairness library there, and I think it's about time. But I wouldn't say it's a necessity. I'm just waiting for these fairness packages to be mature enough so that we can confidently mention them on the sklearn side, either as a "related project" or have them as a project under scikit-learn-contrib.

**Comment by koaning** [comment]
Thanks for the responses all. 

@romanlutz I won't be able to attend thursday because I'll be speaking virtually at a meetup. My collaborator @MBrouns will be able to. Will send both our information via gitter.

**Comment by koaning** [comment]
I'll close this issue for now. We'll start making seperate issues for different components and will slowly start moving them in this direction.
