### ISSUE TITLE
Notebook: Example notebooks aligned with vision whitepaper

### ISSUE THREAD

**Issue by kevinrobinson** [fairlearn/fairlearn#413]
hi pals!

I think that de-abstracting would really help make productive progress on what excellence in a sociotechnical approach to ML would be.  I think looking at the same scenario and talking about it can help the project to confront the core tension in the work: between the mission on one hand, and the realities of who practioners are, what they believe, and what they need on the other hand.  For me, that's the super unique and compelling opportunity here. :)

There are many media to make educational materials, but I think a narrative Python notebook is the best way to confront this tension, because it's closer to where practitioners live (which is not to suggest that notebooks or software are all that matter!).  There are of course many aspects of a sociotechnical approach to fairness that won't fit nicely in there, and attempts at resolving that tension can be super generative!   I also found @hannawallach's comparison to accessibility super compelling.  That work requires both the mission and vision component, but also the tooling that encodes values related to that vision (eg, linter rules that fail the build if you leave out accessibility attributes in your HTML).

There may be early adopter partners who are aligned with the mission aspect of the project, and that may be a source of potential case study topics to make a notebook about.  But there also may be sources that come from the existing culture of data scientists that are not aligned with the mission.  One that I started hacking around on is the Boston housing dataset, since I happened to come upon it earlier in the week and was a bit blown away by how some educational materials approached it.  I started talking about that with @koaning in https://github.com/koaning/scikit-fairness/issues/31, and that might be worth checking out.  I'll put something together and share it in this repo at some point.

But if folks have other ideas of a specific real scenario where we could collectively make the case that there is more to be done to create tooling, process and educational support for fairness as a sociotechnical issue, it would be super helpful if you could share them here. 👍

**Comment by kevinrobinson** [comment]
I also added two issues critiquing two existing notebooks in regards to "fairness is a sociotechnical challenge," and added suggestions for minimal improvements too (https://github.com/fairlearn/fairlearn/issues/418 and https://github.com/fairlearn/fairlearn/issues/419).  While I know those issue may take the minimal suggestions and focus on demonstrating the capabilities of the fairlearn v0.4.6 software package.

So this issue is more about exploring those new different directions, where we see what happens if we center the idea that "fairness is a sociotechnical challenge" :)

**Comment by MiroDudik** [comment]
Thanks for #418 and #419. You're right that we picked them to demonstrate the functionality, and tried to put in a couple of disclaimers to acknowledge that, but we should do it more carefully (and in case of LSAC consider picking a different motivating example altogether). Your critiques make me realize that this was not the best strategy. I wonder about the following approach:

**Comment by kevinrobinson** [comment]
@MiroDudik Sure!  I hear your distinctions between "case studies" and "functionality demonstrations" and I also hear the [discussion on documentation](https://github.com/fairlearn/fairlearn-proposals/pull/8/files#diff-21173c05e65dcf529aa6c8cbc26bf0e9R38) about whether to call things "user guides" or "example notebooks."  In your terminology here I'm trying to talk about "case studies" and in @romanlutz's terminology I'm trying to talk about "example notebooks."

@MiroDudik I hear that you plan to talk with some Azure customers in financial services and revise the "functionality demonstration" related to approving credit card applications, so will check that out when you do!  👍 

Within the scope of this issue, my impression at this point is that while folks on the team may think that "fairness as a sociotechnical challenge" is sort of an interesting aspiration, right now there's not alignment for collaborating on more substantive work in that direction.  I'll keep following along, and feel free to @ me if other ways to collaborate come up down the line.

Thanks for sharing your work in the open! 😄

**Comment by hannawallach** [comment]
Wait hold on. I haven't read all details on both of the issues you opened, @kevinrobinson, but I'm worried there's been a misunderstanding here given your comment "there's not alignment for collaborating on more substantive work in this direction." I'd be happy to hop on a call to discuss this. (I suspect that would be faster/less prone to misunderstanding than comments.)

**Comment by kevinrobinson** [comment]
@hannawallach @MiroDudik Sure, apologies if I am misunderstanding and thanks for helping to clarify.  I'm happy to chat and will ping on gitter.

**Comment by kevinrobinson** [comment]
fwiw it's a different technical angle but Deontological Ethics By Monotonicity Shape Constraints ([Wang and Gupta 2020](https://arxiv.org/pdf/2001.11990.pdf)) has an interesting discussion on both the law school admissions context (https://github.com/fairlearn/fairlearn/issues/419) and the credit card application context (https://github.com/fairlearn/fairlearn/issues/418), where it makes some small attempts to connect the technical choices in the paper to the particular sociotechnical context for those deployment contexts.

**Comment by hannawallach** [comment]
Oh interesting! I hadn't seen this paper. I will check it out....

On Thu, May 28, 2020 at 5:51 PM Kevin Robinson <notifications@github.com> wrote:
>
> fwiw it's a different technical angle but Deontological Ethics By Monotonicity Shape Constraints (Wang and Gupta 2020) has an interesting discussion on both the law school admissions context (#419) and the credit card application context (#418), where it makes some small attempts to connect the technical choices in the paper to the particular sociotechnical context for those deployment contexts.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
hanna wallach
http://dirichlet.net/

**Comment by kevinrobinson** [comment]
fyi, I think this paper is super interesting: [Extending the Machine Learning Abstraction Boundary:A Complex Systems Approach to Incorporate Societal Context (Martin et al. 2020)](https://arxiv.org/pdf/2006.09663.pdf):
> Machine learning (ML) fairness research tends to focus primarily on mathematically-based interventions on often opaque algorithms or models and/or their immediate inputs and outputs. Such oversimplified mathematical models abstract away the underlying societal context where ML models are conceived, developed, and ultimately deployed...  we outline three new tools to improve the comprehension, identification and representation of societal context.

And here's a key diagram, with a systems dynamics diagram modeling a lending scenario:
<img width="841" alt="Screen Shot 2020-06-18 at 1 02 31 PM" src="https://user-images.githubusercontent.com/1056957/85051163-26dc3380-b165-11ea-869c-fc628bf9c1cf.png">

which is of course quite complex :)

My two cents is that it's cool to see ML folks integrating these older lines of work, and it's awesome to see more research on new methods for approaching sociotechnical fairness.  At the same time, the approach of adding more complex formal models to address the "framing trap" is a bit of a "formalism trap" :)  This approach probably makes it even more challenging for non-technical folks to design, critique or evaluate the system (eg, causal graphical models or systems dynamics models are very challenging for people to create, revise or use).  If the evaluation point included qualitative feedback from non-technical stakeholders, or from people impacted by the ML system, it might focus on really different things.

To connect this to `fairlearn`, I see this as the kind of thing that would **not** be in a notebook or part of the project, precisely because this is precisely the "formalism trap."  Other approaches to this that might be included in a notebook or the project might be plain language and storytelling methods like [Brown et al. (2020)](https://www.andrew.cmu.edu/user/achoulde/files/accountability_final_balanced.pdf) or [Young et al. (2019)](https://techpolicylab.uw.edu/wp-content/uploads/2019/03/TowardInclusiveTechPolicyDesign.pdf).  To put it another way: I don't think it would have helped improve the conversations today if we had been drawing proper systems dynamics models, as compared to just talking :)  And I think there's also an opportunity to add a paragraph about this in an "alternative approaches" page, where this tradeoff is highlight in terms of abstraction traps, in a way that's short and accessible for a developer audience.

**Comment by romanlutz** [comment]
Very cool! Of course, I got attracted by the diagram and tried to figure out what's going on there first. My conclusion was that it's really hard to understand, so I very much agree with your analysis :-)

Overall, I think we could focus a lot more on including stakeholders. I wonder what forms this could take. Invite people to hear how they'd feel about a proposed AI system? For me this is mostly about "how do we engage with non-technical stakeholders in a way that makes this meaningful and understandable?". So far everyone involved has at least some technical background. Should the goal be to be to get non-technical up to speed to an extent where they can point out gaps in the proposal (not technical details, but assumptions such as "what feels like fairness?", forgotten cases or scenarios that occur in real life, lack of centering on a good user experience overall)? 

Perhaps this isn't something that needs to be addressed right away, but it's something I keep thinking about.

I like your suggestion about including a paragraph about your conclusions. I'm struggling to imagine where it would fit well, and how it could be written in a way that's easily understandable. If you already have an idea I'm curious to see/hear what you have in mind, though!

Thanks for sharing.

**Comment by hildeweerts** [comment]
Thanks for sharing, Kevin! I didn't see this paper before. I was actually thinking about the connection between system dynamics and algorithmic fairness as a potential research direction, it's nice to see there's already some work there. I don't think a system dynamics approach would fall into the formalism trap necessarily; IMO the process of getting all the relevant information is much more valuable than the diagram itself. I think systems thinking can be particularly valuable in identifying undesirable reinforcing feedback loops à la weapons of math destruction. I agree that drawing "proper diagrams" should not be part of fairlearn though!

I don't think we'll be able to cover *all* relevant aspects of an example in a reasonably concise notebook. So I would probably try to focus on ensuring that the described scenario is reasonably realistic and whether our assumptions regarding the impact of different scenarios are correct. We should make sure that the description of the case, potential harms, and any related trade-offs are clear enough for non-technical folks to have an opinion on them. I think this would be a good goal regardless of whether we're actually able to involve stakeholders.

**Comment by kevinrobinson** [comment]
Yeah, this is awesome @hildeweerts @romanlutz! 👍 

@hildeweerts I really agree that this is an awesome line of research, and I'm super glad to see people exploring it!  I really like the Brown et al. (2020) and Young et al. (2019) work as other examples of other ways to engage in those kinds of conversations with a broader range of people.

@romanlutz @hildeweerts Your comments here have super helpful language for framing this work, since I recognize there's a bit of drift in this issue :)  So I think what might be good is to close this issue, and move forward in a more targeted way in the relevant individual issues (eg, https://github.com/fairlearn/fairlearn/pull/492).

This conversation also helped me see that @hildeweerts's comment on:

> We should make sure that the description of the case, potential harms, and any related trade-offs are clear enough for non-technical folks to have an opinion on them

and @romanlutz' question about "where should this live?" are a bit related!  I think the other thing I've been implicitly trying to do here is say... *what if Fairlearn was a place developers new to fairness came to get help in learning and doing the work of approaching fairness as a sociotechnical challenge?*  This is in the spirit that @hannawallach mentioned yesterday and @MiroDudik described in https://github.com/fairlearn/fairlearn/issues/311#issuecomment-592716247.

So to try to help move this forward, but also respect our current bandwidth, I'm going to close this issue out so we can focus on notebook examples.  I'll separately prototype a website that is "for developers, promoting the idea that fairness as a sociotechnical challenge."  This is similar to the idea in the [microrubric for critiques](https://github.com/fairlearn/fairlearn/pull/490).  That way we reduce the chatter a bit in the short term, and when the timing is right, we can use that prototype website as a concrete thing we can react to and critique and decide what might be good to merge into fairlearn.  👍
