### ISSUE TITLE
Assign labels to values in FairlearnDashboard

### ISSUE THREAD

**Issue by wmeints** [fairlearn/fairlearn#425]
![image](https://user-images.githubusercontent.com/1550763/82177036-b4afcf00-98d8-11ea-9a45-14e30b3579c0.png)

#### Is your feature request related to a problem? Please describe.
When I have a categorical feature in my dataset with just numbers, I get just numbers on the dashboard. Now I have to explain those numbers to the viewers of my `FairlearnDashboard`.

#### Describe the solution you'd like
I would like to be able to assign labels to values of my `sensitive_features` so it's clear what we're talking about in the `FairlearnDashboard`.

#### Describe alternatives you've considered, if relevant
I've considered the following options:

* Turning the feature into a `category` type in Pandas. This requires me to include additional 
  preprocessing in my machine learning pipeline, to turn it back into numeric values.

**Comment by riedgar-ms** [comment]
From your question, I'm guessing that you have an `int-string` dictionary, which could be used for the names?

As a work around, could you apply this dictionary to your sensitive feature column in a map operation when invoking the dashboard? That would avoid having to adjust your existing pipeline.

We can look into allowing a user supplied dictionary for the sensitive feature columns; the exact API of the Dashboard constructor does need some reworking.

**Comment by wmeints** [comment]
Ah yes, applying the map before using the dashboard works too.
It would be nice to have it in the dashboard though. Are you taking pull requests for a feature like that?

**Comment by riedgar-ms** [comment]
We welcome pull requests :-)

As I said, we are considering reworking the Dashboard constructor anyway, so that the sensitive features and predictions are handled consistently.

**Comment by romanlutz** [comment]
The dashboard has moved to the `raiwidgets` package and will be removed from `fairlearn` in April. Closing this accordingly.
