### ISSUE TITLE
Make link to docs more visible. 

### ISSUE THREAD

**Issue by koaning** [fairlearn/fairlearn#432]
Often, the documentation of a github project is immediately next to the title. See the example from [here](https://github.com/koaning/scikit-lego).

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/1019791/82582042-bc4dcd00-9b91-11ea-885a-2c612daedc2b.png">

Fairlearn doesn't do that yet, but since it is common on github (and it gets more people to see an overview of the project) I figured it'd be good if the change was made.

**Comment by MiroDudik** [comment]
Good catch. Done.
