### ISSUE TITLE
Microsoft Copyright Notice

### ISSUE THREAD

**Issue by koaning** [fairlearn/fairlearn#433]
When you look at `setup.py` you'll notice these two lines: 

```
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
```

Just to check; does the project intend on keeping the copyright line? It appears in every file.

**Comment by MiroDudik** [comment]
It's because the file was contributed while we were on MSFT payroll--MSFT employees can contribute to OSS projects as long as we put the copyright notice in the source files we create. If you modify the file, you can of course add your copyright notice to the top (but don't need to). Similarly, if MSFT folks modify files initially contributed by others, we're not expected (but can) add the additional copyright notice. I hope this is not an issue--but we should explain this in our contributor guide probably?

**Comment by koaning** [comment]
Since there's an MIT license I suppose that technically, you can still argue for openness. But it is a turnoff. 

Contributing to a file that starts with `Copyright (c) Microsoft Coporation. All rights reserved.` feels like I am using my spare time to contribute to something that is owned by a big company rather than a open source project that I am building with peers. 

Also, side note, the link to the contributor guide on the readme is broken; https://fairlearn.github.io/contributor_guide.html.

**Comment by adrinjalali** [comment]
I agree. There's also the `SECURITY.md` file which I still think should be removed.

**Comment by MiroDudik** [comment]
I see your points--let me consult with MSFT lawyers to get to the bottom of the rationale and see what can be relaxed. For example, would it help if we just kept the copyright notice in the LICENSE file? On a basic level, I'm not sure whether we should be preventing any contributor (e.g., folks from Google, Facebook, or any other corporations) for stating their copyright as long as they keep the MIT license.

I think that we're running into a misconception--but a turnoff nevertheless. The way I understand this, in case of the MIT license, the copyright notice is like stating the authorship and so when somebody copies substantial portions of the code, they need to give credit to the author (just by stating their names as given in the copyright notice). Other than that--everybody is free to do as they please with the code. When you update the code, you become a co-author and you can add your name in the form of the copyright notice at the top.

Re. `SECURITY.md`, I'll try to get some clarity around that as well. Last we heard is that until we have an independent entity, e.g., "a Fairlearn foundation", we should keep `SECURITY.md`. @romanlutz : is that right?

**Comment by romanlutz** [comment]
@vingu was involved in those discussions, but I think you’re right. 

I agree with everything written above. It’s altogether not unusual to have companies holding copyrights, e.g. [angular](https://github.com/angular/angular.js/blob/master/LICENSE) or [Bootstrap](https://github.com/twbs/bootstrap/blob/master/LICENSE). That said, I had the same impression as you. One pattern I found that I like is “copyright X and other contributors” , e.g. [JQuery](https://github.com/jquery/jquery/blob/master/LICENSE.txt) or [Vowpal Wabbit](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/LICENSE). I’ve been trying to get some clarity from folks with more experience in open source licensing to make sure I am allowed to extend copyright to “all contributors” but with MIT license it really shouldn’t matter as Miro wrote. Nevertheless, giving the strange first impression doesn’t do any good either. I’ll push a little harder to get a resolution internally and will update this thread. 

Regarding the lines in every file: you may recall that we’re thinking of the license for documentation (perhaps CC BY) as something different from the license for code (MIT). For clarity it may be beneficial to have it explicitly stated. That’s another point I want to get a definitive answer on, though.

If you have thoughts in the meanwhile please share!

**Comment by hildeweerts** [comment]
I had the same impression as @koaning and it made me hesitant to contribute to the project. In addition to the turnoff of providing 'free labor' to a big company, for me, it also includes the fear of being overruled during decision-making.

**Comment by MiroDudik** [comment]
We've been kicking the governance issue down the road until we're bigger, but it's obvious that this needs addressing now... it also came up in the last [developer call](https://github.com/fairlearn/fairlearn/blob/master/docs/community/developer_call_notes/2020_05_07.rst).

**Comment by slbird** [comment]
For the security.md, the reason we put the MS one there is for the benefit of the FairLearn community.  We spoke with our security experts and they recommended that you should have a channel to communicate security vulnerabilities that isn't posting them publicly, and MS agreed to do it for this project in absence of an alternative. We would be very happy to update it to another process if we have proposals.

**Comment by MiroDudik** [comment]
Re. `SECURITY.md`--so it sounds like this might be solved by setting up a secure e-mail account that forwards to maintainers?

**Comment by slbird** [comment]
I think generally yes but we should confirm if there's any other functions we'd want to add. I think also they recommended a process to notify people that use FairLearn that might have been exposed as a result of an issue.

**Comment by romanlutz** [comment]
We have both an “internal”/“private” contributor mailing list (read: only accessible by subscribed contributors) and a newsletter through python.org (thanks to @adrinjalali who suggested it). Sounds like they fit both these functions:

- reporting to internal list
- announcements to newsletter 

Note: we haven’t used either of them yet, so you haven’t missed out on anything!

@slbird does that make sense?

**Comment by adrinjalali** [comment]
> I think also they recommended a process to notify people that use FairLearn that might have been exposed as a result of an issue.

That's generally needed if there's any sort of SLA or a contractual agreement or something between the parties. Software which comes with an MIT license, very clearly states:

> 
>     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
>     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
>     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
>     AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
>     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
>     OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
>     SOFTWARE

I'm happy to simply have an email address or something dedicated to security issues, but I don't think it's really needed. It can also be simply a line on the README saying, please report security issues to this email address/web page/etc.

With regards to the copyright notice, sure a lot of projects do that, but that's no the only way to do it. It's true that for many larger projects which are mostly owned by a company that's how it's done, but you could also have a "funding" place instead and recognize who supports the project like the one [here](https://scikit-learn.org/stable/about.html#funding).

**Comment by koaning** [comment]
I'm seeing a PR with activity on this topic which I'm thankful for. Gotta ask though ... what did the lawyers say about the topic?

**Comment by romanlutz** [comment]
There are various topics discussed above, and we haven’t found a resolution for all of them yet. Regarding copyright they said that we can extend it towards contributors so I made that change. The remaining points need further discussions, and we’re on it. Thanks for your patience!

I think @adrinjalali ’s point regarding funding is valid, too. It’s just a unique situation for Microsoft right now and there are a few things we need to iron out for that. Will keep you posted as soon as I know more.

**Comment by romanlutz** [comment]
Thread summary:
- add a funding page to highlight which institutions supported contributors
- SECURITY.md is gone
- update from outside this thread: copyright for new files is only for "Fairlearn contributors", but no longer Microsoft.

I feel like the funding page should be it's own separate issue, and the other two are completed with no further action required. With that in mind I'd suggest closing the issue. Thoughts? @fairlearn/fairlearn-maintainers

**Comment by hildeweerts** [comment]
Sounds good, @romanlutz. I have opened #888 for the funding page and will close this.
