### ISSUE TITLE
Add links to source code to API reference

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#456]
#### Describe the issue linked to the documentation
It would be nice to be able to quickly navigate from the API reference to the source code on Github.

#### Suggest a potential alternative/fix
I believe scikit-learn uses the sphinx extension linkcode to achieve this.

**Comment by riedgar-ms** [comment]
That would certainly be useful. @adrinjalali , can you comment from the scikit-learn perspective?

**Comment by adrinjalali** [comment]
Yep, we use `linkcode`, and the configuration is pretty easy:

https://github.com/scikit-learn/scikit-learn/blob/master/doc/conf.py
https://github.com/scikit-learn/scikit-learn/blob/master/doc/sphinxext/github_link.py
