### ISSUE TITLE
'GridSearch' object has no attribute 'predictors_'

### ISSUE THREAD

**Issue by marcscho** [fairlearn/fairlearn#459]
Hi

I'm walking through the "Binary Classification with the UCI Credit-card Default Dataset" notebook and get an error **'GridSearch' object has no attribute 'predictors_'** when executing the following code cell after successfully training GridSearch:

`sweep_preds = [predictor.predict(df_test) for predictor in sweep.predictors_]`
`sweep_scores = [predictor.predict_proba(df_test)[:, 1] for predictor in sweep.predictors_]`

Thanks for looking into this :wink:

**Comment by kevinrobinson** [comment]
hi @marcscho!  check out this similar issue, which has some suggestions: https://github.com/fairlearn/fairlearn/issues/448

**Comment by romanlutz** [comment]
Thanks @kevinrobinson for linking! Closing this as duplicate
