### ISSUE TITLE
Image on Landing Page of Documentation 

### ISSUE THREAD

**Issue by koaning** [fairlearn/fairlearn#463]
#### Describe the issue linked to the documentation

Currently, this is the main image on the documentation page: 

![image](https://user-images.githubusercontent.com/1019791/83940251-7aed2c80-a7e3-11ea-997b-d2dd3b94f88b.png)

I think the image communicates a few things well; it's machine learning, there's a sense of gender equality and I think the wheel chair is a nice touch. But as far as fairness goes, I think the image is at risk of doing this project a dis-service by not having folks of different color also represented. The goal here is fairness and fairness towards race will certainly be a theme. The front page is a lot more welcoming to a diverse crowd if the main image also represents a diverse crowd.

#### Suggest a potential alternative/fix

Come to think of it; there's other angles of fairness to consider as well. Age discrimination and sexual orientation come to mind. I am no designer and I woulnd't want to suggest that designing a proper image is easy, but it feels like a missed opportunity to not iterate on the image.

**Comment by riedgar-ms** [comment]
Thanks for pointing this out. We're following up.

**Comment by MiroDudik** [comment]
You're absolutely right... there are a few other issues with images that we're aware of. We need to properly set up licensing of artwork (not covered by MIT license, because it's not code) before we merge the illustration source files into the repo--but once that's in, we'll be able to start iterating on better artwork! (Tagging @mesameki and @hannawallach )

**Comment by hildeweerts** [comment]
Are there any updates regarding the images?

**Comment by mesameki** [comment]
@hildeweerts Thanks for following up. Our designer is looking into this and we came up with a list of action items that we would like to share with the community first. We will provide an update of the timeline and action items in our upcoming session.
