### ISSUE TITLE
Expand Makefile

### ISSUE THREAD

**Issue by koaning** [fairlearn/fairlearn#471]
Different folks have different ways of working but it might help some folks if the Makefile was expanded a bit. 

For example locally I've added this; 

```
commit:
	git commit --amend --signoff
```

This handles the part of the signoff. I also think it'd be nice to add a `check` command that will run pytest/flake8 locally with all the correct configurations as well as a `install` command that installs everything locally for development. I personally also like adding a [help command](https://calmcode.io/makefiles/help-commands.html) that explains what commands are in the file. 

I wouldn't mind making the PR. Just wanted to check what folks think of it first.

**Comment by adrinjalali** [comment]
The Microsoft team doesn't really do `make`, so it's up to us to just expand it, and for now it's been just me. I'm happy to have a richer `Makefile`. For the pre-commit hooks, I rather have a pre-commit hook than having it in the `Makefile` though, so that people on Windows machines could easily use it as well.

**Comment by koaning** [comment]
No problems with a `check`/`install` command?

**Comment by adrinjalali** [comment]
I usually prefer to use `pip install --no-build-isolation -e .` to install, but I definitely wouldn't mind having whatever you like in the makefile. For check I would rather have something like the one you see [here](https://github.com/scikit-learn/scikit-learn/blob/master/.pre-commit-config.yaml). Any reason you don't like it?

**Comment by riedgar-ms** [comment]
The `Makefile` is definitely a contribution from the wider community - Powershell doesn't come with `make` :-)

**Comment by romanlutz** [comment]
Definitely want to echo @adrinjalali and @riedgar-ms 's statements. Feel free to extend however it feels right for you!
Does that resolve the issue?

**Comment by romanlutz** [comment]
OK, looks like this is clear (= please improve/update makefile however you feel is appropriate) and the issue isn't needed anymore. Please reopen if anything else comes up. Thanks!
