### ISSUE TITLE
Documentation needs to be versioned

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#482]
This is something we've wanted from the start and only excluded since it added complexity. #472 shows that this is important.

**Comment by riedgar-ms** [comment]
I'm interested to know how this interacts with tags and branches. We'll need to make sure that our release process conforms to expectations.

**Comment by romanlutz** [comment]
Me, too. I'll start by reading the scikit-learn code that they use for this purpose sometime later this week.

**Comment by adrinjalali** [comment]
There are many ways you can do it. The way it's done in scikit-learn is that the CI pushes the docs to the website for each release branch, i.e. any branch whose name looks like a major release, plus sending master's compiled docs to `/dev`. The release manager sets what `stable` points to, manually, in what you see in step 7 of [this guide](https://github.com/scikit-learn/scikit-learn/blob/master/doc/developers/maintainer.rst), which comes after

> For major/minor (not bug-fix release), update the symlink for stable and the latestStable variable


Buf fix releases simply change the release branch and therefore the docs will be updated for that branch.

You can modify this pipeline to have pushing the docs done half manually (with push of a button somewhere) if you want more control.

I'm happy to talk more about it if things are not clear.

**Comment by riedgar-ms** [comment]
One random thought, this may have to wait until we actually start releasing new versions. After all, the old branches (very old!) and tags (more recent) will not have the up-to-date documentation directories, and hence will not build on CircleCI.

**Comment by adrinjalali** [comment]
My suggestion would be (if human resources allow) is to start setting up the infrastructure which itself is quite a bit of work. With the new release you can then test things much better. I wasn't thinking of having the docs for the older versions that we have, more like setting up things so that we have two versions (last release and the current state), and at the next release that will become three (the existing releases plus what the default branch becomes)

**Comment by romanlutz** [comment]
Sklearn also only has newer versions on the webpage so I don’t see any issues with that.
