### ISSUE TITLE
AttributeError: 'GridSearch' object has no attribute 'predictors_'

### ISSUE THREAD

**Issue by LianaN** [fairlearn/fairlearn#495]
I'm using `sklearn` **0.23.1** and `fairlearn` **0.4.6**. The following [example](https://github.com/fairlearn/fairlearn/blob/master/notebooks/Grid%20Search%20with%20Census%20Data.ipynb) from fairlearn/notebooks fails at line:

`predictors = sweep.predictors_`
 
with the error message:

`AttributeError: 'GridSearch' object has no attribute 'predictors_'`

**Comment by riedgar-ms** [comment]
Did you get the notebook directly from GitHub?

If so, then we unfortunately have breaking changes there. There are [two basic options](https://github.com/fairlearn/fairlearn/tree/master/notebooks#notebooks-and-fairlearn-versioning)
- Clone the repo, which will allow the latest versions of the notebooks to work
- Navigate to the tag corresponding to your installed Fairlearn, and download the notebook there.

We are going to be paying more attention to versioning in future, but that is unfortunately the current situation.

**Comment by LianaN** [comment]
Thanks, @riedgar-ms.
I checked the [release that is tagged with 0.4.6](https://github.com/fairlearn/fairlearn/releases/tag/v0.4.6). In this release, it  should be `predictors = sweep._predictors` instead of `predictors = sweep.predictors_`.
The issue can be closed. Thanks.

**Comment by riedgar-ms** [comment]
Thanks for letting us know that you're unblocked.
