### ISSUE TITLE
Fairlearn widget crashes when run inside of VS code

### ISSUE THREAD

**Issue by rchiodo** [fairlearn/fairlearn#501]
#### Describe the bug

Fairlearn widget will crash when loaded into VS code in some circumstances. 

#### Steps/Code to Reproduce

1. Install VS code
2. Install the ms-python.python extension (it's used for opening notebooks)

Using the notebook in this zip file, opening the notebook and running it will cause a crash in the fairlearn javascript:
[sql_query2.zip](https://github.com/fairlearn/fairlearn/files/4806678/sql_query2.zip)

See this bug on the ms-python.python extension for VS code for more information:
https://github.com/microsoft/vscode-python/issues/12394

It should also be noted that VS code tries to load the fairlearn widget js from http://unpkg.com or http://jsdelivr.net. We're unable to find this js so we load the fairlearn js from the jupyter nbextensions folder. This might be what's causing the problem. JS loaded from the nbextensions folder can sometimes have implicit dependencies upon jupyter JS, whereas JS packaged on the CDN is explicit about those.

#### Screenshots
Here's a screenshot of the console log:

![image](https://user-images.githubusercontent.com/19672699/85179252-5e1a1580-b235-11ea-8cf9-eaec9c87226e.png)

#### Versions

System:
    python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
executable: C:\Users\rchiodo.REDMOND\AppData\Local\Continuum\miniconda3\envs\jupyter\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
       pip: 20.0.2
setuptools: 46.1.3.post20200330
   sklearn: 0.22.1
     numpy: 1.18.1
     scipy: 1.4.1
    Cython: None
    pandas: 0.25.1
matplotlib: 3.1.3
    tempeh: None

**Comment by rihorn2** [comment]
Looked into this, its not related to VS Code or the environment, its a problem of datasize. Its seems at some point over 100,000 rows, the dashboard exceeds maximum call stack. We will look into reworking this with larger datasets in mind. Sorry for the bug, but it may still work in VS code with smaller data set sizes.

**Comment by rihorn2** [comment]
The underlying issue is a call to Math.min. This javascript library function is recursive and fails at about this point. Will add a task and tests to make sure the dashboard avoids using Math.min/max in places that could be large arrays.

**Comment by willgart** [comment]
thanks, I reduced my dataset to less than 100 000 rows for testing and its working now.
right, a recursive formula can be a problem, I hope you'll be able to solve it.

**Comment by romanlutz** [comment]
Assigning this to myself for now since I'm switching the dashboard from ipywidgets to Flask. That alone may not solve all the problems in VS Code yet, but it's a prereq.

**Comment by romanlutz** [comment]
The dashboard is moving to a dedicated package upon the next release (> 0.5.0). I'm closing this issue similar to #639 since we're not making updates in this repo anymore. VS code is on our list for environments we want to support, although I don't have a particular timeline yet.
