### ISSUE TITLE
Interactive dashboard doesn't show on website in examples

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#508]
Neither examples nor user guides can currently use the dashboard. This makes it harder to imagine how it works, but also a maintenance burden. Every time any changes are made to related files we have to update all screenshots.

**Comment by romanlutz** [comment]
I tried a variety of things here already including several sphinx extensions that are supposed to run and capture widget state and display the interactive dashboard in html, but none of them worked. I wasted quite a bit of time figuring out how to debug them, but none of them had any debugging information, so I'm stuck on that front. The next steps could be to 

- contact the creators of the extensions to figure out how to debug them
- read up on `nbconvert` which seems to be part of most of the extensions so there's likely something to do with how it treats the dashboard
- learn more about our dashboard to understand what could be going wrong

However, I'm holding off on this right now until we have clarity on whether the dashboard will even live in this repo long-term. Moving it out of the repo would theoretically make the problem disappear.

**Comment by riedgar-ms** [comment]
> Moving it out of the repo would theoretically make the problem disappear.

... and reappear in a different repo, surely?

**Comment by romanlutz** [comment]
Probably. I’m having a hard time imagining that it’s not relevant at all. 

The “solution” of copy pasting 5000 lines of html every time it shows up in the webpage isn’t really acceptable to me so I’ve put this on hold until I figure out something better. Suggestions are most welcome.

**Comment by adrinjalali** [comment]
Did you end up trying [binder](https://mybinder.org/)? Or whatever equivalent Microsoft Azure has? I thought the idea was to have the dashboards on that platform, and have users go there if they want something interactive. I'm certain with some magic we can have the dashboards in the existing generated examples as well, but I'm not sure if it's a very high priority at this point.

**Comment by romanlutz** [comment]
I haven’t looked at binder yet. Not showing the dashboard on the webpage somewhat defeats the purpose of having the notebooks on the page. The point is to illustrate metrics, visualize trade-offs etc., so if it doesn’t show the example is incomplete.

**Comment by romanlutz** [comment]
I opened #764 for the Binder button and I'm closing this since we don't have an interactive dashboard much longer in this repo, so the need for this isn't really there anymore. Thanks everyone for the input, though!
