### ISSUE TITLE
GridSearch Object has no attribute 'predictors_'

### ISSUE THREAD

**Issue by sagu94271** [fairlearn/fairlearn#514]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-58-eecd0beaf4b3> in <module>
----> 1 sweep_preds = [predictor.predict(df_test) for predictor in sweep.predictors_]
      2 sweep_scores = [predictor.predict_proba(df_test)[:, 1] for predictor in sweep.predictors_]

AttributeError: 'GridSearch' object has no attribute 'predictors_'

**Comment by adrinjalali** [comment]
Thanks for reporting the issue. Could you please also include a [minimal and reproducible example](http://sscce.org/) for us to better diagnose the problem?

**Comment by MiroDudik** [comment]
Please see #495

**Comment by MiroDudik** [comment]
Work-around also described here: https://github.com/fairlearn/fairlearn/issues/448#issuecomment-637667403
