### ISSUE TITLE
Split up requirements file

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#516]
A good example: https://github.com/scikit-image/scikit-image/tree/master/requirements

Goal: right now we direct people to install requirements.txt in many places. That brings a lot of extra packages into an env that one may not particularly care about. Additionally, we want to have tests to validate that Fairlearn works with other ML packages like tensorflow, pytorch, xgboost, etc., so adding all of these to requirements.txt is infeasible. Related to #231 as a prerequisite.

The alternative would be to just do custom installations in the pipeline definition, but then it's harder to point people at a file for an installation on their local machine.

**Comment by riedgar-ms** [comment]
Just noticed that `skorch` has a split requirements file (`requirements.txt` and `requirements-dev.txt`) and reads one of them in for the dependencies for `setup.py`:
https://github.com/skorch-dev/skorch/blob/master/setup.py
This is a pattern we should adopt, so we don't have to maintain things in both `requirements.txt` and `setup.py` (which will inevitably lead to breakages).

**Comment by romanlutz** [comment]
I think we can further split it up, for people who want to build the documentation (sphinx etc.), people who want to run notebook tests (papermill etc.), ...
See the link I posted with the original issue at the top.

The only reason we have requirements.txt be that kitchen sink of everything is because we haven't split it up yet, so that duplication will automatically be solved by splitting it.

**Comment by riedgar-ms** [comment]
The duplication to which I was referring was between `requirements.txt` and `setup.py`. Splitting up the former does not intrinsically fix that.

I'm not sure that further splitting of the `requirements.txt` would be desirable. So long as we can kick out `shap`, `xgboost` and so on from the core developer dependencies, I'm not sure that the remaining differences between 'doc only' and 'full dev dependencies' are great enough to be worth the maintenance hassle. Especially given how 'cheap' new conda environments are.

**Comment by romanlutz** [comment]
Sure, and if we change our mind we can easily revisit this!

**Comment by riedgar-ms** [comment]
I think this particular issue is closed by my commit #535 . As said above, we can open a new issue if that change proves insufficient.
