### ISSUE TITLE
Update dashboard documentation based on new design

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#523]
#### Describe the issue linked to the documentation

With a recent PR (#283 ) the dashboard changed a lot. We need to update the documentation accordingly.

**Comment by adrinjalali** [comment]
or move it out of the repo :P

**Comment by romanlutz** [comment]
That doesn't solve the documentation issue, though. Also raises a bunch of other questions we need to think about more, such as whether it stays within fairlearn or becomes a separate package. I think that's a very separate conversation and one that needs to be discussed in a proposal. Let's keep this one about doc.

**Comment by romanlutz** [comment]
Closing this since we've removed the updates, added a warning to alert users that the dashboard will move out of the repo, and this documentation update therefore isn't required anymore.
