### ISSUE TITLE
Bug in group_summary function of _metrics_engine.py and _group_metric_set.py

### ISSUE THREAD

**Issue by maurominella** [fairlearn/fairlearn#537]
#### Describe the bug

When I call  _create_group_metric_set as indicated online at https://docs.microsoft.com/en-us/azure/machine-learning/how-to-machine-learning-fairness-aml , I get the error 
```
Array y_pred is not the same size as y_true
```
, which is clearly not true because I'm passing same-size arrays for y_true and predictions (or even the same variable!).

Please note that the error says "Array **y_pred** is not the same size as y_true", rather than "Array **predictions** is not the same size as y_true", since the parameter name is **predictions**, not y_pred (as I think it should be in alignment to other functions).

However, if I print **len(y_true)** and **len(y_pred)** at row 133 of **_metrics_engine.py** (in group_summary function), it tells me that y_pred length is 1, rather than the real size I passed, which is the same as y_true.

That function is called by the instruction at row 169 of **_group_metric_set.py**:
>>> gmr = metric_func(result[_Y_TRUE], prediction, sensitive_features=g[_BIN_VECTOR])

where "prediction" is a single element of the predictions array. As a result, y_pred array becomes 1 element long, causing the "not same size" error reported above.

Thanks,

Mauro Minella, mauro.minella@microsoft.com

#### Steps/Code to Reproduce

Simply run the following command, making sure that Y_test and ys_pred array have the same shape.
```dash_dict = _create_group_metric_set(
    y_true=Y_test,
    predictions=ys_pred,
    sensitive_features=sf_dict,
    prediction_type='binary_classification')
```

#### Expected Results

Avoid the error below

#### Actual Results

```
ValueError: Array y_pred is not the same size as y_true
```

**Comment by riedgar-ms** [comment]
Thank you for highlighting this. It looks like this is actually a bug in the sample code on:
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-machine-learning-fairness-aml

Specifically in,
```python
#  Create a dictionary of model(s) you want to assess for fairness 
sf = { 'Race': A_test.Race, 'Sex': A_test.Sex}
ys_pred = unmitigated_predictor.predict(X_test)
from fairlearn.metrics._group_metric_set import _create_group_metric_set

dash_dict = _create_group_metric_set(y_true=Y_test,
                                    predictions=ys_pred,
                                    sensitive_features=sf,
                                    prediction_type='binary_classification')
```
the variable `ys_pred` is supposed to be a `(str,array)` dictionary, where the key is the name of the (registered) model. The code in the [example notebooks](https://github.com/Azure/MachineLearningNotebooks/blob/master/contrib/fairness/upload-fairness-dashboard.ipynb) does this, and should work.

Tagging @mesameki

**Comment by riedgar-ms** [comment]
This is actually a problem on the Microsoft Docs website - the Fairlearn part is actually behaving as expected. I've filed an internal bug to fix the webpage.
