### ISSUE TITLE
Demographic Parity in Grid Search For Regression

### ISSUE THREAD

**Issue by RachitChhaya** [fairlearn/fairlearn#539]
I modified the plot_grid_search_census example notebook given in the Examples Notebook. I want to modify it run it for regression task.  I used fetch_bostaon and LinearRegression instead of LogisticRegression. I also made required changes to train_text_split.  It 
runs fine  till the point 
sweep = GridSearch(LinearRegression(fit_intercept=True), constraints=DemographicParity(), grid_size=71)
However the next command 
sweep.fit(X_train, Y_train, sensitive_features=A_train)
gives the following error
"ValueError: Supplied y labels are not 0 or 1"
However the Mitigation section on the User Guide says that Grid search is available for regression also. Can you please tell me how to use the fit and predict methods for regression.
Thank you

**Comment by riedgar-ms** [comment]
Demographic parity is a constraint for classification problems.  You need to pick a constraint moment suitable for regression, such as bounded group loss.

**Comment by RachitChhaya** [comment]
hi. Thanks for the reply . But doesnot the paper "Fair Regression: Quantitative Definitions and Reduction-based Algorithms" regression version constrained with statistical parity too. Thanks

**Comment by romanlutz** [comment]
That's correct. The existing implementation of `DemographicParity` is for binary classification only, though. I'll convert this into a feature request for DP as a regression constraint.

@MiroDudik does the current workstream with Steven, Leijie, and Mukundh address GridSearch as well?

**Comment by RachitChhaya** [comment]
Thank you
