### ISSUE TITLE
Bank Marketing dataset addition needs documentation review/correction

### ISSUE THREAD

**Issue by parul100495** [fairlearn/fairlearn#544]
#### Describe the issue linked to the documentation

Link: https://github.com/fairlearn/fairlearn/blob/master/fairlearn/datasets/_fetch_bank_marketing.py#L69
The filename and code within suggests that the dataset incorporated is UCI bank marketing dataset. However, the description is incorrect (it is of UCI adult dataset).

#### Suggest a potential alternative/fix

Correction in the documentation/comments of the code.
The dataset is fetched from https://archive.ics.uci.edu/ml/datasets/bank+marketing

**Comment by riedgar-ms** [comment]
Tagging @gaugup

**Comment by gaugup** [comment]
@parul100495 thanks for pointing this out. I will create a PR to fix this.

**Comment by gaugup** [comment]
@romanlutz @parul100495 we could close this issue as the above is merged.

**Comment by parul100495** [comment]
Closing as it is now done. Thanks @gaugup for the quick response :)
