### ISSUE TITLE
'GridSearch' object has no attribute 'predictors_'

### ISSUE THREAD

**Issue by ancibira** [fairlearn/fairlearn#552]
Hi there, I am running the notebook: Binary Classification with the UCI Credit-Card Default Dataset.
When running the gridsearch component I get an error when trying to get the scores. I have made no alterations to the notebook. 

![image](https://user-images.githubusercontent.com/48265599/89964665-2015fc80-dc8e-11ea-979b-1a01feee2409.png)

#### Versions
- OS: Windows
- Browser: Edge
- Python version: 3.7.4
- Fairlearn version: 0.4.6

**Comment by riedgar-ms** [comment]
You may have run into one of our backwards compatibility problems.... did you `pip install` Fairlearn, but download the notebook from the website? If so, then I'm afraid there have been breaking changes (we need to do a new release to fix this, and also provide versioned documentation).

To use the latest notebooks, you need to clone the repository, and install Fairlearn via `pip install -e .`

To use notebooks with the latest Fairlearn release, you need to go to tag `v0.4.6` of the repository, and get the notebooks from that.

**Comment by ancibira** [comment]
Yes I did pip install Fairlearn, but download the notebook from the website. Thank you, I will do as you suggested.
