### ISSUE TITLE
FairLearn does not function in JupyterLab

### ISSUE THREAD

**Issue by Rishit-dagli** [fairlearn/fairlearn#571]
FairLearn does not seem to work in JupyterLab or other custom Jupyter based editors. In a JupyterLab Instance the FairLearn dashboard does not seem to load, and displays-

```
Loading Widgets...
```

However, the same example code works well in a Jupyter Notebook and is able to render the FairLearn Dashboard widget. I also tried updating `ipywidget` which did not seem to solve the problem.

I have also tested with a JupyterLab on Several base OSes, tried using it within a non-GPU instance, and also tried using Colaboratory (based on Jupyter) none of which seems to solve the bug. Thus, I feel this would be a JupyterLab specific issue.

**Comment by romanlutz** [comment]
That's correct, we don't yet support JupyterLab. I'm collecting all that kind of feedback in #484 . JupyterLab has already been reported there so I'll close this issue.

FYI I'm actively working on moving the UI from ipywidgets to flask which should solve this issue. Stay tuned!
