### ISSUE TITLE
Datasets module: keep or remove?

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#583]
As discussed in the [last developer call](https://fairlearn.github.io/contributor_guide/developer_call_notes/2020_09_17.html) I wanted to summarize the discussion around the datasets module so that everyone has a chance to comment including folks who didn't happen to be on that call.

Things to be aware of:
- The module is not part of a released version yet, so removing it would be simple since nobody could be using it yet.
- The reasons for including the module are technical:
  - show how to use a function (create "minimal examples")
  - benchmark algorithms, e.g., how well they optimize fairness/performance trade-off under specific quantitative definitions of fairness and performance
  
  but including datasets means we should address sociotechnical aspects. So far we've only scratched the surface of that, e.g. with the "Notes" and "References" in the [API documentation](https://fairlearn.github.io/api_reference/fairlearn.datasets.html)

- We don't add real functionality, just use functionality from `sklearn.datasets`, namely `fetch_openml`
  - e.g., https://github.com/fairlearn/fairlearn/pull/519
  - potential value prop: we can return sensitive features in addition to X, y
- We have been spending a lot of time discussing this every time a dataset gets added since there are no defined criteria for what gets added and what doesn't, and how much documentation there needs to be.

Options:
1. keep module, define inclusion criteria, and write documentation for each added dataset #507 
2. keep module, but don't spend more time on it until someone is willing to pick up tasks like #507, i.e. don't add more datasets for now
3. remove module, but move educational content into examples (i.e. preserve the documentation on why one needs to be careful with the Boston dataset, for example)

Specifically tagging @koaning and @hildeweerts , but also @MiroDudik @riedgar-ms @adrinjalali @kevinrobinson in case they have more to add. The "default" option would be (2) since that doesn't require any changes.

---

Stating my own opinion separately from the overall description: I'm in favor of (3) since it's just as easy to specify the one line of code that `sklearn` provides, and I'd rather see us spend time on other aspects of fairness. However, I'm mostly interested in settling this debate so that we can move on, so if there's consensus on any of these that's fine by me.

**Comment by koaning** [comment]
It's up to you. My only advice is to consider that it is easier to have people demo the library if the library makes it easy to demo the library. That's why I've always added datasets to my other libraries. Running scikit-learn code to fetch a dataset is a small task, but it is a small task that makes it harder for a novice to get started.

**Comment by romanlutz** [comment]
Good point! I'll take that as a vote towards (1) or (2).

**Comment by romanlutz** [comment]
Given that nobody seems to have anything additional to contribute I take it that we're leaving it as is (option #2 from above). If there's anything additional to consider please reopen. Thanks!
