### ISSUE TITLE
Add random_state to ThresholdOptimizer

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#588]
#### Is your feature request related to a problem? Please describe.

The results of `ThresholdOptimizer` are currently not reproducible. Although `random_state` in `ThresholdOptimizer.predict()` helps to ensure reproducibility in the predictions, running `fit()` twice will result in a different optimizer object (and hence different predictions).

#### Describe the solution you'd like

I'd like a `random_state` argument for the `ThresholdOptimizer` object itself.

**Comment by romanlutz** [comment]
Thanks for reporting @hildeweerts ! I'm a little confused, though. `ThresholdOptimizer` is deterministic except for the `predict` call (which is why the `random_state` is only available there). Small caveat: it assumes the underlying estimator is deterministic. If that's not the case then all bets are off.

Do you have an example where you observe this? I tried a handful of different types of models and couldn't repro it, but that could very well be due to my example being to simplistic.

**Comment by hildeweerts** [comment]
Thanks, Roman! After some further inspection it seems the problem is some confusion on my side on what `random_state` in the `predict` call does. I assumed that if I run a cell that contains ```to.predict(X, sensitive_features=A, random_state=0)``` twice, I would get the same predictions. But that does not seem to be the case?

This is the full code in which I ran in to this problem first:
```python
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from fairlearn.postprocessing import ThresholdOptimizer

# fetch data from OpenML
data = fetch_openml(data_id=42193)
X = pd.DataFrame(data['data'], columns=data['feature_names']).drop(columns=['race_Caucasian', 'c_charge_degree_F'])
y = data['target'].astype(np.int)

# split the data in train-validation-test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=0)

# Train a simple logistic regression model
lr = LogisticRegression(max_iter=1000, random_state=0)
lr.fit(X_train, y_train)

# Train threshold optimizer
to = ThresholdOptimizer(estimator=lr, constraints='equalized_odds', grid_size=1000)
to.fit(X_train, y_train, sensitive_features=X_train['race_African-American'])
```

My expectation was that running the following cell twice would give the same results, but I get different predictions each time:
```python
# score groups
y_val_pred = to.predict(X_val, sensitive_features=X_val['race_African-American'], random_state=0)
```
I'm running this in a Google Colab with fairlearn version  0.4.6.

**Comment by romanlutz** [comment]
Your assumption about how this should work is correct! 
I can repro the issue
```
>>> to.predict(X_val, sensitive_features=X_val['race_African-American'], random_state=0)
array([1, 0, 0, ..., 0, 0, 1])
>>> to.predict(X_val, sensitive_features=X_val['race_African-American'], random_state=0)
array([0, 0, 1, ..., 0, 0, 1])
>>> to.predict(X_val, sensitive_features=X_val['race_African-American'], random_state=0)
array([0, 0, 0, ..., 0, 0, 1])
>>> to.predict(X_val, sensitive_features=X_val['race_African-American'], random_state=0)
array([0, 0, 0, ..., 0, 0, 1])
>>> to.predict(X_val, sensitive_features=X_val['race_African-American'], random_state=0)
array([0, 0, 0, ..., 0, 0, 1])
>>> to.predict(X_val, sensitive_features=X_val['race_African-American'], random_state=0)
array([0, 0, 0, ..., 0, 0, 1])
>>> to.predict(X_val, sensitive_features=X_val['race_African-American'], random_state=0)
array([0, 0, 0, ..., 0, 0, 1])
>>> to.predict(X_val, sensitive_features=X_val['race_African-American'], random_state=0)
array([0, 0, 0, ..., 0, 0, 1])
>>> to.predict(X_val, sensitive_features=X_val['race_African-American'], random_state=0)
array([0, 0, 1, ..., 0, 0, 1])
>>> to.predict(X_val, sensitive_features=X_val['race_African-American'], random_state=0)
```

Thanks a lot for reporting. I'll dig into this and will update later today!

**Comment by MiroDudik** [comment]
Oh. Excellent catch. @romanlutz we have a bug in lines 112-116 of https://github.com/fairlearn/fairlearn/blob/master/fairlearn/postprocessing/_interpolated_thresholder.py

My suggestion is to replace it by something like:
```python
        random_state = check_random_state(random_state)
        positive_probs = self._pmf_predict(
            X, sensitive_features=sensitive_features)[:, 1]
        return (positive_probs >= np.random_state.rand(len(positive_probs))) * 1
```
(where `check_random_state` is imported from `sklearn.utils`.

By the way, this also reminds me of #243 and https://github.com/fairlearn/fairlearn/pull/282#discussion_r374723526. That should be handled after the above bugfix.

**Comment by MiroDudik** [comment]
Oh--also worth checking how we do it in `ExponentiatedGradient`.
