### ISSUE TITLE
Doc Build Warning

### ISSUE THREAD

**Issue by riedgar-ms** [fairlearn/fairlearn#606]
#### Describe the bug

Running sphinx to build, I see:
```
checking consistency... C:\Users\riedgar\source\repos\fairlearn\docs\contributor_guide\developer_call_notes\2020_10_08.rst: WARNING: document isn't included in any toctree
```

#### Steps/Code to Reproduce

See:
https://app.circleci.com/pipelines/github/fairlearn/fairlearn/1040/workflows/223c2925-34ab-4787-9af7-983c61e3ff6f/jobs/1643
as well

#### Expected Results

We shouldn't be getting a warning...

#### Actual Results

Get the above error

#### Versions
GitHub master branch

**Comment by romanlutz** [comment]
We should be getting that warning actually! The file is not listed in the index file:
https://github.com/fairlearn/fairlearn/blob/master/docs/contributor_guide/developer_call_notes/index.rst

**Comment by riedgar-ms** [comment]
I suspected that sphinx was telling the truth :-) This was a reminder to come back to it once other changes are in.
