### ISSUE TITLE
selection_rate_group_summary not listed in metrics reference page

### ISSUE THREAD

**Issue by chsafouane** [fairlearn/fairlearn#609]
The function `selection_rate_group_summary` is used in the [quickstart page](https://fairlearn.github.io/quickstart.html). Yet, it is not listed in [API reference for the metrics package](https://fairlearn.github.io/api_reference/fairlearn.metrics.html). Actually, none of the functions `selection_rate_*` are listed in the API reference page. 

Is there a reason for this ? And if no, would it possible to add them, please ?

**Comment by chsafouane** [comment]
And why does it take `y_true` and `y_pred`? Is it for API consistency ?

**Comment by chsafouane** [comment]
A second question comes to mind, why is it that `selection_rate` takes both `y_true` and `y_pred` ? I believe it's done only for API consistency and to be able to pass it to functions like `group_summary` and it uses only `y_pred` for the calculation. If that's the case, I believe it would be good to mention this in the documentation of `selection_rate`

**Comment by riedgar-ms** [comment]
Metrics are all about to change a lot.

You are right that `selection_rate()` requires `y_true` as well for API consistency. In the metrics update I'm working on now, the fact that `y_true` is ignored is mentioned.

**Comment by chsafouane** [comment]
Thanks for your answer, glad to know this
