### ISSUE TITLE
ExponentiatedGradient needs comprehensive tests

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#61]
The current set of tests is too limited. We need to extend that asap.

UPDATE: argument tests are now there thanks to @riedgar-ms but we still need functional tests

**Comment by riedgar-ms** [comment]
Subtask - #316

**Comment by romanlutz** [comment]
@riedgar-ms I've committed a PR for this, but won't get to more for the next few weeks. If you want to wait for this with a release, your release may not happen for a long time...

**Comment by romanlutz** [comment]
This is represented through #316 so closing this issue
