### ISSUE TITLE
DemographicParity init parameters

### ISSUE THREAD

**Issue by chsafouane** [fairlearn/fairlearn#610]
The API reference page for [fairlearn.reductions](https://fairlearn.github.io/api_reference/fairlearn.reductions.html#fairlearn.reductions.DemographicParity) indicates that DemographicParity can take multiple parameters when instatiating and the [code on github](https://github.com/fairlearn/fairlearn/blob/master/fairlearn/reductions/_moments/utility_parity.py#L224-L248) indicates that it does as its base class is `UtilityParity`. Yet, when I try to execute the line instantiating dp in the example in the [user guide](https://fairlearn.github.io/user_guide/mitigation.html)  `dp = DemographicParity(difference_bound=0.01)`, I get this error
`TypeError: __init__() got an unexpected keyword argument 'difference_bound'`.

I installed the package using both pip and conda and in both cases, I get the same error. Is there anything I'm doing wrong ? If it's not the case, where would the problem possibly come from ?

**Comment by riedgar-ms** [comment]
It's been a long time since the last release, and we don't have versioned docs. I believe you've come across one of the places where the docs are far ahead of the PyPI installed version. Does it work if you install Fairlearn from git?

**Comment by chsafouane** [comment]
After installing the package directly from github, the example in the user guide works as a charm. Thanks
