### ISSUE TITLE
cannot import name 'MetricFrame'

### ISSUE THREAD

**Issue by shoresh57** [fairlearn/fairlearn#619]
ImportError                               Traceback (most recent call last)
<ipython-input-316-af1d762958be> in <module>
     17 
     18 # Metrics
---> 19 from fairlearn.metrics import (
     20     MetricFrame,
     21     selection_rate, demographic_parity_difference, demographic_parity_ratio,

ImportError: cannot import name 'MetricFrame'

**Comment by violazhong** [comment]
![Screen Shot 2020-11-03 at 3 51 27 PM](https://user-images.githubusercontent.com/11827679/98039267-722d7080-1dec-11eb-8bab-a88e7dbd4861.png)
@shoresh57 I encountered the same issue here. Would you like to tell me if you have resolved this issue? If so, how?

**Comment by shoresh57** [comment]
@violazhong 
if you installed with pip then it is not working , you should clone git repo : git clone https://github.com/fairlearn/fairlearn.git then it is working but you maybe face another challenge which is widge that you cannot see dashboard fairlearn ,for that part I just upload dashboard to azure ml with the help of this document and everything worked well https://docs.microsoft.com/en-us/azure/machine-learning/how-to-machine-learning-fairness-aml
