### ISSUE TITLE
MetricFrame: missing error message

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#633]
#### Steps/Code to Reproduce
![image](https://user-images.githubusercontent.com/10245648/98857843-7bce5e00-2414-11eb-8ed8-1b123440f733.png)

```
from fairlearn.metrics import MetricFrame
from sklearn.metrics import balanced_accuracy_score
MetricFrame(balanced_accuracy_score, [1], [1], sensitive_features=[0])
```

#### Versions

System:
    python: 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\<alias>\Anaconda3\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
    Cython: 0.29.15
matplotlib: 3.2.2
     numpy: 1.19.0
    pandas: 1.0.5
       pip: 20.0.2
     scipy: 1.4.1
setuptools: 45.2.0.post20200210
   sklearn: 0.23.1
    tempeh: 0.1.12

**Comment by riedgar-ms** [comment]
That would be `numpy.squeeze()` converting one element arrays to scalars. To be helpful.

**Comment by riedgar-ms** [comment]
From @MiroDudik , it appears that [Numpy have a routine to undo this damage](https://numpy.org/doc/stable/reference/generated/numpy.atleast_1d.html).
