### ISSUE TITLE
citation info, bibtex

### ISSUE THREAD

**Issue by hbaniecki** [fairlearn/fairlearn#641]
Hi, great work with the package, especially the interactive dashboard.
Is there any citation info for the software, or a Bibtex to copy?
https://github.com/fairlearn/fairlearn/search?q=citation

**Comment by riedgar-ms** [comment]
For the entire package, there is a whitepaper:
https://www.microsoft.com/en-us/research/uploads/prod/2020/05/Fairlearn_whitepaper.pdf
The two main techniques have papers:
https://arxiv.org/pdf/1803.02453.pdf
https://papers.nips.cc/paper/6374-equality-of-opportunity-in-supervised-learning.pdf

I'm not sure of where to get a standardised BibTeX format for these.... @MiroDudik ?

**Comment by hbaniecki** [comment]
Thanks

**Comment by riedgar-ms** [comment]
@MiroDudik just sent this:
```
@techreport{bird2020fairlearn,
author = {Bird, Sarah and Dud{\'i}k, Miro and Edgar, Richard and Horn, Brandon and Lutz, Roman and Milan, Vanessa and Sameki, Mehrnoosh and Wallach, Hanna and Walker, Kathleen},
title = {Fairlearn: A toolkit for assessing and improving fairness in {AI}},
institution = {Microsoft},
year = {2020},
month = {May},
url = "https://www.microsoft.com/en-us/research/publication/fairlearn-a-toolkit-for-assessing-and-improving-fairness-in-ai/",
number = {MSR-TR-2020-32},
}
```

**Comment by hbaniecki** [comment]
Will use

**Comment by Dref360** [comment]
I find it complicated to find this information on the website.

1. Go to fairlearn.io
2. Click on API Docs
3. Click on "About"
4. Find the section https://fairlearn.org/v0.6.0/about/index.html#citing-fairlearn
