### ISSUE TITLE
The future of DCO / contributor license agreements in the Fairlearn project

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#650]
As far as I had understood we needed some form of agreement from contributors to contribute. If that's not the case then this is a very simple discussion thread.

The DCO currently introduces a lot of friction. I do not know of a single contributor who got this done from the start without issues. It also regularly trips me and other experienced developers up.

@adrinjalali @hildeweerts @MiroDudik @riedgar-ms wdyt?

**Comment by riedgar-ms** [comment]
It would be good to know the original legal reasoning, since I agree that the friction produced is painful.

**Comment by adrinjalali** [comment]
If we're making fairlearn an independent entity, does it matter what the original reason was? I would understand if Microsoft would require Microsoft employees to have the DCO signatures in their commits, but as the fairlearn entity, there's no DCO requirement to contribute to an MIT Licensed project.

**Comment by adrinjalali** [comment]
I'll reach out to one of the OSI members and ask if they have relevant documents, but we do have all those MIT and BSD licensed projects out there that don't require a DCO. I've only seen it if there's one single commercial entity behind a project.

**Comment by riedgar-ms** [comment]
> If we're making fairlearn an independent entity, does it matter what the original reason was? I would understand if Microsoft would require Microsoft employees to have the DCO signatures in their commits, but as the fairlearn entity, there's no DCO requirement to contribute to an MIT Licensed project.

I have a memory that HDF5 ran into trouble because they couldn't dot all i's and cross all t's on who had made code contributions. Having said that, I don't remember the details. Personally, I agree that for a public project on GitHub, it is unlikely that anyone could be able to assert IP rights retroactively. It would just be nice to know whether there was a particular reason for the DCO requirement, or if it was simply a commercial lawyer being paranoid.

**Comment by adrinjalali** [comment]
Seems like people put a DCO in place to not have to deal with potential cases against the company if somebody submits some code which breaks some copyright law. In my experience from other projects, for fairlearn that would really not be a probable risk.

On the other side, DCO is a point of friction which is counterproductive to attracting more contributors from the community.

So in the interest of the community and having a very low level of risk regarding copyrighted code, I'd say we can just remove it, and add it if at some point in the future we think it's necessary.

**Comment by romanlutz** [comment]
Couldn't agree more with @adrinjalali on this. I've put it on the agenda for Thursday's community call. Unless someone objects let's remove it once the governance PR by @MiroDudik is completed.

**Comment by adrinjalali** [comment]
We also had a meeting with an open source lawyer organized by NumFocus, and I did raise this question. Her assessment was that companies sue companies cause it's worth it, but if the project is organized by individuals, they're too small of a cake for them to get anything worthy out of, therefore the probability of getting sued goes down drastically.

Also, this is only important and relevant for major contributions. The fixes, website improvements, small doc improvements, etc are of no risk, and for the major ones, we can and should of course either trust the contributor or ask if we're allowed to use the code, if there is any suspicion. I personally have been in a situation where I had to contact the author of an implementation to ask if I'm allowed to look at their code, and in that case I wasn't given the permission, so had to implement from the paper itself. But we don't need a DCO for that, we just need to be aware of these cases.

**Comment by romanlutz** [comment]
Thanks for elaborating. This is exactly what I wanted to understand. I think that's fair enough. If we want to add major contributions we can just ask the author to explicitly agree. I don't see that as a big deal, especially compared with the burden we put on new contributors with DCO right now.

**Comment by MiroDudik** [comment]
Fantastic. Let's remove it.

**Comment by romanlutz** [comment]
I just uninstalled the DCO app. Closing this item accordingly, but if against all odds it still requires passing the DCO test please let me know!

**Comment by adrinjalali** [comment]
Woohoo, the brave new world of DCO free contibs
