### ISSUE TITLE
Allow multiple metrics to be passed into plotting functions

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#667]
#### Is your feature request related to a problem? Please describe.
With #561 one can pass in only a single metric. It would be nice to extend that to pass in multiple metrics rather than just one, and plotting all of them in a series of subplots.

#### Describe the solution you'd like
The existing functionality could be extended to take a single metric or a list of metrics. This wouldn't even require an API change (other than the description, of course).

#### Describe alternatives you've considered, if relevant
Alternatively, one could also just call the existing function `n` times. Then you get `n` different plots.

**Comment by MiroDudik** [comment]
I think that there's a simple approach to cover some instances of this: https://github.com/fairlearn/fairlearn/pull/561#issuecomment-825766115

**Comment by romanlutz** [comment]
This is already possible now with the `MetricFrame.by_group.plot.bar` approach shown in #766 . Closing the issue!
