### ISSUE TITLE
Documentation Titles don't match selected version

### ISSUE THREAD

**Issue by riedgar-ms** [fairlearn/fairlearn#697]
#### Describe the issue linked to the documentation

With the versioned documentation, the v0.6.0 documentation has a bad header on its pages:

![image](https://user-images.githubusercontent.com/28632930/107421598-29224200-6ae8-11eb-9ce4-39eda98209f7.png)

#### Suggest a potential alternative/fix

This is probably due to the v0.6.0 tag being at the branch point, rather than the tip of the `release/v0.6.0` branch

**Comment by romanlutz** [comment]
Oh. Can tags be moved? Or what's the proposed fix?

**Comment by riedgar-ms** [comment]
I believe tags can be moved:
http://blog.iqandreas.com/git/how-to-move-tags/
However, we won't find out if it's in the right place until we rebuild the docs... and I believe we can't trigger than manually?

**Comment by romanlutz** [comment]
It's auto-triggered upon check in. There's a way to add another trigger for manual triggering to the YAML, called `workflow_dispatch` but you'd need to get that into the `main` branch at which point it would auto-trigger :-)  It may come in handy in the future, though, if you still want to do it...

**Comment by riedgar-ms** [comment]
After a brief battle with vim, I think that this is fixed. However, we don't know until the next doc build/publish

**Comment by romanlutz** [comment]
I confirmed that it's fixed. Thanks @riedgar-ms !
