### ISSUE TITLE
Order packages in API reference

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#715]
#### Describe the issue linked to the documentation

The current ordering of packages in the API reference seems a bit random to me:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/24417440/112278935-a1515b00-8c83-11eb-801f-63f38c257e8c.png">

#### Suggest a potential alternative/fix

I can see a few options:
* Order alphabetically
* Order based on functionality, e.g.:
   * fairlearn.metrics
   * fairlearn.preprocessing
   * fairlearn.postprocessing
   * fairlearn.reductions
   * fairlearn.widget
   * fairlearn.dataset

My preference would probably be alphabetically, but either is fine with me.

@romanlutz @riedgar-ms @MiroDudik @adrinjalali @mmadaio

**Comment by adrinjalali** [comment]
I'm also happy either way.

**Comment by romanlutz** [comment]
I don't understand the ordering by functionality, since I'd expect dataset to be first, but I don't particularly care about the ordering :-)

It's set in this file https://github.com/fairlearn/fairlearn/blob/main/docs/api_reference/index.rst

**Comment by hildeweerts** [comment]
Haha, yeah, I guess it's a lot more subjective than alphabetically. I was clicking through the website to find some good first issues and I noticed this was a bit strange.

**Comment by mmadaio** [comment]
Happy either way, but +1 for alphabetically
