### ISSUE TITLE
Update "Developer Calls" in Contributor Guide

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#716]
We currently describe Developer Calls in the Contributor Guide, including a link to the notes. 

**EDIT based on conversation below**:
* Change "Developer Calls" to "Community Calls" in Contributor Guide (https://fairlearn.org/v0.6.0/contributor_guide/index.html#)
* Add old developer call notes to HackMD (https://hackmd.io/QcJ8WBAbQTq6iOgoi0JT4g)
* Remove old developer call notes from website (https://fairlearn.org/v0.6.0/contributor_guide/developer_call_notes/index.html#developer-call-notes)
* Add link to HackMD to Contributor Guide.

~~* We should update the text to Community Calls.~~
~~* I don't think we are planning to publish notes of the community calls each week - unless somebody has a good idea to somewhat automate this process? In my opinion, stale content is even worse than no content, so if we don't plan on adding new content we should probably remove the older developer call notes from the website.~~

~~I am not sure about the bigger picture for updating the website content. @MiroDudik is there some sort of to-do list somewhere?~~

@riedgar-ms @MiroDudik @romanlutz @mmadaio @MiroDudik

**Comment by romanlutz** [comment]
Agreed! There's no to-do list other than the usual development process description: https://fairlearn.org/v0.6.0/contributor_guide/development_process.html

In general, you don't need to worry about anything unless the gated pipelines fail since they'd prevent you from merging the PR. If you want to quickly check what the new content looks like you can use the doc build command mentioned [here](https://fairlearn.org/main/contributor_guide/contributing_example_notebooks.html#formatting-of-example-notebooks) but it takes a while when running for the first time.

**Comment by hildeweerts** [comment]
With to-do list I actually meant a list of changes we would like to make to the website content, rather than the development process - but I can totally see why you interpreted it differently, haha.

**Comment by romanlutz** [comment]
Clearly, I'm too much in "checklist mode" these days :-)
I typically favor small changes over big ones (in part because the big ones tend to get stuck at PR stage due to many comments as I regularly demonstrate...) so writing issues for small chunks that need changing actually helps with that.

**Comment by mmadaio** [comment]
Re: community call notes, I've been taking notes on our weekly calls [here](https://hackmd.io/@mmadaio/meeting-notes/edit), but we should probably move those onto something on GitHub if we want to make them more accessible and/or collaboratively editable

**Comment by romanlutz** [comment]
@mmadaio I thought to have them editable collaboratively they needed to be on hackmd? We tried using the Wiki here, but it certainly doesn't have the same real-time edit functionality.

**Comment by hildeweerts** [comment]
@mmadaio @romanlutz I think the main question is: what would be the goal of putting them on the website? 

If the goal is to give people an idea of the kind of topics that are discussed, a paragraph on the website will also do. If the goal is for the community to make it easier to retrieve previous discussions, I'm not sure if it matters a lot whether it is on the website or in a hackmd (at least for those who have previously attended a call). If the goal is to keep us accountable, it makes sense to put them on the website but in that case they should probably be polished which can cause a lot of overhead. I'm not sure if that makes a lot of sense given the current level of maturity/scale of the project.

Thoughts?

**Comment by adrinjalali** [comment]
One of the purposes of having the notes is for an outsider to understand what happens in the community, and for that I don't think it matters where we put things.

**Comment by romanlutz** [comment]
Agreed. I don't think anyone has the time to polish the notes. I did that the first few months and it wasn't really worth the overhead. How about we take the notes that are on the webpage already, put them into @mmadaio 's hackmd, remove them from the website, and link to @mmadaio 's hackmd for those interested in the notes?

**Comment by vamsidesu5** [comment]
Hey I'm new and would love to contribute to this project - would like to pick this issue up!

**Comment by hildeweerts** [comment]
Hi @vamsidesu5, welcome to the project! I have assigned the issue to you. Do you have enough information to get started? Please let us know if you have any questions.

**Comment by vamsidesu5** [comment]
Yup going through codebase now and trying to understand where to make edits! Where's the best place to ask any questions? On this issue or in Gitter?

**Comment by vamsidesu5** [comment]
@hildeweerts Hey I'm running into this issue when pushing to git, any permissions need to be changed for me:
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/24753774/114477775-d25de500-9bca-11eb-8bb1-b8efaff55ef7.png">

**Comment by romanlutz** [comment]
@vamsidesu5 if the questions are related to this topic/issue then this is the best place :-)
If they're unrelated then it depends:
- if it's something that might be generally useful (even to other contributors or users) then perhaps a ["discussion"](https://github.com/fairlearn/fairlearn/discussions) is the best place
- if it's probably specific to your situation then Gitter might be best

The error you encountered is a common one and related to our [dev process](https://fairlearn.org/v0.6.0/contributor_guide/development_process.html#development-process). Essentially, the `fairlearn/fairlearn` repo is access-restricted, so everyone works off of their own fork and creates pull requests from their fork to the `fairlearn/fairlearn` repo. If you have questions about this process I'd be happy to help you out, just let me know.

**Comment by vamsidesu5** [comment]
@romanlutz @hildeweerts Thanks for all the help - updating code now and will make a PR soon!

**Comment by vamsidesu5** [comment]
@romanlutz @hildeweerts I made the edits, but I want to be able to test the website. Is there any command I can run locally to see how the website looks with the changes?

**Comment by vamsidesu5** [comment]
Here is the current PR: https://github.com/fairlearn/fairlearn/pull/745

**Comment by romanlutz** [comment]
@vamsidesu5 Great question! This command should build the website locally: `python -m sphinx -v -b html -n -j auto docs docs/_build/html`
Then you can look into that directory at the end of the command and open the pages you care about. In your case I think that would be the contributor guide. This command is a bit of a shortcut compared to what the build pipelines are running since they need to build the webpage for all previously released versions, too, not just for the `main` branch. But that shouldn't really matter in this case, so I'm sure this will be sufficient (and much faster to iterate!).

**Comment by hildeweerts** [comment]
@romanlutz I think it would be great if we can put those instructions in the contributor guide!

**Comment by vamsidesu5** [comment]
Completed - going to close issue now!

**Comment by romanlutz** [comment]
@hildeweerts merged the corresponding PR in, so I'll close this issue. Thanks a ton, @vamsidesu5 !
