### ISSUE TITLE
Improve consistency of reference format in documentation

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#719]
#### Describe the issue linked to the documentation

The usage of references in the documentation is inconsistent.
* In `ThresholdOptimizer` a reference is linked as a clickable *name (year)* in the **Notes**.
* Functions and classes in the reductions module (`DemographicParity`, `EqualizedOdds`, `ErrorRateParity`, `Moment`, `TruePositiveRateParity`, etc.) link the reference as a clickable *name (year)* in the **description**.
* In `GridSearch` the reference is linked as a clickable *name (year)* in the **description**.
* In `fetch_boston()` in the dataset module the **References docstring** is used, 
* In `fetch_adult()` and `fetch_bank_marketing()` in the dataset module the reference (including the full url and explicit 'Source:') is in the **description**. 

#### Suggest a potential alternative/fix

I'd suggest to follow the [docstring guide](https://numpydoc.readthedocs.io/en/latest/format.html) and put proper references in the *References* (i.e. not just links, as they might break).

[Adapted from larger issue #601]

**Comment by enharten** [comment]
I would like to work on this!

**Comment by hildeweerts** [comment]
That is awesome, @enharten! I have assigned the issue to you. Please feel free to ask questions if anything is unclear.

**Comment by enharten** [comment]
Thanks @hildeweerts!

Should anything be done with the **Notes**? For example, in `ThresholdOptimizer`, should the note be removed, or shortened to not include a link since there will be a link in the **References**? Other?

**Comment by hildeweerts** [comment]
@enharten: I got an e-mail notification with a question from you but I don't see here on Github - do you still need some clarification?

**Comment by enharten** [comment]
@hildeweerts I don't know why I naively thought that you wouldn't see it; I thought better of my question. I'll submit a PR shortly

**Comment by hildeweerts** [comment]
No worries, it was a good question - but great to hear you figured it out 👍
