### ISSUE TITLE
Add links to user guides from API pages

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#730]
I needed to use the `MetricFrame`, so I duckduckgoed `fairlearn metricframe`, which pointed me to the API page [here](https://fairlearn.org/v0.5.0/api_reference/fairlearn.metrics.html). Then I was expecting to easily find a section with some example code which I could copy/paste/adapt for my use-case, but it's not available.

I think it'd be nice to have links to user guides and example notebooks from the API pages, or even have short examples on those pages, so that users can adapt fairlearn functionality much easier.

**Comment by hildeweerts** [comment]
Agreed! I've always liked that scikit-learn consistently adds a "Read more in the User Guide." link at the bottom of the description.

**Comment by kurianbenoy** [comment]
Can I work on this issue? As a first level, we can add a link at the end of each section to point read more in User Guide and Example Notebooks. After which we can add individual examples in places were it's required

**Comment by hildeweerts** [comment]
Sounds good, @kurianbenoy! Let us know if you need help finding the appropriate section in the user guide for each class/function.

I think we can split this up into several issues, at least one for links to the user guide and another for adding examples. Could you open a new issue for adding examples, @kurianbenoy? You can link the current issue in the description.

**Comment by kurianbenoy** [comment]
Please do unassign me from this issue @hildeweerts

**Comment by hildeweerts** [comment]
Thank you for the heads up, @kurianbenoy!

**Comment by romanlutz** [comment]
That sounds great @alliesaizan ! Go ahead! 🙂👍🏻
