### ISSUE TITLE
Bugfix Release v0.6.1

### ISSUE THREAD

**Issue by riedgar-ms** [fairlearn/fairlearn#734]
I would like to put out a release (would be v0.6.1) for #727 (and also #662 , if there is agreement on merging that solution). What are people's thoughts on doing this?

**Comment by hildeweerts** [comment]
Sounds good!

**Comment by riedgar-ms** [comment]
If there are no objections, I'd like to go with our current repo state for `v0.6.1` - skipping #662 for now. Please let me know by 0800 EDT on Tuesday (2021-04-13) if you have any concerns. As usual, during a release, there will be some changes made without the usual review delays, as `main` gets its version bumped.

**Comment by riedgar-ms** [comment]
Branch point tagged, branch cut, and PR out (#739) to update `main` for this release. I've also kicked off the _test_ release pipeline for v0.6.1 (which reminds me that that's still MS-only.... we need to fix that).

**Comment by riedgar-ms** [comment]
Turned out that there were two problems:
- Update to `pydata-sphinx-theme` was breaking our docs
- I'd forgotten to update the path to `yarn` in the release pipeline.

PR #740 addresses those. Merged to `main`, being cherry-picked to the release branch (#741).

Also have #739, which updates `main` with the new version and the link from the static page to the versioned documentation.

**Comment by riedgar-ms** [comment]
Published to Test-PyPI:
https://test.pypi.org/project/fairlearn/

**Comment by riedgar-ms** [comment]
Now on PyPI:
https://pypi.org/project/fairlearn/
