### ISSUE TITLE
Create a table with methods/modules and corresponding dependencies

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#736]
We should start having a very clear table, with methods/modules on one side, and dependencies on the other side, for people to have a clear view about them. Currently `postprocessing` has a soft dependency on `matplotlib`. Soon, this will also be true for `metrics` (once the plotting capabilities are merged). Additionally, #466 seems to converge towards `cvxpy` as another soft dependency.

_Originally posted by @adrinjalali in https://github.com/fairlearn/fairlearn/issues/466#issuecomment-815855327_

The table could either live with our installation instructions or on a separate page of our documentation. The installation instructions are currently part of "Getting started", and we may want to avoid adding too many details on that page, hence the suggestion for a "separate page".

**Comment by shimst3r** [comment]
Sounds like a good issue to delve into the source code, I take it. :nerd_face:

**Comment by romanlutz** [comment]
Excellent! Reach out if you have questions 🙂 And if you post a PR it's always great to post it with a screenshot of what the result looks like. Otherwise you basically force the reviewers to build the docs themselves (since our CircleCI build isn't correctly picking up the branch version (see #819).

**Comment by shimst3r** [comment]
Haven’t thought of the screenshot, that’s really good advice. 👍

To make sure I understood the task correctly: I’ll go through functions and methods and document which of them uses external dependencies, correct?

And what’s the difference between a soft and a hard dependency and should I mark them differently?

**Comment by adrinjalali** [comment]
Hard dependencies are the ones included in `setup.py` and are installed with `pip install fairlearn` on a fresh environment (along with their dependencies which we don't care about and don't document).

You don't need to document hard dependencies. And those are the `import` statements you see on top of the files. Soft dependencies are usually ones which are done in a try-except clause or as a part of `importorskip` statement. They are only required if the user uses certain functionalities, but are not installed by default when the user installs the package.

**Comment by shimst3r** [comment]
Got it, thanks @adrinjalali!

**Comment by shimst3r** [comment]
With a bit of thinking, I came up with the following way of identifying the soft imports:

```shell
grep --exclude-dir .venv --include="*.py" -Er "importorskip|^\s{4,}.*import" fairlearn
```

Among a few false positives, this yields

| File                                              | Dependency |
| ------------------------------------------------- | ---------- |
| fairlearn/fairlearn/postprocessing/_plotting.py   | matplotlib |
| fairlearn/test/unit/postprocessing/test_plots.py  | matplotlib |
| fairlearn/test/unit/postprocessing/test_smoke.py  | lightgbm   |
| fairlearn/test/unit/reductions/test_smoke.py      | lightgbm   |
| fairlearn/test_othermlpackages/test_pytorch.py    | torch      |
| fairlearn/test_othermlpackages/test_tensorflow.py | tensorflow |
| fairlearn/test_othermlpackages/test_xgboost.py    | xgboost    |

Is this sufficient or should I check every source file manually due to possible false negatives? :thinking:

**Comment by romanlutz** [comment]
This is consistent with my mental model! We can skip the teat files, of course, so only 1 is left. There are several other PRs that will add matplotlib to the metrics module, so we'll need to keep in mind to update the table then!

**Comment by shimst3r** [comment]
Apart from adding the table to the documentation somewhere sensible, should I also add the necessary `extras_require` to `setup.py`?

**Comment by romanlutz** [comment]
We actually don't want it to be a part of `setup.py` and there's a reason behind having it in a requirements file 🙂 This way you can just specify `pip install -r requirements-customplots.txt` without having to care about the contents. Long-term there is #645 to improve this structure a bit following scikit-learn's approach, but this particular issue here is really only about creating the table in the docs. 

Now the next question is where that "sensible" location in the docs is, of course. I don't see a related section in the website redesign Figma, so I think we need to choose one ourselves. Right now our installation instructions are in the "Getting Started" section, but we should have a more thorough set of installation instructions. In fact, I just saw that we have a doc bug there 🙁 
![image](https://user-images.githubusercontent.com/10245648/125378246-3ebfc000-e343-11eb-9392-f1436b52afb4.png)

So I suppose the best thing to do is to add an installation section to the user guide which includes
- the full installation instructions ("basic" installation, and with extras) as well as the overview table that indicates which methods/modules require which extras (I'm writing this very generically here but it's really just `matplotlib`).
- the existing version migration guide

And then the link from the "Getting Started" should point at that new section, of course instead of the broken `advanced_install`.

@fairlearn/fairlearn-maintainers any thoughts and/or objections? 🙂

**Comment by shimst3r** [comment]
Okay! Now that @hildeweerts gave her thumbs up, I'll go ahead today and work on the PR. :muscle:

**Comment by adrinjalali** [comment]
@romanlutz 

> We actually don't want it to be a part of setup.py and there's a reason behind having it in a requirements file slightly_smiling_face This way you can just specify pip install -r requirements-customplots.txt without having to care about the contents.

I'm wondering if `pip install -r requirements-customplots.txt` is something users are gonna be doing. We're passed the time when users would clone the repo and install from source. They should be ideally `pip install`ing the package, and most people shouldn't be looking at the repo at all.

**Comment by romanlutz** [comment]
I was referring to contributors here because users can already pip install with the corresponding extra. Anyway, there's already another issue #645 to convert all of these into something more like what sklearn has.
