### ISSUE TITLE
Make sure flake8 checks only relevant files

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#751]
From https://github.com/fairlearn/fairlearn/pull/747#issuecomment-821531625:

> Sadly this PR can't be completed since I managed to create a branch with `.py` at the end which means the `.git` folder has a log file ending in `.py` and `flake8` feels responsible for linting it, which results in errors. Wow! Will create a new branch with identical content and better name. Closing this PR

We need to change our CI to make sure `flake8` only checks the relevant files, and not the whole repo folder.

cc @romanlutz

**Comment by romanlutz** [comment]
That would be everything under `examples`, `fairlearn`, and the test directories if I'm not mistaken.
Whoever takes this up may want to look into `flake8` documentation. We have a `setup.cfg` file in the repository's root directory that configures what `flake8` does. Perhaps one can restrict which directories it should consider.

**Comment by bthng** [comment]
Hi @romanlutz am I able to take this up? Was looking at the `setup.cfg` file and one solution is to state the directories that `flake8` should ignore. Would that be an acceptable solution? https://flake8.pycqa.org/en/latest/user/options.html

e.g. in setup.cfg

```
[flake8]
exclude =
   .git/
    build/
    docs/
    notebooks/
``

**Comment by romanlutz** [comment]
That's great! I was thinking about this earlier today and I think that is indeed the best solution. Thanks @bthng !

**Comment by bthng** [comment]
Thank you for the guidance, raised a PR!
