### ISSUE TITLE
MetricFrame and multiple/named sensitive features

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#753]
I was writing an example notebook, and I encountered something which I found strange. Basically, this works:

``` python
multi_metric = MetricFrame(
    {
        "average precision": skm.average_precision_score,
        "roc-auc": skm.roc_auc_score,
        "count": lambda x, y: len(x),
    },
    y_test,
    y_pred,
    sensitive_features=gender_test,
)
```

But this doesn't:

``` python
multi_metric = MetricFrame(
    {
        "average precision": skm.average_precision_score,
        "roc-auc": skm.roc_auc_score,
        "count": lambda x, y: len(x),
    },
    y_test,
    y_pred,
    sensitive_features={'gender': gender_test},
)
```
with error: 

    ValueError: If using all scalar values, you must pass an index

To me this error message is not clear at all, and I have no pandas DataFrames to have any indices in the first place. I don't think we should be failing in this case.

cc @riedgar-ms @MiroDudik 

Here's the whole notebook for reproducibility

<details>

``` python
# %%
# First we need to install the requirements:
# pip install model-card-toolkit scikit-learn matplotlib fairlear pandas

# %%
# Here we have all the imports required to run the rest of the script
import numpy as np
import sklearn.metrics as skm
from numpy.random import RandomState
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.experimental import enable_hist_gradient_boosting  # noqa
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
from fairlearn.metrics import MetricFrame

# %%
rng = RandomState(seed=42)

X_women, y_women = make_classification(
    n_samples=500,
    n_features=20,
    n_informative=4,
    n_classes=2,
    class_sep=1,
    random_state=rng,
)

X_men, y_men = make_classification(
    n_samples=500,
    n_features=20,
    n_informative=4,
    n_classes=2,
    class_sep=2,
    random_state=rng,
)

X_unspecified, y_unspecified = make_classification(
    n_samples=500,
    n_features=20,
    n_informative=4,
    n_classes=2,
    class_sep=0.5,
    random_state=rng,
)

X = np.r_[X_women, X_men, X_unspecified]
y = np.r_[y_women, y_men, y_unspecified]
gender = np.r_[["Woman"] * 500, ["Man"] * 500, ["Unspecified"] * 500].reshape(
    -1, 1
)
X_train, X_test, y_train, y_test, gender_train, gender_test = train_test_split(
    X, y, gender, test_size=0.3, random_state=rng
)

# %%
# Now we train a classifier on the data
clf = make_pipeline(PCA(n_components=4), HistGradientBoostingClassifier())
clf.fit(X_train, y_train)

# %%
# We can finally check the performance of our model for different groups.
y_pred = clf.predict_proba(X_test)[:, 0]
multi_metric = MetricFrame(
    {
        "average precision": skm.average_precision_score,
        "roc-auc": skm.roc_auc_score,
        "count": lambda x, y: len(x),
    },
    y_test,
    y_pred,
    sensitive_features={'gender': gender_test},
)
```

</details>

**Comment by adrinjalali** [comment]
> If you're passing a dictionary,  `_process_feature()` will try to convert the dict to a pandas dataframe using ` df = pd.DataFrame.from_dict(features)`.

I understand why this happens, but from the users' perspective, this is irrelevant. From the users' perspective, there's no reason for one of those variations to work and not the other. We should do the right validations to make sure those odd potential behaviors you mention don't happen, but I don't see why we'd force the user to import pandas when they don't need to, and to me what I have is a completely legit way of working with the `MetricFrame` and comes quite intuitively to me.

**Comment by hildeweerts** [comment]
I don't think they'd need to import pandas, right? in your current code replacing `reshape (-1,1)` by `reshape(-1,)` would solve the issue. Regardless, I agree that this is a pretty intuitive way to define an array and we shouldn't bother the user with it. I was mostly thinking that there's probably a reason pandas does not accept this type of shape directly (but I'm probably being too naive here, lol).

**Comment by adrinjalali** [comment]
> in your current code replacing `reshape (-1,1)` by `reshape(-1,)` would solve the issue.

That's true, which I didn't try, and then `ValueError: If using all scalar values, you must pass an index` is really a misleading error message lol.

**Comment by hildeweerts** [comment]
> then `ValueError: If using all scalar values, you must pass an index` is really a misleading error message lol.

Yeah, it's not very informative lol. Even as a frequent pandas user I am often still confused by some of their error/warning messages(`SettingWithCopyWarning` gets me every time )

**Comment by riedgar-ms** [comment]
So what is the fix we need here? We could certainly do something to address this particular case. However, you then start getting into worrying about whether a vector of length n is the same as an (n,1) array, a (1,n) array or a (1,1,n,1,1,1) array. I'd prefer to delegate that to pandas... perhaps we could put a try/catch around the conversion, so that we can at least be explicit to the user as to what we tried to do, and embed the error from pandas?

**Comment by adrinjalali** [comment]
I think applying a `reshape(-1,)` on everything before passing to pandas would make sense. It doesn't matter what the original shape is, as long as there are only `n` items there.

**Comment by riedgar-ms** [comment]
You mean iterate over the dictionary, check if each value is a numpy array (because it might be a list), and if so call reshape? What do we do if some of the values are lists?

**Comment by hildeweerts** [comment]
There may be a few very specific scenarios in which this could lead to unexpected results e.g., if the user accidentally passes the "wrong" array that happens to be of shape (n/2, 2), they wouldn't receive any notification whatsoever that they actually passed a multidimensional array. I admit this is quite an unlikely scenario, but I like @riedgar-ms 's idea of at least letting the user know we tried to do some conversions.

**Comment by adrinjalali** [comment]
Checking and correcting the number of dimensions is not really something odd. I agree maybe we don't want to do a `reshape` on everything, but doing certain dimension changes is not that odd, eg.:

https://github.com/scikit-learn/scikit-learn/blob/114616d9f6ce9eba7c1aacd3d4a254f868010e25/sklearn/decomposition/_nmf.py#L95

> What do we do if some of the values are lists?

Passing anything to `asarray` or sklearn's `check_array` fixes those inconsistencies. We can either use them or have our own validation which accepts and corrects all those issues. I really don't think changing from `(n, 1)` to `(1, n)` is something we need to warn the user about. Users very quickly get warning fatigue and ignore those warnings.

**Comment by hildeweerts** [comment]
If we limit the reshape to a limited set of straightforward shapes (like the (n,1) and (1,n)), I agree a warning wouldn't be necessary.

Would it make sense to still replace the pandas ValueError message with a more informative one (e.g., a suggestion to check the dimensions of the array)?

**Comment by adrinjalali** [comment]
> Would it make sense to still replace the pandas ValueError message with a more informative one (e.g., a suggestion to check the dimensions of the array)?

Yeah that error really puzzled me. A more verbose message with a suggested solution would probably help.

**Comment by riedgar-ms** [comment]
I'd really rather wrap [the call to `DataFrame.from_dict()`](https://github.com/fairlearn/fairlearn/blob/2d795006c045bdaeab1a22cd1893d5c63d27f099/fairlearn/metrics/_metric_frame.py#L522) in a try/catch block which tells the user exactly what we tried to do, and passes on the pandas error. The whole point of using that call was so that we didn't need to do any processing ourselves.

**Comment by adrinjalali** [comment]
Sure, as long as the error message is clear enough and gives the user a solution, I'd be happy with that.
