### ISSUE TITLE
Unstructured Data metrics (i.e: WER for Text data) in MetricsFrame

### ISSUE THREAD

**Issue by michaelamoako** [fairlearn/fairlearn#765]
#### Is your feature request related to a problem? Please describe.

I would like support for metrics that specifically pertain to unstructured data. For example: 

Speech To Text - Some common metrics used in STT include Word Error Rate (which looks at the difference between the uttered text and the transcribed text). Another example is "sentence error rate" where if _any_ mistakes are made in the transcription, the utterance is given a 1, otherwise 0. 

While these metrics are specifically related to the text scenario described above, it would still be very useful to use Fairlearn to see them disaggregated. 

#### Describe the solution you'd like

These Metrics could either be built into the MetricFrame, or the MetricFrame could support custom metrics for a user's scenario (i.e: the user defines the metric of interest)

#### Describe alternatives you've considered, if relevant

Built a dashboard for these metrics outside of Fairlearn.

**Comment by riedgar-ms** [comment]
You can already give `MetricFrame` a custom metric, so long as it conforms to the `f(y_true, y_pred)` pattern of sklearn (there are examples of this in the documentation, although perhaps not particularly highlighted). So long as `y_true` and `y_pred` are arrays of equal length, the type of the items is irrelevant to `MetricFrame` - it just passes them on to the supplied metric function.

We do know that not all data fit into the tabular model of `MetricFrame`, and we're starting to think about ways to support these scenarios as well.

**Comment by michaelamoako** [comment]
https://github.com/fairlearn/fairlearn/issues/756 highlights this in a more general way
