### ISSUE TITLE
DOC: Measurement modeling - construct validity

### ISSUE THREAD

**Issue by mmadaio** [fairlearn/fairlearn#769]
#### Describe the issue linked to the documentation!
The user guide currently does not include explanations of key concepts from measurement modeling. 

Measurement modeling is a framework from quantitative social sciences, involving a process of measuring theoretical constructs that cannot be observed directly (such as fairness) by making inferences from observable properties.

Because fairness itself is unobservable (and is fundamentally contested), users of Fairlearn need to make decisions about what their theoretical understanding of fairness is, and how they operationalize it via observable properties. At each stage, assumptions are made, which need to be tested. 

Measurement modeling provides a language and a framework for making those assumptions explicit and testing them.

As many users of Fairlearn may not have quantitative social science backgrounds, we need to provide explanations and examples of the process of measurement modeling, including key concepts such as construct validity and construct reliability. This issue is focused on construct validity (to keep the issues smaller and more achievable), but others should include construct reliability.

See [Jacobs and Wallach (2021)](https://arxiv.org/pdf/1912.05511.pdf) for more information.

#### Suggest a potential alternative/fix

Create a glossary explaining key terms from construct validity, with explanations of what they might mean for measuring fairness. Specifically:

- face validity
- content validity
  - contestedness
  - substantive validity
  - structural validity
- convergent validity
- discriminant validity
- predictive validity
- hypothesis validity
- consequential validity

**Comment by shimst3r** [comment]
Measurement and Fairness is still on my desk (and I wouldn't mind reading it again 🥰), do you already have a list of key terms in mind? I'd be interested in collaborating on this issue, but I lack the STS background (at the moment).

**Comment by romanlutz** [comment]
@michaelamoako just created #771 today as well. Would be great if the three of you (@shimst3r , @mmadaio , @michaelamoako ) could outline your ideas here in detail to decide who can do which part :-)
For good measure I'll also tag @hannawallach in case she has any thoughts.

**Comment by romanlutz** [comment]
I just realized #707 also discussed this. @hildeweerts @LisaIbanez @riedgar-ms and @LeJit participated there, too, and may have thoughts, too :-)

**Comment by michaelamoako** [comment]
@romanlutz could you changed linked PR to #787

**Comment by mmadaio** [comment]
> Measurement and Fairness is still on my desk (and I wouldn't mind reading it again 🥰), do you already have a list of key terms in mind? I'd be interested in collaborating on this issue, but I lack the STS background (at the moment).

Ah, thanks for flagging @shimst3r! I should have been more clear in the issue. This is referring to the sub-sections of construct validity from the Measurement and Fairness paper, including:

- face validity
- content validity
  - contestedness
  - substantive validity
  - structural validity
- convergent validity
- discriminant validity
- predictive validity
- hypothesis validity
- consequential validity
