### ISSUE TITLE
Delete `master` branch

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#776]
I just realized we still have the `master` branch somehow. It should be deleted. People may keep sending PRs to that branch by mistake: https://github.com/fairlearn/fairlearn/pull/771

cc @fairlearn/fairlearn-maintainers

**Comment by romanlutz** [comment]
Absolutely! I talked about this with @riedgar-ms today as well. Let's do it!

**Comment by adrinjalali** [comment]
Done and gone.
