### ISSUE TITLE
Use icons for Twitter, StackOverflow, and Gitter

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#791]
Our current website has the following in the top right corner:
![image](https://user-images.githubusercontent.com/10245648/117505684-4d4fbc80-af39-11eb-9d3a-3dddc336556e.png)

Pydata-sphinx-theme just added an update that allows us to customize icons: https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html#configure-icon-links

The GitHub one is already correct. Twitter is also available, but we haven't uncommented that line in `docs/conf.py` yet since we weren't using the account. That changed to day, of course, so we should add the icon.

For StackOverflow and Gitter there were no icons available, but the link above shows how to add them.

This would require upgrading `pydata-sphinx-theme`, probably to the latest version. This may introduce other conflicts.

**Comment by romanlutz** [comment]
Of course, but you're proposing something that takes between 5 and 50 hours for an experienced person (sphinx themes are very non-trivial) while I'm proposing a ~15-60 minute fix for a new contributor. :-)
Whenever someone actually wants to come in and create our very own sphinx theme they can certainly unify all the headers and footers, but that's out of scope for what I'm proposing (which is just to get rid of the inconsistency between links and icons).

**Comment by MiroDudik** [comment]
good point. i wonder if there's a bit of a middle ground--use the current sphinx theme to get a similar look as the landing page nav bar (this would mean removing gitter / stackoverflow, changing the names of sections to match, and replacing github logo).

the second part would be to adjust footer -- at the minimum the copyright statement, and if possible then add links (not sure if sphinx allows that easily).

**Comment by romanlutz** [comment]
You're already in the 2-10 hour range (and that assumes some familiarity with sphinx). I am really open to having your suggestion as another issue, but this one is just about providing a small item for someone to get started in contributing (hence the tags). I suspect the result will remain on our webpage for at least a year before we make such sweeping changes. Plus, it's a fantastic way to get started using sphinx!

**Comment by trangology** [comment]
Hi @romanlutz, I'd like to work on this issue! 😃

**Comment by romanlutz** [comment]
Welcome! It's generally been prepared for anyone getting started. Thanks for picking this and let me know if you have any questions. I will be at the mentored sprint (Americas) today and development sprints Monday/Tuesday, but we can discuss this (or the project more generally) at any time. If you're on the sprints Discord you should find me there with the same alias. After the sprints there is always our Fairlearn [Gitter](https://gitter.im/fairlearn/community). Obviously the best place to ask about this particular issue is right here, but these channels are better in case there's anything else you're curious about. Thanks for contributing!

**Comment by trangology** [comment]
Will definitely reach out to you if I encounter any issues. Thanks for creating these issues to help newcomers like me get started contributing to open-source projects! ✨

**Comment by trangology** [comment]
Hey @romanlutz, I just jumped into this issue when building the docs using Sphinx. 

The command I used for this building is `python -m sphinx -v -b html -n -j auto docs docs/_build/html` as it's described at https://fairlearn.org/main/contributor_guide/contributing_documentation.html#contributing-documentation

I also have upgraded the version of `pydata-sphinx-theme` inside the `requirement-dev.text` file as you mentioned in this issue details. Any ideas?

![image](https://user-images.githubusercontent.com/37827647/118403841-08ceca00-b679-11eb-9894-31deafa03fa4.png)

**Comment by romanlutz** [comment]
@trangology it looks like everything's running fine from what I can tell. The FairlearnDashboard warning is intentional and should actually show up. The first time you build it there should also be a ton of other warnings at the end (often printed in red which makes them quite scary looking), but no errors. Did it finish running? Where there any other messages?
The command you're using with Sphinx mentions `-v` so this is going to be verbose, hence all this output. I do think that's good for development purposes, but it can be a bit strange when using this for the first time.

**Comment by trangology** [comment]
Oh yeah, forgot about the `-v` flag, which is denoted as `verbose`. Here is the current issue, this generation has been running for more than 5 mins without any changes in the percentage 🤔 

![image](https://user-images.githubusercontent.com/37827647/118404724-be4f4c80-b67c-11eb-9716-e284f6567691.png)

**Comment by romanlutz** [comment]
The first time it takes quite a while I'm afraid. I'd wager around 5-10 minutes. The good news is after that it's a lot faster. It has to run all our examples on the first run and store the outputs. Hang in there! :-) If it takes longer than 15 minutes something is definitely off.

**Comment by trangology** [comment]
Yes, you are right about the timing. But I need to go off for an hour or so. Will get back to it ASAP. Super excited to get it done! 🙂

**Comment by romanlutz** [comment]
Good to hear! No worries at all, take your time. Thanks for joining @trangology 😄

**Comment by trangology** [comment]
Hey @romanlutz. I'm back to work on this issue!

Here is what I have after reading the `pydata-sphinx-theme` docs. 

![image](https://user-images.githubusercontent.com/37827647/118413282-2024ac00-b6a7-11eb-8f3a-531e2583c1cf.png)

What makes me stuck is I don't know why Twitter & GitHub icons can be displayed, but not other icons.  We do have StackOverflow & Gitter icons on [FontAwesome free](https://fontawesome.com/icons?d=gallery&m=free):

- https://fontawesome.com/icons/gitter?style=brands
- https://fontawesome.com/icons/stack-overflow?style=brands

I can't seem to be able to figure this out. Could you help me with it? 😁

**Comment by romanlutz** [comment]
Closing since it's merged 🙂  Thanks again @trangology
