### ISSUE TITLE
DOC: migrate version upgrade guide for v0.2->v0.3 to the corresponding user guide section

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#798]
#### Describe the issue linked to the documentation

The [Development process](https://fairlearn.org/main/contributor_guide/development_process.html) page of our doc has instructions on how to upgrade from v0.2 to v0.3
![image](https://user-images.githubusercontent.com/10245648/117921140-0c430980-b2a5-11eb-8a33-3e27b35cc236.png)

These should live in the [Migrating from prior versions](https://fairlearn.org/main/user_guide/migrating_versions/index.html#migrating-from-prior-versions) section instead.

#### Suggest a potential alternative/fix

Move the docs from https://github.com/fairlearn/fairlearn/blob/main/docs/contributor_guide/development_process.rst to a new file `migrating_to_v0_3 under https://github.com/fairlearn/fairlearn/tree/main/docs/user_guide/migrating_versions

Additionally, we should also make the creation of such a migration file a part of our release process. For that purpose, the [release process instructions](https://fairlearn.org/main/contributor_guide/release.html) should be extended. Specifically, step 9 needs another substep to say "Create a migration guide from the previous version to the new version under `docs/user_guide/migrating_versions`"

**Comment by MeekaElla** [comment]
Hi! @romanlutz I would like to work on this as part of the mentored sprint. I am still a very beginner in Python so I'm trying to find some issues that are doable at my level. My understanding of this issue is just moving the docs from document process to a new file under the migrating versions. Is that right?

**Comment by romanlutz** [comment]
That's correct! It's meant to get a first issue in and to familiarize yourself with the repository/doc build. Let me know if you need any help! I'm available as part of the mentored sprints for another ~2 hours, but also asynchronously beyond that, of course.

**Comment by MeekaElla** [comment]
Thank you! I will be working on it right now. Just another clarification as per the release process instructions, I will be making a new branch called release/v0.6.3 right? once I made a PR on it should the branch contains the all of the changes that I made? or is it a separate PR?

**Comment by romanlutz** [comment]
@MeekaElla you don't need to follow the release instructions. They're just for maintainers when pushing out a new package release. I linked them above only to indicate that the release instructions should get an additional point. The branch names starting with `release` are actually protected, so I'd suggest something different, e.g., `update_release_instructions`. You can also put all your changes in the same branch, no need to have multiple PRs, unless you prefer that.

**Comment by MeekaElla** [comment]
Ohh noted. Thank you! I'm still familiarizing myself with Git and the branches are kinda confusing me xD This sprint is a really great learning opportunity for me.

**Comment by romanlutz** [comment]
No problem! I've written about this a little in the instructions steps 6-8 https://github.com/romanlutz/fairlearn-pycon-sprint/blob/main/README.md
But I'm also around for a little while longer in case you want to look at it together.

**Comment by MeekaElla** [comment]
Thank you so much!
