### ISSUE TITLE
Stop MetricFrame errors on nonscalar metrics

### ISSUE THREAD

**Issue by riedgar-ms** [fairlearn/fairlearn#800]
#### Is your feature request related to a problem? Please describe.

`MetricFrame` is quite relaxed as to the return values of the metric functions it evaluates. For example, it is perfectly possible to return a confusion matrix or a confidence bound from a metric function.

However such metrics will cause a problem if the user tries calling `group_min()`, `group_max()`, `difference()` or `ratio()` on the resultant `MetricFrame` since those operations are only well defined for scalars.

Currently, we (or rather `pandas`) will throw an exception. This is defensible if only a single metric is being computed by the `MetricFrame` but is likely to lead to a lack of user delight if there are other metrics present for which those operations do make sense. In particular, if a user has constructed a `MetricFrame` consisting of both the `accuracy_score` and `accuracy_score_confidence_interval` then they would reasonably expect `group_min()` to give a useful answer for the `accuracy_score` column.

#### Describe the solution you'd like

Catch any exceptions from `group_min()` and `group_max()` and emplace `NaN` in this case.

#### Describe alternatives you've considered, if relevant

Without this, users are forced to split up related metrics into separate `MetricFrame` objects.

#### Additional context

This is important for #235

**Comment by romanlutz** [comment]
@vamsidesu5 would this be interesting for you?

**Comment by vamsidesu5** [comment]
@romanlutz Yup I can pick this up! Any suggestions on what to read up on so I can understand the issue better and contribute faster? I'm new so not too familiar with all the vocabulary and functions.

**Comment by hildeweerts** [comment]
Hi @vamsidesu5 - I think [section 2.1 of our user guide](https://fairlearn.org/v0.6.2/user_guide/assessment.html#metrics) and the [API Reference of MetricFrame](https://fairlearn.org/v0.6.2/api_reference/fairlearn.metrics.html) would be good places to get started.

Here's a small code example to show what the issue is:

```python
from fairlearn.metrics import MetricFrame
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

y_true = [0, 0, 0, 0, 1, 1, 1, 1]
y_pred = [0, 0, 0, 1, 1, 1, 1, 0]
sensitive_features = [1, 1, 0, 0, 1, 1, 0, 0]

mf = MetricFrame(metric= { 'accuracy_score' : accuracy_score, 'confusion matrix' : confusion_matrix},
            y_true = y_true,
            y_pred = y_pred,
            sensitive_features = sensitive_features)
```

Now, if we print the results in `mf.by_group` that works perfectly fine:

```python
                    accuracy_score  confusion matrix
sensitive_feature_0                                 
0                              0.5  [[1, 1], [1, 1]]
1                                1  [[2, 0], [0, 2]]
```

However, if we do `mf.difference()`, which computes the difference of each metric between the two groups, pandas raises `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`. The reason is that the 'confusion matrix' column of `mf.by_group` contains arrays instead of floats. This is expected, but not a good user experience. In particular, it would have been possible to compute difference for `accuracy_score` if we hadn't put in the confusion matrix as well:

```python
mf = MetricFrame(metric= { 'accuracy_score' : accuracy_score},
            y_true = y_true,
            y_pred = y_pred,
            sensitive_features = sensitive_features)

mf.difference()
```

which simply outputs:

```
accuracy_score    0.5
dtype: float64
```

I hope this makes things a bit clearer. If you have any questions, feel free to reach out. Also, if you feel like the user guide is unclear in any way, please raise an issue as well - all feedback is super valuable :)

**Comment by riedgar-ms** [comment]
Thanks for adding that repro code @hildeweerts

**Comment by vamsidesu5** [comment]
@hildeweerts Thank you so much for the explanation - getting to work on it!

**Comment by vamsidesu5** [comment]
So the solution here is to throw an exception whenever the output from a function run on a MetricFrame such as mf.groupby() whenever the the output does not consist of all floats?

**Comment by romanlutz** [comment]
That sounds correct to me. A slight correction perhaps: scalar can be `int`, too, and maybe other types. I'd suggest going with something like https://numpy.org/doc/stable/reference/generated/numpy.isscalar.html to check.

@hildeweerts @riedgar-ms you wouldn't expect it to still work for the other metrics and ignore the ones that don't return scalars, right?

**Comment by hildeweerts** [comment]
If I read @riedgar-ms's issue correctly I actually think the idea was to ignore the ones that don't return scalars. Right now there is already a `ValueError` so there's not really a need to throw a new exception, apart from providing the user with a more meaningful message. 

I think it would make sense to return the value for the ones that are scalar and `NaN` for those that aren't, potentially with a warning message that says something like "Some of the metrics are not scalar and `NaN` is returned". Or we could even add an argument which controls how to handle such errors, I've seen a similar `errors` argument in pandas (e.g., [`pd.to_numeric`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_numeric.html)), where you can choose to `'raise'`, `'coerce'`,  or`'ignore'` invalid values. Though that might be a bit overkill for our scenario, it can be quite useful I think.

**Comment by riedgar-ms** [comment]
@hildeweerts is correct; the issue is that if one has mixed scalar and non-scalar metrics in a single `MetricFrame`, it is no longer possible to call `difference()` etc. on that `MetricFrame`. That may be a problem for some users (in fact, we already know it is).

I do like @hildeweerts 's suggestion of a `errors` argument (defaulting to `ignore` in this case).

**Comment by hildeweerts** [comment]
Assuming the thumbs up from @romanlutz means that he agrees, I think the `errors` argument is the way to go.

@vamsidesu5 is this enough information for you to get started with this issue? Please feel free to ask questions if anything is unclear!

**Comment by vamsidesu5** [comment]
@hildeweerts Thanks - that helps - I'll keep you guys updated here

**Comment by romanlutz** [comment]
This issue is up for grabs again 🙂

**Comment by bram49** [comment]
I would like to pick this up
