### ISSUE TITLE
Math doesn't render properly anymore on webpage

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#810]
#### Describe the issue linked to the documentation

The following is one of many similar examples from https://fairlearn.org/main/user_guide/fairness_in_machine_learning.html
![image](https://user-images.githubusercontent.com/10245648/118598484-fa5cdd00-b762-11eb-8e31-dcea6e1cce58.png)

#### Suggest a potential alternative/fix

Find a way to make it work again. Perhaps something changed about the way LaTeX is rendered in our sphinx theme (?)
I don't have any idea why it's not working (yet).

**Comment by riedgar-ms** [comment]
One clue: those pieces which aren't rendering are defined as custom LaTeX macros:
https://github.com/fairlearn/fairlearn/blob/389159c5c6d30479742ad6ab268964fe50d2fa2f/docs/conf.py#L212
I don't know what's going on, but it's obviously to do with the macro support.

**Comment by romanlutz** [comment]
One way to fix it would be to replace the occurrences of the macro throughout the files, but I really like the macros :-(

**Comment by iofall** [comment]
I can help with this

**Comment by romanlutz** [comment]
Great! This looks like it'll require some investigation. Are you familiar with the documentation build? https://fairlearn.org/main/contributor_guide/contributing_documentation.html
