### ISSUE TITLE
Homepage: link to contributor guide directly

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#826]
#### Describe the issue linked to the documentation

When clicking on "Contributor guide" on the homepage we are currently moving to the banner shown below. That's not needed. 
![image](https://user-images.githubusercontent.com/10245648/119792871-ea43ac80-be8a-11eb-8aa9-c25a0970e2f7.png)

#### Suggest a potential alternative/fix

Instead, we should just directly link to the contributor guide. This should be as simple as a single link replacement in https://github.com/fairlearn/fairlearn/blob/f3e23d2cfc66b1677c2d62d1cb13d0fda115a13f/docs/static_landing_page/index.html#L45

**Comment by Godwindaniel10** [comment]
hi @romanlutz 
i will like to solve this issue

**Comment by hildeweerts** [comment]
Awesome, I have assigned the issue to you @Godwindaniel10. Let us know if you have any questions!

**Comment by Godwindaniel10** [comment]
ok , on it...
Thanks.

i was trying to clone the repo , but its not cloning.

![cmd error](https://user-images.githubusercontent.com/54848535/119872586-903ef780-bf1b-11eb-8177-c6c558ed30e6.JPG)

**Comment by romanlutz** [comment]
Looks like a network issue to me. I would delete the potentially created directory and retry.

**Comment by romanlutz** [comment]
Closing since #828 fixes this!
