### ISSUE TITLE
Add user guide section on persisting metrics using pickle

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#827]
#### Describe the issue linked to the documentation

Persisting metrics and loading them back into memory is often useful. We don't currently mention this anywhere but `fairlearn.metrics.MetricFrame` can be pickled and then loaded at a later point for further analysis.

#### Suggest a potential alternative/fix

Add a section to the user guide on assessment that shows a short snippet of code for dumping & loading the object.
```
mf = MetricFrame(...)
pickle.dump(mf, open(file_name, 'wb'))
pickle.load(open(file_name, 'rb'))
```
Ideally this should be in a `doctest` block like other code in the user guide so that we run this on every doc build.

**Comment by MikeyHV** [comment]
Hello! I will try and work on this issue.

**Comment by riedgar-ms** [comment]
Looking through old PRs, I noticed #908 ... Pickling is rather fragile; should we be adding save/load to `MetricFrame` ? That is, is this really a feature request, not a doc request?

**Comment by romanlutz** [comment]
That's fair. I commented on the PR to see if @MikeyHV is still interested in continuing. Is there anything in particular we should add to the description of the issue or do you think it's fairly straightforward? I can think of

- Save/load on MetricFrame and corresponding tests
- the doc section this issue was created for

**Comment by TamaraAtanasoska** [comment]
@romanlutz is this issue ready to be closed? I see a PR merged that references it, but is it done in full?

**Comment by romanlutz** [comment]
Looks like we decided this is sufficient despite @riedgar-ms 's comment about having a method on the class instead. I guess this works the same...
