### ISSUE TITLE
Fix comment in postprocessing API documentation

### ISSUE THREAD

**Issue by ziqi-ma** [fairlearn/fairlearn#831]
Hello! Line249 of fairlearn/fairlearn/postprocessing/_tradeoff_curve_utilities.py accumulates 
`false_positives=count[0]
true_positives=count[1]
`
Shouldn't they be true_negatives=count[0] and false_negatives=count[1]? (since you are accumulating in ascending order how many counts are < threshold, thus yhat= 0 which conflicts with definition on lines244 and 245(P[Y_hat=1 | Y=0], P[Y_hat=1 | Y=1])?

I think this is fine if ROC of two classes's ROC curves intersect, but would be problematic when one class needs to be randomized?

**Comment by romanlutz** [comment]
The default is a rule `> threshold`, and `< threshold` is only considered if the `flip` argument is set to `True`. Does that resolve your doubt?

**Comment by ziqi-ma** [comment]
> The default is a rule `> threshold`, and `< threshold` is only considered if the `flip` argument is set to `True`. Does that resolve your doubt?

I think the implementation of flip=True vs. flip=False is reversed? (for my previous comments I'm only talking about the > threshold case, which is the default)

**Comment by MiroDudik** [comment]
Maybe the issue is that scores are sorted in descending order, so our comment is actually incorrect, but implementation is correct?

**Comment by ziqi-ma** [comment]
Oops sorry never realized that... Closing this.

**Comment by MiroDudik** [comment]
@ziqi-ma : no worries--it's actually our fault, we should fix the comments!

**Comment by romanlutz** [comment]
Then let's reopen to fix the comment! 🙂 
@MiroDudik you mean this line, right? https://github.com/fairlearn/fairlearn/blob/fed04c6149ceb7c691fd496ee594cd08c7ba5cc5/fairlearn/postprocessing/_tradeoff_curve_utilities.py#L278

**Comment by MiroDudik** [comment]
I saw an incorrect comment at two locations at least. Besides the one you mention, also here:
https://github.com/fairlearn/fairlearn/blob/fed04c6149ceb7c691fd496ee594cd08c7ba5cc5/fairlearn/postprocessing/_tradeoff_curve_utilities.py#L224

**Comment by bram49** [comment]
Hello! I will be picking this up as a good first issue to get familiar with open-source development.
I will change the two comments and scan the document for more increase / ascending mistakes.

**Comment by bram49** [comment]
Send out a pull request.
Hope I did everything right, if not please let me know.
This will be my first contribution to fairlearn :) 
https://github.com/fairlearn/fairlearn/pull/889
