### ISSUE TITLE
Add code coverage test to the CI

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#847]
We can add https://about.codecov.io/ to the CI, to make sure the PRs are all tested.

**Comment by riedgar-ms** [comment]
We do have a code coverage build:
https://dev.azure.com/responsibleai/fairlearn/_build?definitionId=24&_a=summary
Or is that not generally visible? We still haven't quite figured out permissions on that VSO tenant.

**Comment by riedgar-ms** [comment]
It only runs on `main` (that can be changed). Why would it fail, though?

**Comment by adrinjalali** [comment]
Because for instance when #822 adds code which is not tested, we should see that it needs tests to improve the coverage. We shouldn't approve any PRs unless they also add the appropriate tests.

**Comment by riedgar-ms** [comment]
So you'd like to gate on code coverage%? Would you like to include branch coverage as well?

**Comment by adrinjalali** [comment]
I don't think branches matter at this point, we can add this for the future. As long as we fail on newly written code, gradually things will get better.

**Comment by riedgar-ms** [comment]
Just realised that 'branch' is ambiguous in this context. I was meaning in the `if/else` sense.... is that what you meant?

How would you want the threshold set? We're currently at >95%, which is well into "increasing code coverage tells you nothing" territory. I do see that the [codecov service you linked has a 'patch' setting](https://docs.codecov.io/docs/commit-status#patch-status) which requires code coverage on any changed lines. A threshold on that might be more useful?

**Comment by adrinjalali** [comment]
Yes, I think we should set it to 100% for patch, and 98% overall as threshold for PRs.

**Comment by riedgar-ms** [comment]
That's very high. I don't want us to slide from what we have, but as I said there comes a point where you have diminishing returns and there are better places to focus effort. After all,100% code coverage doesn't tell you that you've missed a complete scenario.

**Comment by adrinjalali** [comment]
It doesn't, but anything less than 100% on patch, tells you that there's new untested code in the PR. It's really not hat hard to make sure the code is run at least once in at least one of the tests. Also, we can always merge ignoring the coverage if we think a test is not needed for a particular line of code. But in my experience, you definitely want tests for everything you write, at least one code.

**Comment by romanlutz** [comment]
Bumping this as it came up in a PR (mentioned by @adrinjalali).

I did the setup/connection to codecov. Now all that's required is to generate the coverage report (.xml) and add upload commands to our pipelines.

Linux:
```
curl -Os https://uploader.codecov.io/latest/linux/codecov chmod +x codecov ./codecov
```

Mac:
```
curl -Os https://uploader.codecov.io/latest/macos/codecov chmod +x codecov ./codecov
```

Windows:
```
$ProgressPreference = 'SilentlyContinue' Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe .\codecov.exe
```
