### ISSUE TITLE
Test for deprecation warnings

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#848]
Our CI should test and fail for `DeprecationWarning` and `FutureWarning`. This can be done by passing `-Werror::DeprecationWarning -Werror::FutureWarning` to `pytest`.

We can enable this for at least a few of the tests if not all.

**Comment by riedgar-ms** [comment]
Is there any way to restrict this to our direct dependencies? For example, [in a recent build](https://dev.azure.com/responsibleai/fairlearn/_build/results?buildId=12007&view=logs&j=aa2fd561-a338-5537-45ee-49ae22aea958&t=7d222596-41fc-5765-4dd3-df02a80934d4&l=163) there's a deprecation warning on `ansiwrap` but that's being brought in by some other package.

**Comment by adrinjalali** [comment]
I think you can ignore certain warnings: 

https://github.com/scikit-learn/scikit-learn/blob/main/setup.cfg#L20

**Comment by romanlutz** [comment]
Didn't #1171 already address this? From a brief search I found that we're basically configuring all warnings to be errors unless explicitly excluded in the pyproject.toml file as @MiroDudik put it in #1171. So we should be able to just close #1278 , right? @MiroDudik can you confirm and close PR and issue if this is right?
