### ISSUE TITLE
[Website Redesign] Replace Logo

### ISSUE THREAD

**Issue by nessamilan** [fairlearn/fairlearn#858]
New logotype for word "Fairlearn" in progress

**Comment by nessamilan** [comment]
**Updated logo for header**

[Logo Lockup](https://www.figma.com/file/wt76z0M87RBDDEoyAEpD2g/OPEN-SOURCE-Fairlearn-Redesign?node-id=2672%3A2719)
Update using SVG. Note that colors will change based on finalized color theming

**Comment by hildeweerts** [comment]
Looks good, @nessamilan!

**Comment by romanlutz** [comment]
@nessamilan I tried the steps you mentioned above, but I can only export the individual pieces, so it ends up as 4 SVG files (3 rectangles for the bars and the Fairlearn text). Any chance they could be exported together?

**Comment by hildeweerts** [comment]
@romanlutz to expert as one image you have to select it in the pane on the lefthandside: 
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/24417440/128320443-5d47db24-1883-4cd3-898d-a8d2d3ddea96.png">
