### ISSUE TITLE
DOC: remove duplicates index example notebooks

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#872]
#### Describe the issue linked to the documentation

The lefthand side index of our [Example Notebooks](https://fairlearn.org/main/auto_examples) contains duplicate items. I think this is because some are [in the `toctree` of README.rst](https://github.com/fairlearn/fairlearn/edit/main/examples/README.rst) as well as in the automatically generated examples.

#### Suggest a potential alternative/fix

Remove the items from README.rst and only show automatically generated examples.

@fairlearn/fairlearn-maintainers 

*[if you want to work on to this issue, please let us know in the comments.]*

**Comment by Fyrebright** [comment]
Hello, I have made the change and verified it a local build. I will go ahead and make a PR.

**Comment by romanlutz** [comment]
#873  was merged, so I'm closing this issue.
