### ISSUE TITLE
DOC replace Gitter with Discord on the webpage

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#886]
#### Describe the issue linked to the documentation

Our website points people to Gitter even though our Discord is much more active and not mentioned anywhere. We should replace occurrences of Gitter with Discord.

- nav bar at the top 
![image](https://user-images.githubusercontent.com/10245648/124847369-90d1a180-df4f-11eb-970f-1ca165260250.png) find code at `docs/conf.py`, specifically [these lines](https://github.com/fairlearn/fairlearn/blob/378f1e693cff01c69de3a9d9504b336ae1e0064e/docs/conf.py#L134)
- [landing page](https://fairlearn.org/) 
![image](https://user-images.githubusercontent.com/10245648/124847419-ac3cac80-df4f-11eb-913e-4788493eecc6.png) find code at `docs/static_landing_page/index.html`
- https://fairlearn.org/main/contributor_guide/index.html#real-time-communication, find code at `docs/contributor_guide/index.rst`

Note that older versions will still say Gitter so we can't delete our Gitter or abandon it completely, but we might as well point people in the right direction without adding another hop.

**Comment by adrinjalali** [comment]
How do we get a permanent discord invite link?

**Comment by hildeweerts** [comment]
@adrinjalali You can set the settings of the invite link under ‘link settings’. This link will allegedly never expire and has unlimited uses: https://discord.gg/R22yCfgsRn

**Comment by shimst3r** [comment]
Following the instructions, `make doc` yields the following warning:
```shell
WARNING: 'pypandoc' not available. Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
```
Is this expected or did I miss something in the setup process? :nerd_face:

**Comment by romanlutz** [comment]
The latest version mentions the pandoc installation: https://fairlearn.org/main/contributor_guide/contributing_documentation.html
It's not related to the icons, though, so it's up to you whether you want to do that.

BTW this is the right icon https://fontawesome.com/v5.15/icons/discord?style=brands and the color should probably be sort of like this: https://en.wikipedia.org/wiki/Discord_%28software%29#/media/File:Discord_logo.svg
