### ISSUE TITLE
DOC Add funding page to highlight institutions that support Fairlearn

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#888]
From #433: add a funding page to highlight which institutions support(ed) the development of Fairlearn, similar to [scikit-learn](https://scikit-learn.org/stable/about.html#funding) or [pandas](https://pandas.pydata.org/about/sponsors.html).

Two open questions:
* *Where should the page live?* I think a section under *About Us* would make the most sense. Additionally, we could add some logos and/or link to section in the footer (like scikit-learn) or on our home page (like pandas).
* *What should be on it?* IMO the minimal version should have a header with a tittle like *Funding* and a simple list of organizations and how they are involved (e.g., *Organization X funds person Y since Z*). Can be with logos but a first version could be a simple list.

Thoughts? @fairlearn/fairlearn-maintainers

**Comment by adrinjalali** [comment]
I'm happy with either pandas or sklearn style

**Comment by romanlutz** [comment]
I prefer the scikit-learn style. So much nicer with logos and clear description.
Section within "About Us" works for me.
I think we also need to curate a list of what would be included so far. Perhaps I can get started with that.
