### ISSUE TITLE
DOC typo in control features documentation

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#892]
#### Describe the issue linked to the documentation

![image](https://user-images.githubusercontent.com/10245648/125114348-bae5a980-e09e-11eb-983b-47b366148eba.png)

should be

![image](https://user-images.githubusercontent.com/10245648/125114400-c89b2f00-e09e-11eb-9264-13653286df06.png)

**Comment by nishit-prasad** [comment]
Hello, I'm new and would like to contribute by starting small and then making my way up.
Can this be assigned to me?

I believe the necessary change has to be made here?https://github.com/fairlearn/fairlearn/blob/main/docs/user_guide/assessment.rst

**Comment by romanlutz** [comment]
That's correct @nishit-prasad ! It should say `control_features`. I'll assign it to you 🙂

**Comment by nishit-prasad** [comment]
@romanlutz PR is up and ready! 😄
