### ISSUE TITLE
Add code examples for API Reference section

### ISSUE THREAD

**Issue by kurianbenoy** [fairlearn/fairlearn#894]
#### Describe the issue linked to the documentation

This issue is related to adding usage examples in API reference guide. When some one is stumbling into API reference of Metrics Frame, a code example showing usage will greatly help the user.

For more context check the issue #730, https://github.com/fairlearn/fairlearn/issues/730#issuecomment-878110294

**Comment by rensoostenbach** [comment]
I noticed that only the metrics module has code examples in the API docs right now (as merged in https://github.com/fairlearn/fairlearn/pull/946), and I was wondering if the other modules would also benefit from some code examples. If so, I would like to work on that as a first issue!

**Comment by romanlutz** [comment]
They certainly would, @rensoostenbach ! If you want to try doing this perhaps start small and focus on just 1 class method/function, send it as a PR and see what people think. That way you can get feedback fast and iterate 🙂

**Comment by TamaraAtanasoska** [comment]
Closing this issue because of https://github.com/fairlearn/fairlearn/issues/1475
