### ISSUE TITLE
DOC sphinx fairlearn logo link is broken

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#899]
#### Describe the issue linked to the documentation

Currently, the Fairlearn logo in the docs generated by sphinx points to *"../_static/_static/images/fairlearn_full_color.png"* which doesn't exist. 

~~It seems that '_static' is currently prepended in `html_logo = "_static/images/fairlearn_full_color.png"` in conf.py even though we also define the `html_static_path = ['_static']`. I expect that this used to be a bug in sphinx and that it is now fixed there, breaking our link.~~ 

#### Suggest a potential alternative/fix

~~In [conf.py](https://github.com/fairlearn/fairlearn/blob/main/docs/conf.py) replace line 144:~~

~~`html_logo = "_static/images/fairlearn_full_color.png"`~~

~~with:~~

~~`html_logo = "/images/fairlearn_full_color.png"`~~

UPDATE: As shown in #901 this apparently wasn't the right solution. When we change the url like this the image cannot be found at all while building the docs (`WARNING: logo file '/images/fairlearn_full_color.png' does not exist`). 

UPDATE 2: It turns out we are not the only one with this issue: see [this issue](https://github.com/sphinx-doc/sphinx/issues/9438). So we need to make sure to update to sphinx 4.1.1 and then all will be fine.

**Comment by svenkat19** [comment]
I have replaced `html_logo = "_static/images/fairlearn_full_color.png"` in conf.py. Is there anything else I must look into? Pls guide me

**Comment by hildeweerts** [comment]
Hi @svenkat19! Did you open a pull request for the change? You can find more information on how to contribute to fairlearn in this helpful guide by @romanlutz: https://github.com/romanlutz/fairlearn-scipy-sprint/blob/main/README.md

And specifics on how to build the documentation locally can be found here: https://fairlearn.org/main/contributor_guide/contributing_documentation.html
