### ISSUE TITLE
Specific cutoff for Fair Regression 

### ISSUE THREAD

**Issue by Bee-zest** [fairlearn/fairlearn#90]
I just read the new paper (Fair Regression). Is it possible to just optimize some specific cutoff in Fair Regression? (e.g. 0.65 approval cutoff in lending business).

**Comment by Bee-zest** [comment]
> I am assuming that you are talking about ensuring that demographic parity holds if you threshold at 0.65. 
Yes. In fairlearn paper, the loss is  `err(Q) + DP`, and the `err(Q)` is the misclassification error.  If I want to optimize 0.65 cutoff under DP constraints, is it ok to change the fairness constraints part `DP` to support the 0.65 cutoff instead of the 0.5?

**Comment by MiroDudik** [comment]
is err(Q) misclassification at 0.5 or at 0.65?

**Comment by Bee-zest** [comment]
> is err(Q) misclassification at 0.5 or at 0.65?

It's at 0.5. I don't think 0.65 cutoff makes any sense for misclassification error.

**Comment by romanlutz** [comment]
Closing this since it doesn't relate to current implementations and has gone stale since. If this is still an area of interest please reopen. Thanks!
