### ISSUE TITLE
CircleCI credits and issues

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#927]
Seems like CircleCI isn't giving open source projects unlimited credits anymore.

As @romanlutz  said on discord: 

> Looks like it's not triggering for new pull requests. I checked their pages and can't really find anything definitive, but it seems like we have 2,500 weekly credits of which we've used 2,342. That sounds like we still have some... That said, this is for the week starting Aug 1, so it definitely looks like our usage is high for this tier. They're trying to sell us a $60/month plan.

We should investigate this issue and figure out how we can proceed. I'll check what we have on the sklearn side.

@amueller do you happen to know anything related to this?

cc @fairlearn/fairlearn-maintainers

**Comment by adrinjalali** [comment]
So it seems they've been nice to us on the sklearn side so far, we're using way more than the free credit, and we'd need to pay $180/month for our usage:

![Screenshot from 2021-08-04 12-03-13](https://user-images.githubusercontent.com/1663864/128162994-329ba8ca-9144-4262-a24f-c518bed0d7d0.png)

I agree with @romanlutz that if this is how it's gonna be, we should somehow move to another solution.

**Comment by romanlutz** [comment]
Update: I got a response!

> Hi Roman,
> 
> Thank you for contacting CircleCI Support!
> 
> Sorry to hear you are having trouble getting your builds to trigger.
> 
> Would it be possible to get the webhook ID/payload for a PR from your project that was supposed to trigger a build? With this, it will give me more insight into what is blocking you.
> 
> https://support.circleci.com/hc/en-us/articles/360021511153-How-to-view-your-GitHub-webhook-deliveries
> 
> I do not think it is related to credits as there would be some indication of that on the dashboard (a workflow should still appear even if it is blocked due to no credits).
> 
> Please feel free to ask any additional questions as well!
> 
> Best Regards
> 
> [name omitted]
Support Engineer @ CircleCI

The webhooks tab turns out to be empty, so we'll see what they can find. The quick response is certainly encouraging. In parallel I'm trying a few other things that could solve this long-term...

**Comment by romanlutz** [comment]
I think I managed to resolve this with help from CircleCI! The problem turned out to be that my fork romanlutz/fairlearn got added (or technically: "followed", whatever that means) and it confused CircleCI. Lesson learned: don't add forks to CircleCI!

After "unfollowing" I pushed an empty commit to a PR of mine that was lacking builds (#925), and voila, they're back! I'll close this issue accordingly, but if this shows up again please reopen.

I will say this: CircleCI support was first rate, and extraordinarily quick in responding given that we're not a paying customer.

**Comment by romanlutz** [comment]
Final update on credits since CircleCI responded in direct reference to my assumption about credits:
> I took a look at the Github issue you linked in your tweet and thought I would give some clarification regarding credits for free plans.
> For open source linux builds, you can use 400,000 credits per month (macOS is 25,000 credits), but those totals won't appear on the plan usage page. I believe it currently shows it as a negative balance.

So my worries were entirely unjustified 🙂 That is probably the same thing you're seeing for scikit-learn @adrinjalali.

**Comment by adrinjalali** [comment]
Awesome, thanks for checking Roman
