### ISSUE TITLE
Keyword Arguments Change Affecting Fairness Dashboard

### ISSUE THREAD

**Issue by michaelamoako** [fairlearn/fairlearn#933]
With the new change that arguments must be keywords, a warning is thrown when attempting to pass in multiple predictions into y_pred as shown in the sample code below. This seems to be an issue specifically in the dashboard.

#### Describe the bug

Key work argument requirement leading to bug in the Fairness dashboard, but not in the API 

#### Steps/Code to Reproduce
```python
FairnessDashboard(sensitive_features=sensitive_cols,
                y_true=golden_labels,
                y_pred=predictions)
```

#### Expected Results
No error is thrown.

#### Actual Results
You have provided 'metrics', 'y_true', 'y_pred' as positional arguments. Please pass them as keyword arguments. From version 0.10.0 passing them as positional arguments will result in an error.

#### Screenshots

![Model Comparison Error](https://user-images.githubusercontent.com/69976597/128803024-5dd9e0f8-e8bd-47d0-90e7-5232773629af.PNG)

**Comment by michaelamoako** [comment]
Unclear if this issue should be opened in RAI Widgets or here

**Comment by romanlutz** [comment]
This is an issue in `raiwidgets` which depends on Fairlearn. I'll move it over. Thanks for reporting @michaelamoako !
