### ISSUE TITLE
Bug when using custom Lagrange multiplier grids

### ISSUE THREAD

**Issue by AndreFCruz** [fairlearn/fairlearn#940]
#### Describe the bug

When passing a custom set of Lagrangian multipliers to the `GridSearch` reduction, via the `grid` kwarg, the loss computation for model selection throws a `KeyError`.

The multipliers at `self.gammas_`, which is a pandas.DataFrame, are being inserted using the name of the column as index.
See [line 162](https://github.com/fairlearn/fairlearn/blob/main/fairlearn/reductions/_grid_search/grid_search.py#L162) for the values of `i` and [line 194](https://github.com/fairlearn/fairlearn/blob/main/fairlearn/reductions/_grid_search/grid_search.py#L194) for how the values are inserted.

Afterwards, in [line 201](https://github.com/fairlearn/fairlearn/blob/main/fairlearn/reductions/_grid_search/grid_search.py#L201), these values are accessed assuming the indices are ordered integer values.
This works when using the default GridGenerator because the column names are indeed ordered integer indices, but not when providing a custom DF.

#### Steps/Code to Reproduce

Running a GridSearch reduction with a custom grid represented by a DF whose column names are not ordered integer indices.

#### Versions
This happens on all versions as far as I can tell, including the most recent on the `main` branch.

**Comment by romanlutz** [comment]
@riedgar-ms should we close this since #941 was merged?

**Comment by AndreFCruz** [comment]
Yep, closed :slightly_smiling_face:
