### ISSUE TITLE
ENH: Use flake8-pytest-importorskip

### ISSUE THREAD

**Issue by riedgar-ms** [fairlearn/fairlearn#957]
#### Is your feature request related to a problem? Please describe.

In the `test_othermlpackages` directory, we use `pytest.importorskip()` to make things better behaved when various packages aren't present. However, this means that subsequent imports have to have a `#noqa` suppression since they are technically placed after the first executable line.

#### Describe the solution you'd like

Consider using:
https://pypi.org/project/flake8-pytest-importorskip/
The package does note that it works in a 'slightly hacky' way, so sticking to the `#noqa` suppressions may be preferable.

**Comment by romanlutz** [comment]
Would the proposed change be to just install the package, and no code changes?

**Comment by riedgar-ms** [comment]
Remove the `#noqa` tags within `test_othermlpackages` as well

**Comment by adrinjalali** [comment]
but that means an extra dependency. I'm happy with what we have now.

**Comment by riedgar-ms** [comment]
Fair enough. I can see the argument that a few `# noqa` tags are better than bringing in another package.
