### ISSUE TITLE
DOC Restructure the assessment section of the user guide

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#977]
This first came up in #943 through [a comment](https://github.com/fairlearn/fairlearn/issues/943#issuecomment-914997930_) by @hildeweerts.

The existing headers and structure may not be ideal for helping users discover the section they're actually looking for and are somewhat confusing (as #943 shows). As we're working on the user guide anyway we should consider better ways to structure this section.

The original comment by @hildeweerts:
> All information in `MetricFrame` relate to group comparisons, which is why it is under 'Metrics with Grouping'. I can see why the headers might be a bit confusing though, as `MetricFrame.by_group` by itself is not strictly a metric on its own but a table of disaggregated "ungrouped" metrics, so some renaming/restructuring of this section is probably not a bad idea. On a related note, I'd also be in favor of retiring the Fairlearn Dashboard as a separate top-level header. This is all a bit out of the scope for this PR, though (we always try to keep PR's as small as possible to avoid blocking small (uncontroversial) changes by other changes that require more discussion). I'd suggest to open a new issue to re-evaluate the structure of the Assessment section of the user guide.

FYI @SeanMcCarren since he's the author of #943 (Thank you!) and may be able to point out additional parts that are confusing in the existing user guide.

**Comment by SeanMcCarren** [comment]
At first, I found it slightly confusing that every subsection of Metrics (except for the first) is about grouped metrics, while the header of the second subsection is called 'Metrics with Grouping'. Really no big deal though :)

**Comment by MiroDudik** [comment]
We should really update the material here to be more similar to how we talk about the assessment, e.g., in our [SciPy tutorial](https://github.com/fairlearn/talks/blob/main/2021_scipy_tutorial/fairness-in-AI-systems-instructors.ipynb).

**Comment by alliesaizan** [comment]
Hi @romanlutz @MiroDudik, I'd like to help out with some of the documentation tasks. This one seems pretty straightforward and appears to be unassigned. Please let me know if there are any other documentation tasks that are more pressing, otherwise I can start working on this!

**Comment by hildeweerts** [comment]
That would be really useful - I have assigned the issue to you, @alliesaizan! Let us know if anything is unclear.
