### ISSUE TITLE
DOC add user guide CorrelationRemover

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#990]
#### Describe the issue linked to the documentation

There is currently no user guide for `fairlearn.preprocessing.CorrelationRemover `.

#### Suggest a potential alternative/fix

Add a user guide for `fairlearn.preprocessing.CorrelationRemover `.

**Comment by rensoostenbach** [comment]
I will take this issue! Is there some sort of structure we would like to have in the user guide? E.g. when I look at [the current user guide for mitigation](https://fairlearn.org/main/user_guide/mitigation.html), most classes start with a textual/mathematical explanation what it is about, followed by a code example. I assume the textual/mathematical explanation can be partially taken from the [API docs](https://fairlearn.org/main/api_reference/fairlearn.preprocessing.html) of the `fairlearn.preprocessing.CorrelationRemover`, but I was wondering if there is a difference in writing style or so :).

**Comment by hildeweerts** [comment]
Yup, thanks for resurfacing this one @TamaraAtanasoska!
