### ISSUE TITLE
DOC make_derived_metric API ref should contain options for transform

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#993]
#### Describe the issue linked to the documentation

The [API ref entry for `make_derived_metric`](https://github.com/fairlearn/fairlearn/blob/v0.7.0/fairlearn/metrics/_make_derived_metric.py#L96-L155) currently does not contain the list of strings that can be used as argument for the `transform` parameter.

#### Suggest a potential alternative/fix

Add the list of options to the docstring, i.e., something like "one of `['difference', 'group_min', 'group_max', 'ratio']`"

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this. Is `['difference', 'group_min', 'group_max', 'ratio']` the complete list of options for the arguments?

**Comment by hildeweerts** [comment]
Yup, that's the whole list. Thanks @Carlosbogo, I will assign the issue to you.
