### ISSUE TITLE
DOC typo make_derived_metric API ref

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#994]
There is a small typo in the API ref entry of `make_derived_metric`.

In the sentence under Returns: *Function with the same signature as the metric but with additional sensitive_feature= and method= arguments, to enable the required computation*, `sensitive_feature` should say `sensitive_features`

**Comment by Carlosbogo** [comment]
Hi, I would like to help with this.

**Comment by hildeweerts** [comment]
Perfect! I will assign this issue to you as well, @Carlosbogo.

**Comment by Vibhaa5** [comment]
Hey, i want to solve this issue! Is this issue opened to solve?

**Comment by hildeweerts** [comment]
Hi @Vibhaa5, thank you for your interest! Currently @Carlosbogo is already working on this issue.

**Comment by hildeweerts** [comment]
Fixed by #995
